### ISSUE TITLE
zef leaves file in compunit when uninstalling '.'

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#100]
according to 'nine', using zef like "zef uninstall ." fails to remove the short name of the module in the compunit repository

**Comment by niner** [comment]
This may happen when the version of the dist in . does not contain all of the modules the installed version contains. Proper fix is to get the Distribution object from the CURI and pass that to $repo.uninstall

**Comment by ugexe** [comment]
fwiw zef does get the dist from CURI already

**Comment by ugexe** [comment]
`zef uninstall $path` should not even do anything. If you are talking about the empty directories in `short/` after doing `zef uninstall $identity` that is rakudo
