### ISSUE TITLE
Can't reinstall modules

### ISSUE THREAD

**Issue by labster** [ugexe/zef#109]
Literally the first four commands I've run with zef.  Nothing successful yet.

brent@ragnar ~/c/zef (master)> zef install XML
All candidates are currently installed
No reason to proceed. Use --force to continue anyway
brent@ragnar ~/c/zef (master)> zef install XML --force
===> Searching for: --force
^Cfish: Job 1, 'zef install XML --force' terminated by signal SIGINT (Quit request from job control (^C))
brent@ragnar ~/c/zef (master)> zef install --force XML
===> Searching for: --force
^Cfish: Job 1, 'zef install --force XML' terminated by signal SIGINT (Quit request from job control (^C))
brent@ragnar ~/c/zef (master)> zef uninstall XML
Failed to remove the file '/Users/brent/code/rakudo/install/share/perl6/site/short/013475CC1C654B266E6C7423AA789C0FBFC50355/8094D71F5CB6EDE3932C8B405D6469F2DFB986FF': Failed to delete file: not a directory
  in any  at /Users/brent/code/rakudo/install/share/perl6/runtime/CORE.setting.moarvm line 1
  in block  at /Users/brent/code/rakudo/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 552
  in method uninstall at /Users/brent/code/rakudo/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 548
  in sub MAIN at /Users/brent/code/rakudo/install/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 138
  in block <unit> at /Users/brent/code/rakudo/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1

Actually thrown at:
  in block  at /Users/brent/code/rakudo/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 552
  in method uninstall at /Users/brent/code/rakudo/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 548
  in sub MAIN at /Users/brent/code/rakudo/install/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 138
  in block <unit> at /Users/brent/code/rakudo/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1

**Comment by ugexe** [comment]
In Perl6 named parameters to a script come before positional, but you're passing --force after the positional 'install' in each case

**Comment by labster** [comment]
Yeah, but I'd still argue it's LTA behavior.  I think I've been trained by git to write action first, then options.  Not saying the behavior is wrong, but the positional arguments really should complain if they start with `-`.

**Comment by ugexe** [comment]
zef doesn't implement its own Getopts library - it uses Perl6's MAIN. Unless I'm misunderstanding something this is an issue that should be opened against Perl6/Rakudo

**Comment by labster** [comment]
Cool, thanks!
