### ISSUE TITLE
install Task::Star failed during Test::Mock

### ISSUE THREAD

**Issue by hkdtam** [ugexe/zef#119]
Hi,

My environment is 

`perl6 -v
This is Rakudo version 2016.12-214-g996ab6a built on MoarVM version 2016.12-60-g36f3385
implementing Perl 6.c.
`
and I did a `zef udpate` beforehand.

Here are the relevant error bits, thanks in advance for the help.

===> Testing [OK] for SVG::Plot
===> Testing: Test::Mock:ver('1.3')
t/computing.t ....... ok
t/new.t ............. All 4 subtests passed
t/overriding.t ...... ok
t/required-attrs.t .. ok
t/returning.t ....... ok
t/synopsis.t ........ ok
t/with.t ............ All 8 subtests passed
All tests successful.

Test Summary Report
-------------------
t/new.t  (Wstat: 0 Tests: 2 Failed: 0)
  Parse errors: Bad plan.  You planned 4 tests but ran 2.
t/with.t  (Wstat: 0 Tests: 5 Failed: 0)
  Parse errors: Tests out of sequence.  Found (5) but expected (2)
                Tests out of sequence.  Found (6) but expected (3)
                Tests out of sequence.  Found (7) but expected (4)
                Tests out of sequence.  Found (8) but expected (5)
                Bad plan.  You planned 8 tests but ran 5.
Files=7, Tests=24,  3 wallclock secs
Result: FAILED
===> Testing [FAIL]: Test::Mock:ver('1.3')
Aborting due to test failure: Test::Mock:ver('1.3') (use --force to override)
  in code  at /home/user/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 306
  in method test at /home/user/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 285
  in code  at /home/user/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 456
  in sub  at /home/user/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 453
  in method install at /home/user/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 559
  in sub MAIN at /home/user/.rakudobrew/moar-nom/install/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 122
  in block <unit> at /home/user/.rakudobrew/moar-nom/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1

**Comment by ugexe** [comment]
Does it pass if you install it via 'zef --prove install ...'?

If yes - it's a bug with perl6 TAP::Harness (included with Rakudo)
If no - it's a bug with how Test::Mock generates tap output

**Comment by ugexe** [comment]
The tests do pass when using `--/tap-harness` or when using rakudo 2016.12 (the actual release) or earlier.

So something between moar-2016.12 and moar-blead seems to have broken TAP::Harness

**Comment by ugexe** [comment]
Broken in https://github.com/rakudo/rakudo/commit/b183cabf41b5c42cce04f68743180386782ee788

**Comment by ugexe** [comment]
Fixed it latest Rakudo
