### ISSUE TITLE
zef fails to handle tests of JSON::Fast

### ISSUE THREAD

**Issue by gfldex** [ugexe/zef#120]
===> Testing: JSON::Fast:ver('0.7')
t/01-parse.t ...... All 93 subtests passed
t/02-structure.t .. All 10 subtests passed
t/03-unicode.t .... All 4 subtests passed
t/04-roundtrip.t .. ok
All tests successful.

Test Summary Report
-------------------
t/01-parse.t  (Wstat: 0 Tests: 75 Failed: 0)
  Parse errors: Tests out of sequence.  Found (13) but expected (12)
                Tests out of sequence.  Found (14) but expected (13)
                Tests out of sequence.  Found (15) but expected (14)
                Tests out of sequence.  Found (16) but expected (15)
                Tests out of sequence.  Found (17) but expected (16)
                Tests out of sequence.  Found (18) but expected (17)
                Tests out of sequence.  Found (19) but expected (18)
                Tests out of sequence.  Found (20) but expected (19)
                Tests out of sequence.  Found (21) but expected (20)
                Tests out of sequence.  Found (22) but expected (21)
                Tests out of sequence.  Found (23) but expected (22)
                Tests out of sequence.  Found (24) but expected (23)
                Tests out of sequence.  Found (25) but expected (24)
                Tests out of sequence.  Found (26) but expected (25)
                Tests out of sequence.  Found (27) but expected (26)
                Tests out of sequence.  Found (28) but expected (27)
                Tests out of sequence.  Found (29) but expected (28)
                Tests out of sequence.  Found (31) but expected (29)
                Tests out of sequence.  Found (34) but expected (30)
                Tests out of sequence.  Found (35) but expected (31)
                Tests out of sequence.  Found (36) but expected (32)
                Tests out of sequence.  Found (37) but expected (33)
                Tests out of sequence.  Found (38) but expected (34)
                Tests out of sequence.  Found (40) but expected (35)
                Tests out of sequence.  Found (41) but expected (36)
                Tests out of sequence.  Found (42) but expected (37)
                Tests out of sequence.  Found (43) but expected (38)
                Tests out of sequence.  Found (44) but expected (39)
                Tests out of sequence.  Found (45) but expected (40)
                Tests out of sequence.  Found (46) but expected (41)
                Tests out of sequence.  Found (47) but expected (42)
                Tests out of sequence.  Found (48) but expected (43)
                Tests out of sequence.  Found (54) but expected (44)
                Tests out of sequence.  Found (55) but expected (45)
                Tests out of sequence.  Found (56) but expected (46)
                Tests out of sequence.  Found (61) but expected (47)
                Tests out of sequence.  Found (62) but expected (48)
                Tests out of sequence.  Found (63) but expected (49)
                Tests out of sequence.  Found (64) but expected (50)
                Tests out of sequence.  Found (65) but expected (51)
                Tests out of sequence.  Found (66) but expected (52)
                Tests out of sequence.  Found (67) but expected (53)
                Tests out of sequence.  Found (68) but expected (54)
                Tests out of sequence.  Found (72) but expected (55)
                Tests out of sequence.  Found (73) but expected (56)
                Tests out of sequence.  Found (74) but expected (57)
                Tests out of sequence.  Found (75) but expected (58)
                Tests out of sequence.  Found (76) but expected (59)
                Tests out of sequence.  Found (77) but expected (60)
                Tests out of sequence.  Found (78) but expected (61)
                Tests out of sequence.  Found (79) but expected (62)
                Tests out of sequence.  Found (81) but expected (63)
                Tests out of sequence.  Found (82) but expected (64)
                Tests out of sequence.  Found (83) but expected (65)
                Tests out of sequence.  Found (84) but expected (66)
                Tests out of sequence.  Found (85) but expected (67)
                Tests out of sequence.  Found (86) but expected (68)
                Tests out of sequence.  Found (87) but expected (69)
                Tests out of sequence.  Found (88) but expected (70)
                Tests out of sequence.  Found (89) but expected (71)
                Tests out of sequence.  Found (90) but expected (72)
                Tests out of sequence.  Found (91) but expected (73)
                Tests out of sequence.  Found (92) but expected (74)
                Tests out of sequence.  Found (93) but expected (75)
                Bad plan.  You planned 93 tests but ran 75.
t/02-structure.t (Wstat: 0 Tests: 7 Failed: 0)
  Parse errors: Tests out of sequence.  Found (8) but expected (6)
                Tests out of sequence.  Found (9) but expected (7)
                Bad plan.  You planned 10 tests but ran 7.
t/03-unicode.t  (Wstat: 0 Tests: 2 Failed: 0)
  Parse errors: Tests out of sequence.  Found (2) but expected (1)
                Tests out of sequence.  Found (4) but expected (2)
                Bad plan.  You planned 4 tests but ran 2.
Files=4, Tests=103,  1 wallclock secs
Result: FAILED
===> Testing [FAIL]: JSON::Fast:ver('0.7')
Aborting due to test failure: JSON::Fast:ver('0.7') (use --force to override)
  in code  at /usr/local/src/rakudo/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 306
  in method test at /usr/local/src/rakudo/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 285
  in sub MAIN at /usr/local/src/rakudo/install/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 35
  in block <unit> at /usr/local/src/rakudo/install/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1

**Comment by ugexe** [comment]
see #119

**Comment by gfldex** [comment]
fixed with https://github.com/rakudo/rakudo/commit/b120ac401a0795f5f4c5fcd6e775848b4b755508
