### ISSUE TITLE
zef usage too verbose on paths with rakudobrew

### ISSUE THREAD

**Issue by coke** [ugexe/zef#121]
````
$ zef --version
Usage:
  /Users/coke/.rakudobrew/bin/../moar-6d28c1d/install/share/perl6/site/bin/zef [--force] fetch [<identities> ...] -- Download specific distributions
````

**Comment by ugexe** [comment]
This is a Rakudo bug

**Comment by coke** [comment]
Is there an RT for the root cause?

**Comment by ugexe** [comment]
Its a side effect of having a rakudobrew shim + CompUnit::Repository::Installation shim in relation to how rakudo's MAIN_HELPER works (e.g. how to display shadowed commands)

I don't know if there is an RT, or if it technically qualifies as a bug. But you can see [this](https://irclog.perlgeek.de/perl6-dev/2016-12-22#i_13785048) and nine's comments.

**Comment by coke** [comment]
Closing, as this isn't a zef issue.
