### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by bsiegert** [ugexe/zef#130]
zef does not have any releases tagged in the git repo as far as I can see. For distribution packaging, it would be preferable if there were actual releases with a version number and perhaps a Changelog :)

Note that this does not necessarily mean any more guarantees about stability, maturity, etc.

**Comment by ugexe** [comment]
I will release once #122 is resolved 👍

**Comment by ugexe** [comment]
I've gone ahead and made a `v0.1.0` release
