### ISSUE TITLE
Issue installing 

### ISSUE THREAD

**Issue by WildYorkies** [ugexe/zef#131]
I can't figure out what I'm doing wrong in the installation process.

I git clone the repo, cd into the repo, and run the command to install. This is what I get for output:

```
===> Testing: zef:auth('github:ugexe')
t/00-load.t ........... ok 
t/identity.t .......... ok 
t/utils-filesystem.t .. ok 
All tests successful.
Files=3, Tests=14,  26 wallclock secs
Result: PASS
===> Testing [OK] for zef:auth('github:ugexe')
===> Installing: zef:auth('github:ugexe')
===> Install [SKIP] for zef:auth('github:ugexe'): zef:ver<*>:auth<github:ugexe>:api<> already installed
!!!> Install failures: zef:auth('github:ugexe')
```

## Context
I tried to execute the zef file directly from the /bin folder. I made sure file was executable with `chmod +x zef`. 

Then I typed `./zef` and `./zef --help` and `zef` and each time I got this output:

```
./zef: line 1: use: command not found
```

## Expected Behavior
The app is installed and I can run it from any location in the terminal

## Actual Behavior
I can't run the binary file directly or otherwise

## Steps to Reproduce
This may be a silly mistake on my part. But the steps to reproduce are installing on a macbook. 

## Your Environment
* perl6 -v
`This is Rakudo version 2016.11 built on MoarVM version 2016.11
implementing Perl 6.c.`
* perl6 -e 'say $*VM.config<os>'
`darwin`

**Comment by ugexe** [comment]
Zef is already installed, but you don't have your PATH setup to point at the directory it is installed to, hence `zef` resulting in `command not found`. Rerun with the `--force` flag, which will reinstall zef and also show you what you need to add to your path.

For example:
```
nickl@li685-90:~/perl6/zef$ perl6 -Ilib bin/zef -v --force install .
===> Testing: zef:auth('github:ugexe')
t/00-load.t ........... ok
t/identity.t .......... ok
t/utils-filesystem.t .. ok
All tests successful.
Files=3, Tests=14,  3 wallclock secs
Result: PASS
===> Testing [OK] for zef:auth('github:ugexe')
===> Installing: zef:auth('github:ugexe')
===> Install [OK] for zef:auth('github:ugexe')

1 bin/ script [zef] installed to:
/home/nickl/.rakudobrew/moar-blead-nom/install/share/perl6/site/bin
```

Notice the final line - this is what you need to add to your PATH. So in my case I would do:
`export PATH="/home/nickl/.rakudobrew/moar-blead-nom/install/share/perl6/site/bin:$PATH"`

Alternatively you can invoke it with its full path (or alias something to it):
`/home/nickl/.rakudobrew/moar-blead-nom/install/share/perl6/site/bin/zef`

**Comment by WildYorkies** [comment]
That did the trick, thanks 👍
