### ISSUE TITLE
module generator enhancement

### ISSUE THREAD

**Issue by WildYorkies** [ugexe/zef#132]
I'd like to propose a simple module generator. One would use it like this:

`zef new [name-of-module]`

And it would spit out a barebones directory structure like this: https://github.com/ugexe/Perl6-Foo

**Comment by ugexe** [comment]
I'm still on the fence about this. While I've considered it in the past (more than once), it doesn't really belong in zef functionality wise.

I'd consider something where the initial templates for `lib/Foo.pm6 README.md t/ .travis.yaml appveyor.ym META6.json` (and optionally `bin/script`) are stored in a single file `resources/module-templates.tmpl` in the perl5 / mojo style of `Data::Section::Simple` and parse-able (p5 regex: `my @section-data = split /^@@\s+(.+?)\s*\r?\n/m, $content;`). Then the only other code addition would be to `Zef::CLI` by adding a new `multi MAIN("gen-new-dist", *%args) { ... }` that just passes arguments from MAIN into the template parser (which gives back a hash of `"lib/File/Name.pm" => $handle-to-data`.

If someone wants to just write the `resources/module-templates.tmpl` file I would likely implement the rest myself.

**Comment by WildYorkies** [comment]
I was just reading up on the mi6 authoring tool yesterday as well: https://github.com/skaji/mi6/issues/12

It seems that the file/folder generation is the primary use of something like mi6 at this point. Since zef handles the rest of the functionality like testing and such.

**Comment by ugexe** [comment]
There is also https://github.com/kalkin/Ddt (its travis test are passing... not sure why the badge is red)

**Comment by tony-o** [comment]
I second it not belonging in zef except as maybe a plugin

Sent from my iPhone

On Feb 21, 2017, at 7:43 AM, Nick Logan <notifications@github.com<mailto:notifications@github.com>> wrote:


There is also https://github.com/kalkin/Ddt (its travis test are passing... not sure why the badge is red)
