### ISSUE TITLE
CompUnit::Repository install target is not writeable/installable

### ISSUE THREAD

**Issue by Mudada** [ugexe/zef#136]
## Context

Hi, i tried to use zef to install some module on my osx, but everytime i got the error

```
CompUnit::Repository install target is not writeable/installable: /Users/username/auto
Need a valid installation target to continue
  in method install at /Users/username/.rakudobrew/moar-nom/install/share/perl6/site/sources/3192BD24F21B007D17D5398A1BEB41886A372215 (Zef::Client) line 404
  in sub MAIN at /Users/username/.rakudobrew/moar-nom/install/share/perl6/site/sources/16B60ECDC98BB269498FB2064857E4355FBF945D (Zef::CLI) line 123
  in block <unit> at /Users/username/.rakudobrew/moar-nom/install/share/perl6/site/resources/09C71DE0BF8C31A0E3291B1471D521114E17F384 line 1
```

I already try to reinstall my rakudo and zef but with no result. I launched the command in sudo so i dont think its a permission problem.

## Steps to Reproduce
Simply install zef and try to install a package.

## Your Environment

* perl6 -v     => ``This is Rakudo version 2017.02-227-gf190f24 built on MoarVM version 2017.02-31-g91aab71
implementing Perl 6.c.``
* perl6 -e 'say $*VM.config<os>'.     => darwin
* osx version    => Sierra 10.12.3

Sorry for my bad english.

**Comment by ugexe** [comment]
This is a bug somewhere in your env. You have not provided enough information for me to debug this further.

```
$ perl6 -e '.say for map { .Str =>  .can-install() }, map { CompUnit::RepositoryRegistry.repository-for-name($_) }, <site home>'
/home/nickl/.rakudobrew/moar-blead-nom/install/share/perl6/site => True
/home/nickl/.perl6 => True
```
The above is failing for you, and as you can see `zef` is not involved in any way.

Additionally `zef` is tested on OSX https://travis-ci.org/ugexe/zef/jobs/208369170

**Comment by Mudada** [comment]
Sorry if i misunderstand something but in my case your command 

``perl6 -e '.say for map { .Str =>  .can-install() }, map { CompUnit::RepositoryRegistry.repository-for-name($_) }, <site home>' ``

isn't failing and give me the same output,

```
/Users/mudada/.rakudobrew/moar-nom/install/share/perl6/site => True
/Users/mudada/.perl6 => True
```
sorry if im cluncky in my explanation I'm still new in programming

**Comment by ugexe** [comment]
But look at your original post, it shows the following path:
`/Users/username/.rakudobrew/moar-nom/install/share/perl6/site`
yet your second post shows
`/Users/mudada/.rakudobrew/moar-nom/install/share/perl6/site`

These are two different home directories, so your PATH or some other setup is wrong. Maybe you need to `rakudobrew rehash` first? Again, the problem is your env and nothing to do with zef.

**Comment by tony-o** [comment]
A dump of `export` would also help @Mudada

**Comment by Mudada** [comment]
Sorry it's my fault for this I replace ``mudada`` by ``username`` to only keep the usefull informations, but because im a bit low i miss to did it in the second post.

here are the result for the commands you send me (without retarded editing this time)
```
$> which zef
/Users/mudada/.rakudobrew/bin/zef

$> which perl6
/Users/mudada/.rakudobrew/bin/perl6

$> which rakudobrew
/Users/mudada/.rakudobrew/bin/rakudobrew

$> echo $PATH
/Users/mudada/.rakudobrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

$> echo $HOME
/Users/mudada
```

```
$> export
declare -x Apple_PubSub_Socket_Render="/private/tmp/com.apple.launchd.14nwhTJDdB/Render"
declare -x HOME="/Users/mudada"
declare -x LC_CTYPE="UTF-8"
declare -x LOGNAME="mudada"
declare -x OLDPWD
declare -x PATH="/Users/mudada/.rakudobrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
declare -x PWD="/Users/mudada"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.jjzL9mZ4ME/Listeners"
declare -x TERM="xterm-256color"
declare -x TERM_PROGRAM="Apple_Terminal"
declare -x TERM_PROGRAM_VERSION="388"
declare -x TERM_SESSION_ID="F2433D2A-C5A1-41B7-AEAF-B7E7A9870A82"
declare -x TMPDIR="/var/folders/f2/gdkm1ghj60v1s8c9fjhcf0600000gn/T/"
declare -x USER="mudada"
declare -x XPC_FLAGS="0x0"
declare -x XPC_SERVICE_NAME="0"
declare -x __CF_USER_TEXT_ENCODING="0x1F5:0x0:0x0"
```

**Comment by tony-o** [comment]
`/Users/username/auto` is a strange CUR to attempt to write to - was that modified somehow?

**Comment by ugexe** [comment]
@tony-o `/$*HOME/auto` would happen if the code in my first comment fails. https://github.com/ugexe/zef/blob/master/lib/Zef/CLI.pm6#L627

Post the full output (including the command itself) of:
`RAKUDO_MODULE_DEBUG=1 ZEF_PLUGIN_DEBUG=1 zef --debug install P6TCI`

**Comment by Mudada** [comment]
Sure, 

```
?>  RAKUDO_MODULE_DEBUG=1 ZEF_PLUGIN_DEBUG=1 zef --debug install P6TCI
===> Searching for: P6TCI
[Plugin - cached] Checking: Zef::Repository::LocalCache
[Plugin - cached] 	(OK) Plugin loaded successful
[Plugin - cached] (OK) Plugin is now usable: Zef::Repository::LocalCache
[Plugin - p6c] Checking: Zef::Repository::Ecosystems
[Plugin - p6c] 	(OK) Plugin loaded successful
[Plugin - p6c] (OK) Plugin is now usable: Zef::Repository::Ecosystems
[Plugin - git] Checking: Zef::Service::Shell::git
[Plugin - git] 	(OK) Plugin loaded successful
[Plugin - git] 	(OK) Probing successful
[Plugin - git] (OK) Plugin is now usable: Zef::Service::Shell::git
[Plugin - path] Checking: Zef::Service::FetchPath
[Plugin - path] 	(OK) Plugin loaded successful
[Plugin - path] 	(OK) Probing successful
[Plugin - path] (OK) Plugin is now usable: Zef::Service::FetchPath
[Plugin - wget] Checking: Zef::Service::Shell::wget
[Plugin - wget] 	(OK) Plugin loaded successful
[Plugin - wget] 	(SKIP) Probing failed
[Plugin - curl] Checking: Zef::Service::Shell::curl
[Plugin - curl] 	(OK) Plugin loaded successful
[Plugin - curl] 	(OK) Probing successful
[Plugin - curl] (OK) Plugin is now usable: Zef::Service::Shell::curl
[Plugin - cpan] Checking: Zef::Repository::Ecosystems
[Plugin - cpan] 	(SKIP) Not enabled
[Plugin - metacpan] Checking: Zef::Repository::MetaCPAN
[Plugin - metacpan] 	(SKIP) Not enabled
===> Found: P6TCI:ver('0.0.4'):auth('github:ugexe')
===> Fetching: P6TCI
Fetching with plugin: Zef::Service::Shell::git+{<anon|140329626779168>}
===> Fetching [OK]: P6TCI to /Users/mudada/.zef/tmp/P6TCI.git
===> Extracting: P6TCI
[Plugin - git] Checking: Zef::Service::Shell::git
[Plugin - git] 	(OK) Plugin loaded successful
[Plugin - git] 	(OK) Probing successful
[Plugin - git] (OK) Plugin is now usable: Zef::Service::Shell::git
Extracting with plugin: Zef::Service::Shell::git+{<anon|140329626779168>}
===> Extraction [OK]: P6TCI to /Users/mudada/.zef/store/P6TCI.git
===> CompUnit::Repository install target is not writeable/installable: /Users/mudada/auto
```

**Comment by ugexe** [comment]
Everything looks ok. Not sure what causes `.can-install()` to fail on those directories when zef calls it in your specific env.

As a wild guess, when you reinstalled rakudo did you happen to delete it first? e.g. `rakudobrew nuke moar-nom && rakudobrew build moar`?

**Comment by Mudada** [comment]
Oh im so dumb that was it, thanks a lot for your help and sorry for the waste of time.
