### ISSUE TITLE
Installing from path on Windows only works with /, not \

### ISSUE THREAD

**Issue by jnthn** [ugexe/zef#137]
## Context
I was trying to install a module from a local directory with zef on Windows, doing:

    zef install --install-to=site --/test C:\path\to\my\app

## Expected Behavior
It should install it.

## Actual Behavior
It failed with an error message:

    Don't understand identity: C:\path\to\my\app

It also had exit code zero (which, since I called it from a script, made it look appear successful). When I instead did:

    zef install --install-to=site --/test C:/path/to/my/app

It correctly installed the application with its dependencies.

## Steps to Reproduce
Install any local module on Windows using backslashes in the path.

## Your Environment
* perl6 -v

    This is Rakudo version 2017.02 built on MoarVM version 2017.02
    implementing Perl 6.c.

* perl6 -e 'say $*VM.config<os>'

    win32

**Comment by ugexe** [comment]
Thanks for the report!

**Comment by jnthn** [comment]
Thanks for the quick fix; just tried it and can confirm it helps. :-)
