### ISSUE TITLE
executables can't have the arg --name

### ISSUE THREAD

**Issue by gfldex** [ugexe/zef#147]
The wrappers created by zef come with their own argumented named --name. That parameter will not be forwared to the actual executable. There is no documentation for this nor is a wrapper needed if there is only one executable for a given name and/or author.

This will further break anything that depends on scripts but are not aware of special Perl 6 semantics. A cronjob that was running fine yesterday may break when a module installs an executable of the same name but different author.

Please don't ask me for a solution but this aint it.

**Comment by ugexe** [comment]
`zef` doesn't install wrappers, [rakudo](https://github.com/rakudo/rakudo/blob/nom/src/core/CompUnit/Repository/Installation.pm#L53) does. And we're aware that the wrapper sucks, but removing it also requires breaking changes.
