### ISSUE TITLE
Do not use IO::Path.new-from-absolute-path

### ISSUE THREAD

**Issue by zoffixznet** [ugexe/zef#149]
Used in https://github.com/ugexe/zef/blob/f270052b9615d37b5bf5bb3dc6735ce787115104/lib/Zef/Distribution/Local.pm6#L15

The method is being made private. Use `$abspath.IO` instead

**Comment by ugexe** [comment]
FTR: this was used to workaround IO caching in some form or another. However - IO caching has since been removed from rakudo.
