### ISSUE TITLE
nqp listed in build-depends breaks build @hack.p6c.org

### ISSUE THREAD

**Issue by samcv** [ugexe/zef#156]
Term::ANSIColor is failing.
Log is here: http://hack.p6c.org/~samcv/ecosystem-tests/2017-04-28_21.52/Term::ANSIColor.log

I see we have a @!ignore but don't see it being used anywhere?

**Comment by ugexe** [comment]
`nqp` is a pragma and shouldn't be listed as a dependency

**Comment by ugexe** [comment]
See https://github.com/tadzik/Terminal-ANSIColor/commit/2db8169c45022159db851528af8a283c5f31def4

Note `Term::ANSIColor` is the deprecated version of this (`Terminal::ANSIColor`)

**Comment by samcv** [comment]
Yeah I know it shouldn't be listed as a dependency, but regardless, it is in the ecosystem, should we remove it from the ecosystem?

**Comment by samcv** [comment]
Ok well I made a PR that fixes the issue, also adding the 'superseded-by' key.

https://github.com/tadzik/perl6-Term-ANSIColor/pull/10

Does zef support this key yet?

**Comment by ugexe** [comment]
No, *CompUnit::Repository* does not support supercedes, superceded-by, or emulates (and may never support them). It does not make sense for zef to support them until they are implemented in core.

**Comment by samcv** [comment]
Ok thanks. Gonna close this issue for now.
