### ISSUE TITLE
create installation directory

### ISSUE THREAD

**Issue by daxim** [ugexe/zef#162]
› perl6 -Ilib bin/zef install . --install-to=/tmp/stuff
    ===> CompUnit::Repository install target is not writeable/installable: /tmp/stuff

This must be the first installation tool in the world that expects the target directory to already exist. <http://enwp.org/Least_surprise> applies.

If the directory does not exist, silently `mkdir -p` it and continue. If anything goes wrong, only then's the right time to error out.

**Comment by ugexe** [comment]
Except there is no reason the argument --install-to must be a directory - how its stored is up to CompUnit::Repository::*. Things are not as simple as you are making them out to be.

**Comment by zoffixznet** [comment]
Can't reproduce this issue on ` 2017.05-297-g608e886`. The directory gets created just fine.

I see in OP's code the `--install-to` arg is missing the `inst#` part. Perhaps that's the problem.

I'm now getting the [same output as OP](https://irclog.perlgeek.de/perl6/2017-06-08#i_14705341):

```
/tmp › /tmp/perl6/bin/zef 
===SORRY!===
No candidate found for 'zef'.
```

But that looks to be like a problem with bin wrappers than zef as the error doesn't occur if I do have `zef` installed in my normal installation.

**Comment by ugexe** [comment]
Note that:
`/tmp › /tmp/perl6/bin/zef ` 

would really need to be:
`/tmp › PERL6LIB="inst#/tmp/perl6" /tmp/perl6/bin/zef `
