### ISSUE TITLE
Add verbose mode

### ISSUE THREAD

**Issue by szabgab** [ugexe/zef#167]
It would be nice to be able to get more details what zef does. e.g. by adding a --verbose flag I'd like to see what files have been installed (full path) and which files were removed in 'nuke' mode.

Update:
I've just noticed in the skeleton of the issues here at GitHub, that there is a `--debug` flag but I have not seen it in neither `zef help` nor `zef --help` so maybe this issue should be "include --debug in help"

**Comment by ugexe** [comment]
The flag already exists and is already in the usage. I'm not adding all 5 flags to every single MAIN for it to show up under the auto generated --help

**Comment by ugexe** [comment]
https://github.com/ugexe/zef/blob/master/lib/Zef/CLI.pm6#L554

Please be more thorough before sending bug reports in the future and this isn't the only issue recently opened that is not valid
