### ISSUE TITLE
Date of last sync by zef update

### ISSUE THREAD

**Issue by szabgab** [ugexe/zef#170]
When I run `zef update` at the end it tells me
```
---------------------------------------------------
Content Storage                 |Distribution Count
---------------------------------------------------
Zef::Repository::Ecosystems<p6c>|836
Zef::Repository::LocalCache     |34
---------------------------------------------------
```
Would it be possible to also show when was the index on the server updated last time? (Date and how long ago was that would be great.)

That would help me know if I should expect my push to a GitHub to already be included or if I should wait a bit more.

**Comment by ugexe** [comment]
fwiw zef will auto update on most searches. See the configuration file.

**Comment by ugexe** [comment]
And your push to github would not be reflected very accurately in this way, as all this really represents is when the *ecosystem* has last ran its indexing.
