### ISSUE TITLE
zef disregards the Git branch listed in the ecosystem

### ISSUE THREAD

**Issue by szabgab** [ugexe/zef#173]
I am not 100% it is an issue with `zef` but I have not received any response to my query here: http://www.nntp.perl.org/group/perl.perl6.users/2017/06/msg3869.html

## Context

In the Bailador project we use a branch called 'dev' for development
and one called 'main' for releases. Or at least we try to.

In the META.list of the ecosystem
https://github.com/perl6/ecosystem/blob/master/META.list we have
listed the 'main' branch:
https://raw.githubusercontent.com/Bailador/Bailador/main/META6.json

## Expected Behavior
I expect that `zef install Bailador` will install from the 'main' branch of Bailador, as that is listed in the META.list file of the ecosystem.

## Actual Behavior
zef installs the from the 'dev' branch which is marked as the 'default' branch on GitHub.

e.g. here Bailador is listed as a dependency of another project. 
(It could not install Bailador: https://travis-ci.org/szabgab/6blog/builds/240466600 because some new  files were not added to the provides key of the META file. After fixing it on the 'dev' branch
the installation was successful. https://travis-ci.org/szabgab/6blog/builds/240481882 )

## Steps to Reproduce
You can try to install Bailador using `zef install Bailador` and then compare the installed files to the ones on the `main` and `dev` branch of Bailador.

Alternatively you could set up a Perl 6 project with two branches. Have different code on the two versions. Add the project to the ecosystem using the branch which is not the default branch on GitHub. Then install that module using `zef`.

## Your Environment
This happened on Travis-CI (Which is Linux and AFAIK the latest Rakudo source code)

This happened on this environment as well:
```
$ perl6 -v
This is Rakudo version 2017.05-393-g8b86b50 built on MoarVM version 2017.05-71-gad6ab26
implementing Perl 6.c.
```
```
$ perl6 -e'say $*VM.config<os>'
linux
```

```
$ zef info zef
- Info for: zef
- Identity: zef:ver('0.1.16'):auth('github:ugexe')
- Recommended By: /home/jgoff/.rakudobrew/moar-nom/install/share/perl6/site
Description:     It's like [cpanm] wearing high heels with a tracksuit
License:     Artistic-2.0
Source-url:     git://github.com/ugexe/zef.git
Provides: 36 modules
Support:
#   bugtracker:    https://github.com/ugexe/zef/issues
Depends: 0 items
```

**Comment by ugexe** [comment]
It's not zef's place to force git protocol on users. You could write a plugin I guess, but its a bad idea in the first place. Use CPAN if this is an issue for you - thats what its for.

**Comment by szabgab** [comment]
So you say the URL provided the META.list of the ecosystem (and not the META6.json of the distribution) is mostly disregarded.

**Comment by ugexe** [comment]
The META.list is used to create indexes. The indexes themselves are used by package managers, and themselves are just an array of all the meta json of all distributions.

See:
http://ecosystem-api.p6c.org/projects.json
https://github.com/ugexe/Perl6-ecosystems/blob/master/p6c.json

**Comment by szabgab** [comment]
Thanks for clarifying. I did not know CPAN is already usable for Perl 6 distribution and the way I read this https://docs.perl6.org/language/modules.html that it still needs some work. Would people be able to install Bailador from CPAN using zef?

If not, then till that happens I think it would be nice if Perl 6 module developers had a way to have releases which are the things installed by zef by default, while the development goes on.

**Comment by ugexe** [comment]
Yes you can upload your module to CPAN. It will automatically change your `source-url` in the META6.json field to point at some tarball on CPAN servers, and once its picked up by an indexer it will be installable from zef by name `zef install $name` (although you can always immediately do `zef install $url-to-tarball`

See:
https://github.com/ugexe/zef#cpan
http://ugexe.com/perl-toolchain-summit-2017-cpan-and-perl6/

**Comment by szabgab** [comment]
Thanks. We'll take a look and try to use that.

**Comment by szabgab** [comment]
We have not tried that yet, but in the meantime we stumbled upon something that, IMHO either needs some fix or some documentation.

https://github.com/ugexe/Perl6-ecosystems/blob/master/p6c.json is based on the META6.json files listed in the META.list file.  When we run `zef install Module` it uses that same META6.json file, but uses the default branch on GitHub. 
In case an entry in the META.list does not point to the default branch on GitHub, the META data and the code being installed will not belong to the same commit that can lead to all kinds of misunderstandings.

If the above is indeed correct understanding and as you think zef should not need to know about branches in Git, would you mind adding a comment to https://docs.perl6.org/language/modules.html that tells people to link to the default branch.

Also I think it might be a good idea to point to describe how to upload a module or at least to link to your CPAN articles from https://docs.perl6.org/language/modules.html

**Comment by ugexe** [comment]
First: https://github.com/ugexe/Perl6-ecosystems/blob/master/p6c.json is a secondary mirror, it's almost certain this is not the source of the index you have. Nor is it generated in the same fashion as the "perl6 ecosystem".

There is nothing in the docs that mention the link listed in the META.list has any bearing or relation to *anything*, let alone branches, so this should not be so confusing. The `source-url` is the what package managers are interested in, and it's *module authors* responsibility to set this if the ecosystem does not do this automatically (cpan does, the original perl6 ecosystem does not). If a source-url that does git-clone doesn't work for you then don't use it - link the source-url to the .tar.gz of that commit/branch, use cpan, etc

You are welcome to send PRs to address all the items listed at the end - you already know the answers as well as having the resources I've already spent time writing.
