### ISSUE TITLE
Feature request: default to printing USAGE when there's an error in the command line

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#189]
When there's an error in the command line, some subroutine is called and it includes the whole path to `zef`, making out put a bit confusing.

## Context

```
$ zef does-not-exist  
Usage:
  /home/jmerelo/.rakudobrew/bin/../moar-2017.07/install/share/perl6/site/bin/zef [--force|--force-fetch] fetch '[<identities> ...]' -- Download specific distributions
  /home/jmerelo/.rakudobrew/bin/../moar-2017.07/install/share/perl6/site/bin/zef [--force|--force-test] test '[<paths> ...]' -- Run tests
```

## Expected Behavior

Print the default zef -h, or maybe just use the command line instead of the whole command path.

## Actual Behavior

Printing the whole path makes the output a bit confusing in consoles with few columns. Besides, it's inconsistent with zef -h

## Steps to Reproduce

I guess running zef installed from rakudobrew or any other way.

## Your Environment

~~~
This is Rakudo version 2017.07 built on MoarVM version 2017.07
implementing Perl 6.c.
~~~

* perl6 -e "say $*VM.config<os>"
This yields an error
~~~
Cannot look up attributes in a VM type object
  in block <unit> at -e line 1

~~~

~~~
- Info for: zef
- Identity: zef:ver('0.1.26'):auth('github:ugexe')
- Recommended By: /home/jmerelo/.rakudobrew/moar-2017.07/install/share/perl6/site
Description:	 It's like [cpanm] wearing high heels with a tracksuit
License:	 Artistic-2.0
Source-url:	 git://github.com/ugexe/zef.git
Provides: 35 modules
Support:
#   bugtracker:	https://github.com/ugexe/zef/issues
Depends: 0 items
~~~

**Comment by ugexe** [comment]
You are using rakudobrew - this is not a zef bug and also happens for ALL perl6 bin/ scripts installed if using rakudobrew.

Duplicate #108
