### ISSUE TITLE
`zef` doesn't parse command-line options correctly when 'installed'

### ISSUE THREAD

**Issue by jonathonf** [ugexe/zef#191]
## Context

After installing `zef` --to='a location', `zef` fails to run from that location.

## Expected Behavior

`zef` should output usage instructions.

## Actual Behavior

`zef` appears to incorrectly parse the command-line input and ignores any arguments provided.

## Steps to Reproduce

```
$ rm -fr ~/.perl6 ~/.zef
$ cd /tmp
$ git clone --depth=1 https://github.com/ugexe/zef.git
$ cd zef
$ perl6 -Ilib bin/zef
Zef - Perl6 Module Management

USAGE

    zef [flags|options] command [args]


COMMANDS

    install                 Install specific dependencies by name or path
.
. #snip#
.
    --<short-name>  # `--cpan`  Enable plugin with short-name `cpan`
    --/<short-name> # `--/cpan` Disable plugin with short-name `cpan`

$ perl6 -Ilib bin/zef install --to='inst#/tmp/perl6' zef
===> Searching for: zef
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Testing: zef:ver('0.1.26'):auth('github:ugexe')
===> Testing [OK] for zef:ver('0.1.26'):auth('github:ugexe')
===> Installing: zef:ver('0.1.26'):auth('github:ugexe')

1 bin/ script [zef] installed to:
/tmp/perl6/bin

$ export PATH=/tmp/perl6/bin:$PATH
$ zef --debug
===SORRY!===
No candidate found for 'zef' that match your criteria.
Did you perhaps mean one of these?
  Distribution | Author(ity) | Version
               |             |        
               |             |        
               |             |        
               |             |
$ zef --debug update
===SORRY!===
No candidate found for 'zef' that match your criteria.
Did you perhaps mean one of these?
  Distribution | Author(ity) | Version
               |             |        
               |             |        
               |             |        
               |             |
$ perl6 --ll-exception /tmp/perl6/bin/zef
===SORRY!===
No candidate found for 'zef' that match your criteria.
Did you perhaps mean one of these?
  Distribution | Author(ity) | Version
               |             |        
               |             |        
               |             |        
               |             |
```

## Your Environment

Manjaro Linux (Arch Linux-derivative), GCC 7.1.1, ZSH 5.3.1, BASH 4.4.012

* perl6 -v
```
This is Rakudo version 2017.07 built on MoarVM version 2017.07
implementing Perl 6.c.
```
* perl6 -e "say $*VM.config<os>"
```
linux
```
* zef info zef
```
$ perl6 -Ilib bin/zef info zef
- Info for: zef
- Identity: zef:ver('0.1.26'):auth('github:ugexe')
- Recommended By: Zef::Repository::LocalCache
Description:	 It's like [cpanm] wearing high heels with a tracksuit
License:	 Artistic-2.0
Source-url:	 git://github.com/ugexe/zef.git
Provides: 35 modules
Support:
#   bugtracker:	https://github.com/ugexe/zef/issues
Depends: 0 items
```

**Comment by ugexe** [comment]
That's not zef, that's from a perl6 bin wrapper

**Comment by ugexe** [comment]
Why do you expect this to work without setting PERL6LIB as outlined in the readme?

**Comment by jonathonf** [comment]
> That's not zef, that's from a perl6 bin wrapper

Running `zef --debug` is not running `zef`, but is running a perl6 bin wrapper? This setup is weird.

> Why do you expect this to work without setting PERL6LIB as outlined in the readme?

You mean this bit?

> ### Custom installation locations?
> 
> Pass a path to the _--to / --install-to_ option and prefix the path with `inst#` (unless you know what you're doing)
> 
>     $ zef -to="inst#/home/perl6/custom" install Text::Table::Simple
>     ===> Searching for: Text::Table::Simple
>     ===> Testing: Text::Table::Simple:ver('0.0.3'):auth('github:ugexe')
>     ===> Testing [OK] for Text::Table::Simple:ver('0.0.3'):auth('github:ugexe')
>     ===> Installing: Text::Table::Simple:ver('0.0.3'):auth('github:ugexe')
> 
> To make the custom location discoverable:
> 
>     # Set the PERL6LIB env:
>     $ PERL6LIB="inst#/home/perl6/custom" perl6 -e "use Text::Table::Simple; say 'ok'"
>     ok
> 
>     # or simply include it as needed
>     $ perl6 -Iinst#/home/perl6/custom -e "use Text::Table::Simple; say 'ok'"
>     ok

Nothing in there about running `zef` from a custom location, but then I suppose I'm not extrapolating the necessary details about `zef` not actually being a program.

Considering zef is the Perl6.org's go-to 'module manager' there's a pretty significant usability gap. It can't be this difficult to get something working, which means either I'm missing something (or not understanding it, or being plain dumb, etc.) or there actually _is_ something missing.

**Comment by ugexe** [comment]
Just to be clear: You want installed scripts to magically find where their libraries are installed? Or for me to provide you with a cut and paste solution? If it's neither of these then it's explained in the readme and I'd suggest taking a moment to read it.

**Comment by jonathonf** [comment]
I expect a program I install to be able to find itself, yes - or at the very least a README to be unambiguous in its installation instructions.

The fact `zef` is a module rather than a binary shouldn't preclude an "installation" process from setting up the executable to function, and any failure should be with least surprise (e.g. an on-installation message to "remember to set your PERL6LIB to $INSTALL_LOCATION"). But then, if it knows where it's installed, why not set that variable?

I suspect that `zef install zef` is not the "correct" approach for users in this instance - they're not wanting to install a source module, they're wanting to install an executable.

**Comment by tony-o** [comment]
@jonathonf - `zef install zef` installs `zef` to a location known to `perl6`.  Your `-to` directive is to a custom location that you cannot expect `perl6` to arbitrarily know.  The documentation you quoted explicitly states how to use a custom location _and_ how to make that custom location known.  The "usability issue" sounds more like a reading problem.

**Comment by jonathonf** [comment]
Thanks for the passive-aggressive insult; those work wonders. You could have just left out the last sentence but I suppose you have to belittle the other person.

Obviously trying these different approaches to get a system-wide `zef` installation isn't worth it - you have your way of doing things which works, and that's that. I'll wait until the Debian and Fedora packagers have a way forward; at least they get input that doesn't denigrate their efforts.

**Comment by tony-o** [comment]
@jonathonf - there is no passive-aggression there.  As a user of arch-linux I'm sure you've seen the acronym RTFM.  Debian has `perl6` packages.  Perl6 cannot be expected to know the arbitrary location of libs that *you* installed and chose, you need to tell it.  It's that simple.

**Comment by tony-o** [comment]
As discussed in IRC; please set the `PERL6LIB` environment variable appropriately or install to a known location @jonathonf

**Comment by farhad2017** [comment]
hjjghjvh

**Comment by farhad2017** [comment]
c

**Comment by farhad2017** [comment]
ccc
