### ISSUE TITLE
zef fails to upgrade itself on a fresh install on Mac OS X

### ISSUE THREAD

**Issue by briandfoy** [ugexe/zef#199]
zef fails to upgrade itself on a fresh install on Mac OS X

## Expected Behavior

zef should upgrade itself

## Actual Behavior

And I immediately try to upgrade. Notice the shift in version numbers
between "Updating" and "Testing":

	$ zef upgrade Zef
	===> Searching for: Zef
	===> Updating: zef:ver('0.1.26'):auth('github:ugexe')
	===> Testing: zef:ver('0.1.1'):auth('github:ugexe')
	===> Testing [OK] for zef:ver('0.1.1'):auth('github:ugexe')
	===> Installing: zef:ver('0.1.1'):auth('github:ugexe')
	===> Install [FAIL] for zef:ver('0.1.1'):auth('github:ugexe'): ===SORRY!=== Error while compiling /Users/brian/Desktop/perl6-ncurses/site#sources/5234CB6C3C8E9251F4F02BE117FA9C370158E393 (Zef::Service::Shell::unzip)
	Cannot import symbol &zrun from Zef::Shell, because it already exists in this lexical scope
	at /Users/brian/Desktop/perl6-ncurses/site#sources/5234CB6C3C8E9251F4F02BE117FA9C370158E393 (Zef::Service::Shell::unzip):2
	------> use Zef::Shell⏏;

	Use of Nil in string context
	  in sub MAIN at /Applications/Rakudo/share/perl6/site/sources/ED3033E8712BCF9F6DE53678B14A54705DF211A6 (Zef::CLI) line 253
	Unexpected named argument '' passed
	  in sub MAIN at /Applications/Rakudo/share/perl6/site/sources/ED3033E8712BCF9F6DE53678B14A54705DF211A6 (Zef::CLI) line 253
	  in block <unit> at /Applications/Rakudo/share/perl6/site/resources/6182CA1C8C9C6ED5BBB3076B522103070B37DDA4 line 1
	  in sub MAIN at /Applications/Rakudo/share/perl6/site/bin/zef line 2
	  in block <unit> at /Applications/Rakudo/share/perl6/site/bin/zef line 2

## Steps to Reproduce

Install the Mac OS X package for Rakudo 2017.07. Try to upgrade zef.

## Your Environment

* perl6 -v

	 This is Rakudo version 2017.07 built on MoarVM version 2017.07
	 implementing Perl 6.c.

* zef list --installed

	CORE:ver('6.c'):auth('perl')
	DBIish:ver('0.5.10')
	Debugger::UI::CommandLine
	Digest::MD5:ver('0.05'):auth('Cosimo Streppone')
	Encode:ver('0.0.2'):auth('github:sergot')
	File::Directory::Tree:auth('labster')
	File::Find:ver('0.1')
	File::Temp
	File::Which
	Grammar::Debugger:ver('1.0.1'):auth('github:jnthn')
	Grammar::Profiler::Simple:ver('0.02')
	HTTP::Easy:ver('1.1.0')
	HTTP::Status
	IO::String:ver('0.1.1'):auth('Rob Hoelz')
	JSON::Fast:ver('0.9.2')
	JSON::RPC:ver('0.17.3'):auth('bbkr')
	JSON::Tiny
	LibraryMake:ver('1.0.0'):auth('github:retupmoca')
	Linenoise:ver('0.1.1'):auth('Rob Hoelz')
	LWP::Simple:ver('0.091'):auth('Cosimo Streppone')
	MIME::Base64:ver('1.2'):auth('github:retupmoca')
	NativeHelpers::Blob:ver('0.1.10'):auth('github:salortiz')
	OO::Monitors:ver('1.1')
	p6doc:ver('1.001001')
	panda:ver('2016.02')
	Pod::To::BigPage:ver('0.2.1'):auth('Wenzel P. P. Peppmeyer')
	Pod::To::HTML:ver('0.3.7')
	PSGI:ver('1.2.0')
	Shell::Command
	SVG
	SVG::Plot
	TAP::Harness:ver('0.0.2'):auth('Leon Timmermans')
	Template::Mojo:ver('0.1')
	Template::Mustache:auth('github:softmoth')
	Terminal::ANSIColor:ver('0.3')
	Test::Mock:ver('1.4')
	Test::When:ver('1.001008')
	URI:ver('0.1.4')
	XML::Writer
	zef:ver('0.1.1'):auth('github:ugexe')
	zef:ver('0.1.23'):auth('github:ugexe')

**Comment by ugexe** [comment]
You'll probably have to:
zef uninstall zef

And then reinstall zef to get the fix for fixed version comparison of different lengths.

**Comment by ugexe** [comment]
You might also need to delete ~/.zef if the above fails to solve the issue

**Comment by ugexe** [comment]
Also please note that while you say this is a fresh install of Rakudo that there are already modules installed - including two versions of zef (so even if you meant rakudo star, there is still old modules installed). I mention this because there is a bug in 2017.07 that can invoke the wrong version of a bin script if it's installed in a certain location.

**Comment by briandfoy** [comment]
Ah, hadn't considered that. Deleting ~/.zef seems to have fixed the problem,
