### ISSUE TITLE
non-Perl 6 scripts in the bin directory do not install in a runnable form

### ISSUE THREAD

**Issue by molecules** [ugexe/zef#200]
## Context

In the module directory is a `META6.json` file and a subdirectory called `bin`. In the `bin` is a Perl 5 file called `bin/test.pl`.

`zef install .` runs without error in the top directory. But when trying to run `test.pl`, I get an error. Come to find out, a Perl 6 wrapper script had been installed for `test.pl` and that is what is giving me the error. If I run `bin/test.pl` directly, it works fine.

## Expected Behavior
I expected that running `test.pl` from any directory would be the same as running it from the source directory.

## Actual Behavior
When trying to run `test.pl`, I get the following error:

    ===SORRY!===
    Could not find Perl5 at line 2 in:
        /home/username/.perl6
        /path/to/perl6/rakudo-star-2017.07/install/share/perl6/site
        /path/to/perl6/rakudo-star-2017.07/install/share/perl6/vendor
        /path/to/perl6/rakudo-star-2017.07/install/share/perl6
        CompUnit::Repository::AbsolutePath<64730416>
        CompUnit::Repository::NQP<43359856>
        CompUnit::Repository::Perl5<43359896>

## Steps to Reproduce
Create the following files:

**`META6.json`**

    {
    "perl"         : "6.c",
    "name"         : "TESTING1234",
    "license"      : "Artistic-2.0",
    "version"      : "0.0.2",
    "auth"         : "github:author",
    "authors"      : ["First Last"],
    "description"  : "TESTING module creation",
    "provides"     : {
                     },
    "depends"      : [ ],
    "test-depends" : [ "Test", "Test::META"  ]
    }

**`bin/test.pl`**

    #!/bin/env perl
    use v5.10;
    use strict;
    use warnings;
    
    say 'Hello world!';

Install it and run `test.pl`.

```
zef install .
test.pl     # error
bin/test.pl # works fine

```

* zef install --debug .

```
===> Dependencies: Test, Test::META
===> Filtering: TESTING1234:ver('0.0.6'):auth('github:molecules')
===> Filtering [OK] for TESTING1234:ver('0.0.6'):auth('github:molecules')
===> # SKIP: No Build.pm for TESTING1234:ver('0.0.6'):auth('github:molecules')
===> Testing: TESTING1234:ver('0.0.6'):auth('github:molecules')
Testing with plugin: Zef::Service::TAP+{<anon|56456448>}
===> Testing [OK] for TESTING1234:ver('0.0.6'):auth('github:molecules')
===> Installing: TESTING1234:ver('0.0.6'):auth('github:molecules')
===> Install [OK] for TESTING1234:ver('0.0.6'):auth('github:molecules')

1 bin/ script [test.pl] installed to:
/path/to/perl6/rakudo-star-2017.07/install/share/perl6/site/bin
```

The "installed" `test.pl` script is 
`/path/to/perl6/rakudo-star-2017.07/install/share/perl6/site/bin/test.pl`:

    #!/usr/bin/env perl6
    sub MAIN(:$name is copy, :$auth, :$ver, *@, *%) {
        CompUnit::RepositoryRegistry.run-script("test.pl", :dist-name<TESTING1234>, :$name, :$auth, :$ver);
    }

## Your Environment

* perl6 -v
```
This is Rakudo version 2017.07 built on MoarVM version 2017.07
implementing Perl 6.c.
```

* zef list --installed
```
===> Found via /path/to/perl6/rakudo-star-2017.07/install/share/perl6
CORE:ver('6.c'):auth('perl')
===> Found via /path/to/perl6/rakudo-star-2017.07/install/share/perl6/site
HTTP::Easy:ver('1.1.0')
JSON::Class:ver('0.0.9'):auth('github:jonathanstowe')
DNACF::Pipeline:ver('0.0.6'):auth('github:molecules')
Grammar::Debugger:ver('1.0.1'):auth('github:jnthn')
Encode:ver('0.0.2'):auth('github:sergot')
MIME::Base64:ver('1.2'):auth('github:retupmoca')
URI:ver('0.1.4')
Grammar::Profiler::Simple:ver('0.02')
HTTP::Status
JSON::Marshal:ver('0.0.13'):auth('github:jonathanstowe')
panda:ver('2016.02')
XML::Writer
TESTING1234:ver('0.0.6'):auth('github:molecules')
File::Find:ver('0.1')
LibraryMake:ver('1.0.0'):auth('github:retupmoca')
DNACF::Pipeline:ver('0.0.5'):auth('github:molecules')
Pod::To::BigPage:ver('0.2.1'):auth('Wenzel P. P. Peppmeyer')
Linenoise:ver('0.1.1'):auth('Rob Hoelz')
File::Temp
META6:ver('0.0.16'):auth('github:jonathanstowe')
TAP::Harness:ver('0.0.2'):auth('Leon Timmermans')
zef:ver('0.1.23'):auth('github:ugexe')
JSON::Unmarshal:ver('0.08')
p6doc:ver('1.001001')
DNACF::Pipeline:ver('0.0.7'):auth('github:molecules')
Debugger::UI::CommandLine
DBIish:ver('0.5.10')
TESTING1234:ver('0.0.4'):auth('github:molecules')
TESTING1234:ver('0.0.2'):auth('github:molecules')
Terminal::ANSIColor:ver('0.3')
IO::String:ver('0.1.1'):auth('Rob Hoelz')
JSON::Fast:ver('0.9.2')
Template::Mustache:auth('github:softmoth')
TESTING1234:ver('0.0.3'):auth('github:molecules')
JSON::Tiny
Test::When:ver('1.001008')
File::Which
SVG
Shell::Command
JSON::Name:ver('0.0.2'):auth('github:jonathanstowe')
JSON::RPC:ver('0.17.3'):auth('bbkr')
Template::Mojo:ver('0.1')
TESTING1234:ver('0.0.1'):auth('github:molecules')
NativeHelpers::Blob:ver('0.1.10'):auth('github:salortiz')
OO::Monitors:ver('1.1')
Test::META:ver('0.0.10'):auth('github:jonathanstowe')
Pod::To::HTML:ver('0.3.7')
PSGI:ver('1.2.0')
TESTING1234:ver('0.0.5'):auth('github:molecules')
Test::Mock:ver('1.4')
SVG::Plot
File::Directory::Tree:auth('labster')
Digest::MD5:ver('0.05'):auth('Cosimo Streppone')
LWP::Simple:ver('0.091'):auth('Cosimo Streppone')
```

**Comment by ugexe** [comment]
You are correct that this is not ideal, but unfortunately this is a rakudo bug.

Whats happening is rakudo, not zef, installs a wrapper for all bin scripts. Prior to `2017.07` these wrappers would have launched your example correctly. To see what I mean, consider the following two lines which show how these used to be loaded vs how they are loaded now:
Before: https://github.com/rakudo/rakudo/commit/92f8abe00883d7b25b11ca64bec8f02369f89270#diff-9d9f3b6271234e410619d222c23d08f7L87
Current: https://github.com/rakudo/rakudo/commit/92f8abe00883d7b25b11ca64bec8f02369f89270#diff-01e5aae0452c5cc8b73580eb6a4a74acR245

You'll see that scripts are now loaded as if they were perl6 via `require $path-to-script-code`, which was done to speed up loading when the scripts are perl6. Non-perl6 bin scripts, however, got overlooked. They used to work because before the wrapper just did `run $path-to-script-code`

Feel free to open a rakudo bug:
```
Bug reports should be sent to “rakudobug@perl.org” with
the moniker [BUG] (including the brackets) at the start of
the subject so that it gets appropriately tagged in the RT
system
```

As some additional information: the wrappers are necessary because Perl 6 can have multiple versions/auths of the same distribution name. The wrapper is thus responsible for finding the available scripts, and then choosing one to run (the one with the highest version, although technically its not limited to this).

**Comment by molecules** [comment]
Thanks. Just for the record, I tried installing it with `zef` with Rakudo Star `2017.04` and with `panda` with Rakudo-Star `2016.11`, and got the same errors.

**Comment by molecules** [comment]
Closing this since it is a Rakudo bug and not a zef bug.

**Comment by AlexDaniel** [comment]
Ticket: [RT #131911](https://rt.perl.org/Ticket/Display.html?id=131911)
