### ISSUE TITLE
zef install fails when the path to .zef contains a space

### ISSUE THREAD

**Issue by Garland-g** [ugexe/zef#204]
If the path to the .zef directory contains a space, zef fails with  "No such method 'IO' for invocant of type 'Any'. 

## Context
Windows creates a home directory with a space if a username containing a space is entered into their user creation tool. Because of this, it's easy for Windows users to get stuck with having to create a new account to make zef work correctly with the default location for the .zef folder.

## Expected Behavior
zef installs the package correctly.

## Actual Behavior
PS C:\Users\Test User>zef --debug install SDL2::Raw
===> Searching for: SDL2::Raw
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Found: SDL2::Raw:ver('0.1'):auth('Timo Paulssen') [via Zef::Repository::Ecosystems<p6c>]
===> Fetching: SDL2::Raw
Fetching with plugin: Zef::Service::Shell::git+{<anon|124275920>}
===> Fetching [OK]: SDL2::Raw:ver('0.1'):auth('Timo Paulssen') to C:\Users\Test User/.zef/tmp\1504559828.12528.3116\SDL2_Raw-p6.git
===> Extracting: SDL2::Raw
Extracting with plugin: Zef::Service::Shell::git+{<anon|124275920>}
No such method 'IO' for invocant of type 'Any'
  in whatevercode  at C:\rakudo\share\perl6\site\sources\270B9C37420306783B2C9E093EFC383F73849A80 (Zef::Extract) line 19
  in method extract at C:\rakudo\share\perl6\site\sources\270B9C37420306783B2C9E093EFC383F73849A80 (Zef::Extract) line 19
  in code  at C:\rakudo\share\perl6\site\sources\A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 261
  in method extract at C:\rakudo\share\perl6\site\sources\A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 244
  in method fetch at C:\rakudo\share\perl6\site\sources\A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 183
  in sub MAIN at C:\rakudo\share\perl6\site\sources\31FF9E8498781BF95868DF98AD861FCF1211BCC1 (Zef::CLI) line 149
  in block <unit> at C:\rakudo\share\perl6\site\resources\E23789C46D9ED2CBC64CD3742C3FEBCA612A7D5B line 1
  in sub MAIN at C:\rakudo\share\perl6\site\bin\zef line 2
  in block <unit> at C:\rakudo\share\perl6\site\bin\zef line 2

## Steps to Reproduce
Create a new account in Windows with a space in the name (e.g. Test User)
Log in
Add folders for perl6 and zef to the user PATH
zef install <package>

## Your Environment
Using user "Test User" --> zef install fails
Using user "Test"         --> zef install works properly

perl6 -v
This is Rakudo version 2017.07 built on MoarVM version 2017.07
implementing Perl 6.c.

zef list --installed
===> Found via C:\rakudo\share\perl6\site
Template::Mojo:ver('0.1')
Template::Mustache:auth('github:softmoth')
SVG::Plot
Test::When:ver('1.001008')
NativeHelpers::Blob:ver('0.1.10'):auth('github:salortiz')
PSGI:ver('1.2.0')
IO::String:ver('0.1.1'):auth('Rob Hoelz')
HTTP::Easy:ver('1.1.0')
Encode:ver('0.0.2'):auth('github:sergot')
Grammar::Debugger:ver('1.0.1'):auth('github:jnthn')
LWP::Simple:ver('0.091'):auth('Cosimo Streppone')
File::Which
JSON::RPC:ver('0.17.3'):auth('bbkr')
DBIish:ver('0.5.10')
Shell::Command
panda:ver('2016.02')
Grammar::Profiler::Simple:ver('0.02')
Terminal::ANSIColor:ver('0.3')
File::Find:ver('0.1')
Test::Mock:ver('1.4')
OO::Monitors:ver('1.1')
Pod::To::BigPage:ver('0.2.1'):auth('Wenzel P. P. Peppmeyer')
Pod::To::HTML:ver('0.3.7')
Linenoise:ver('0.1.1'):auth('Rob Hoelz')
XML::Writer
Digest::MD5:ver('0.05'):auth('Cosimo Streppone')
LibraryMake:ver('1.0.0'):auth('github:retupmoca')
File::Temp
Debugger::UI::CommandLine
URI:ver('0.1.4')
MIME::Base64:ver('1.2'):auth('github:retupmoca')
JSON::Fast:ver('0.9.2')
zef:ver('0.1.27'):auth('github:ugexe')
JSON::Tiny
SVG
p6doc:ver('1.001001')
File::Directory::Tree:auth('labster')
HTTP::Status
TAP::Harness:ver('0.0.2'):auth('Leon Timmermans')
===> Found via C:\rakudo\share\perl6
CORE:ver('6.c'):auth('perl')

**Comment by ugexe** [comment]
Thanks for the report. It will take me a day or two since I will need to setup an alternative windows user to dig deeper. Are you sure it has to do with the location of the `/.zef` directory though? While it seems like the space is a likely culprit, I'm not sure its tied to zef's work directory.

**Comment by Garland-g** [comment]
I installed rakudo using the 2017.07 rakudo-star release with the standard settings. 

I dug a bit deeper and used the configuration file to figure out a more specific cause of the bug.

What I found was that if I changed the configuration to place the tmp folder inside a path that had no spaces, the installation worked. I tested it with `/zef/tmp` and `/zef test/tmp` and the first one installed correctly, but the second failed in the same way.

The `zef/store` folder didn't seem to care where it was for installation.

I then tried to reproduce it on a different machine to make sure it was consistent, but I wasn't able to.  I'm not sure where else to look. I'd be happy to continue if you have any ideas about it. 

Thanks for looking into this.

**Comment by ugexe** [comment]
I see. So based upon your example output it seems like a problem passing the path to the `git` command. `git` serves both the [fetch](https://github.com/ugexe/zef/blob/01661a5aff76ee4dfa57616e30d77cf297727978/lib/Zef/Service/Shell/git.pm6#L22) phase (`git clone ...`) and the [extract](https://github.com/ugexe/zef/blob/01661a5aff76ee4dfa57616e30d77cf297727978/lib/Zef/Service/Shell/git.pm6#L30) phase (`git checkout ...`). Fetch moves stuff from `$some-remote` to `~/.zef/tmp`, and Extract moves it from `~/.zef/tmp` to `~/.zef/store`. So one of those linked methods is not passing the path to git (via `zrun('git', ..., :cwd($some-path)`) in a way it understands.

You could try to add some debug output inside of those methods to see if this is what is going on. For instance remove `--quiet` and any `:!out` and `:!err` will show git output that may include hints. Also you could print the `.perl` of the various `$foo-proc = zrun('git', ...)` vars to see the full command launched. (e.x. `my $sha-proc = zrun('git', 'rev-parse', $checkout, :cwd($path), :out) andthen *.perl.say;`)

**Comment by Garland-g** [comment]
I ran it with v0.1.27 and with the latest master. I was able to reproduce the issue on v0.1.27, but it installs correctly as of the latest commit, `01661a5`.

I did some more investigation, and what I see is that something is giving back a Nil as the first value at `Zef::Extract line 19`. That Nil hits the whatevercode and causes the error, so grepping for defined values fixes the issue. I'm not sure where that Nil comes from, though.

**Comment by briandfoy** [comment]
I'm playing with this in 2018.01 and running zef from the repo. Here's roughly what happens in git.pm6:

`extract` calls `rev-parse` which calls `checkout-name` which calls `uri` which leads to a grammar. The `$url` in `checkout-name` is a Windows path. Mine is _C:\Users\brian d foy/.zef/tmp\...\zef.git_ with a space in it. 

The `uri` returns `False` and that is used as the checked out name for the remaining git commands.

**Comment by briandfoy** [comment]
Following on from this, any time that you want to send a path to a command you need to quote or escape it. Although I fixed part of the problem last night, now zef has trouble send the windows path to external commands because of the spaces.

**Comment by ugexe** [comment]
See https://rt.perl.org/Public/Bug/Display.html?id=132258 for additional context in process spawning + argument escaping on windows. The part about using cmd is unofficially addressed ( [zef](https://github.com/ugexe/zef/blob/5eeae20d9d2d00f1ea9cc613f4b41711ad055043/lib/Zef.pm6#L5-L6) vs [zef2](https://github.com/ugexe/zef2/blob/cef8296f45fb8dd35c0263f9e4b8193957c4d9db/lib/Zef/Utils/SystemCommands.pm6#L17) ) but still suffers when invoking the perl6 command ( among others like it ). I will probably copy the non-cmd method from the zef2 repo over and see how it tests, but this won't help with the spaces issue.

There is no need to use windows to test the space issue: simply edit `resources/config.json` to have spaces ( such as `"RootDir"  : "$*HOME/.z e f"` ). I think percent encoding in new might be the easiest option... I've been meaning to write an encoder but I suppose I could try testing using an existing module to see what the fall out is.
