### ISSUE TITLE
Test output not shown until all tests finished

### ISSUE THREAD

**Issue by MARTIMM** [ugexe/zef#205]
## Context
Installing my MongoDB project takes too much time(hours). The complaint here is that there is no output at all so I cannot see where the problem is. The test setup is complex so it might be that, but guessing is not a good practice to go on.

Other modules can be installed.

## Expected Behavior
Normal installation after taking not too much time

## Actual Behavior
Seems to hang

## Steps to Reproduce
```
$ cd /some/dir/mongo-perl6-driver
$ zef --debug install .
===> Dependencies: BSON, Semaphore::ReadersWriters, Config::DataLang::Refine, Auth::SCRAM, Base64, OpenSSL, URI::Escape, Unicode::PRECIS, Terminal::ANSIColor, Log::Async, Test::META
===> Filtering: MongoDB:ver('0.39.0.1')
===> Filtering [OK] for MongoDB:ver('0.39.0.1')
===> # SKIP: No Build.pm for MongoDB:ver('0.39.0.1')
===> Testing: MongoDB:ver('0.39.0.1')
Testing with plugin: Zef::Service::Shell::prove+{<anon|94143696>}
.... (a log wait ahead) ...
```

Also tried directly from github master branch, developer branch zip file, etc with the same result.

## Your Environment
* uname -a
```
Linux h03-fedora 4.11.12-100.fc24.x86_64 #1 SMP Fri Jul 21 17:35:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
* perl6 -v
```
This is Rakudo version 2017.08-72-g614bb92 built on MoarVM version 2017.08.1-46-g7965424
implementing Perl 6.c.
```
* zef list --installed
```
===> Found via /home/marcel/Software/perl6/rakudo/install/share/perl6/site
Digest::HMAC:ver('1.0.0'):auth('github:retupmoca')
Base64:ver('0.0.1'):auth('github:ugexe')
File::Which
Digest:ver('0.3.4'):auth('Lucien Grondin')
Digest::MD5:ver('0.05'):auth('Cosimo Streppone')
URI:ver('0.1.4')
Unicode::PRECIS:ver('0.5.1.1'):auth('Marcel Timmerman')
Terminal::ANSIColor:ver('0.3')
LibraryMake:ver('1.0.0'):auth('github:retupmoca')
JSON::Marshal:ver('0.0.13'):auth('github:jonathanstowe')
Log::Async:ver('0.0.4')
OpenSSL:ver('0.1.14'):auth('github:sergot')
PKCS5:ver('0.1.6.2')
JSON::Name:ver('0.0.2'):auth('github:jonathanstowe')
File::Find:ver('0.1')
Semaphore::ReadersWriters:ver('0.2.6'):auth('Marcel Timmerman')
Auth::SCRAM:ver('0.4.6.3')
JSON::Class:ver('0.0.9'):auth('github:jonathanstowe')
UUID:ver('1.0.0'):auth('github:retupmoca')
Crane:auth('Andy Weidenbaum')
Config::DataLang::Refine:ver('0.7.2')
Shell::Command
zef:ver('0.1.27'):auth('github:ugexe')
BSON:ver('0.9.36.2')
Linenoise:ver('0.1.1'):auth('Rob Hoelz')
JSON::Unmarshal:ver('0.08')
Config::TOML:auth('Andy Weidenbaum')
META6:ver('0.0.17'):auth('github:jonathanstowe')
Test::META:ver('0.0.13'):auth('github:jonathanstowe')
JSON::Fast:ver('0.9.2')
===> Found via /home/marcel/Software/perl6/rakudo/install/share/perl6
CORE:ver('6.c'):auth('perl')
```

**Comment by ugexe** [comment]
I think you can get the result you want in the meantime by running `zef --/tap-harness --/prove ...` which will then run your test files one at a time via `perl6 -I... t/some-file.t`.

**Comment by ugexe** [comment]
Might be a rakudo bug with `Proc`, since I would expect the following two one-liners to be nearly equivalent: 

#### No output?
```
mongo-perl6-driver.git$ perl6 -e 'my $proc = run "prove", "-e", "perl6 -I. -Ilib", "t/", :out, :err; $proc.out.Supply.tap: { .say }; $proc.err.Supply.tap: { .say }; say $proc.exitcode'
```

#### Output shown when not captured
```
mongo-perl6-driver.git$ perl6 -e 'my $proc = run "prove", "-e", "perl6 -I. -Ilib", "t/"; say $proc.exitcode'
```

**Comment by MARTIMM** [comment]
The suggestion mentioned above(`zef --/tap-harness --/prove --debug install MongoDB`) is working fine so I can see some output to work with. However, a bug was found when displaying the current working dir with $*CWD. It showed `/home/marcel/.zef/store/develop.zip/mongo-perl6-driver-develop`. This is caused perhaps by an earlier experiment of mine doing `zef install https://github.com/MARTIMM/mongo-perl6-driver/archive/develop.zip`. The bug is then that zef is mistakenly using the wrong parts. Removing `$*HOME/.zef/develop.zip` solved this problem.

**Comment by ugexe** [comment]
To understand why this is not a bug you must understand that a distributions identity, `Foo::Bar:auth<...>:ver<...>:api<...>`, is considered immutable. Then consider that when `zef` fetches something **remotely** it caches it in `~/.zef/store`.

(If you were try and install that same package without `zef` rakudo would complain that it is already installed, despite the fact there is likely a difference in source code and you simply have not updated the `META6.json` version yet).

The correct way is to always bump the version. This is really an authoring issue (regular users are not installing multiple differing devel copies of something that claim to be the same version), but zef provides a few solutions allowing developers to maintaining a sane workflow:

* Install dev stuff from local paths only (local resources don't get cached)
* `zef nuke RootDir` (deletes cache)
* `zef --/cached install ...` (disables local cache)
* Disable it in [resources/config.json](https://github.com/ugexe/zef/blob/master/resources/config.json#L27)

**Comment by MARTIMM** [comment]
Thanks for your answer, however, the version of the develop branch was **0.39.0.1** and the master branch was **0.39.0.2**. Unless it only looks for 3 digit groups.

**Comment by ugexe** [comment]
If you only just recently bumped the version you still have to wait for 1) the ecosystem to update 2) zef to refresh the package lists (or `zef update`) - this could take 1-2 hours. You asked for `MongoDB` (`zef install MongoDB`), i.e. `MongoDB:ver<*>`, and the cached version still fulfills this as its the newest version between itself and the ecosystem (considering the ecosystem has not yet updated). For instance: `zef install "MongoDB:ver<0.39.0.2>"` would not install the cached module of a lower version - instead this would simply tell you it can not find it.

**Comment by MARTIMM** [comment]
Thanks again, all is clear now

**Comment by MARTIMM** [comment]
Simple ```zef install MongoDB``` now works fine. Thanks for your work.

**Comment by melezhik** [comment]
Now I need to run `zef test  --/tap-harness  --/prove .` to get _verbose_ output from prove6, maybe worth to document this? Running with _just_ `--debug` or `--verbose` does not give output _from prove6_

**Comment by ugexe** [comment]
You’re commenting on a 4 year old comment that isn’t valid anymore

**Comment by melezhik** [comment]
Should I rephrase and create an issue that the way to get “prove6” verbose output is not documented in zef ?

**Comment by ugexe** [comment]
```
❯ zef test . --/raku-test --/prove --debug
===> Testing: zef:ver<0.13.7>:auth<github:ugexe>:api<0>
[zef] Testing with plugin: Zef::Service::TAP+{<anon|1>}
[zef] 1..2
[zef] # Subtest: Core
[zef]     ok 1 - Zef module can be use-d ok
[zef]     ok 2 - Zef::Build module can be use-d ok
[zef]     ok 3 - Zef::Config module can be use-d ok
[zef]     ok 4 - Zef::Extract module can be use-d ok
[zef]     ok 5 - Zef::Identity module can be use-d ok
[zef]     ok 6 - Zef::Test module can be use-d ok
[zef]     ok 7 - Zef::Install module can be use-d ok
[zef]     ok 8 - Zef::Fetch module can be use-d ok
[zef]     ok 9 - Zef::Client module can be use-d ok
[zef]     ok 10 - Zef::Repository module can be use-d ok
[zef]     ok 11 - Zef::Repository::LocalCache module can be use-d ok
[zef]     ok 12 - Zef::Repository::Ecosystems module can be use-d ok
[zef]     ok 13 - Zef::Distribution module can be use-d ok
[zef]     ok 14 - Zef::Distribution::DependencySpecification module can be use-d ok
[zef]     ok 15 - Zef::Distribution::Local module can be use-d ok
[zef]     ok 16 - Zef::Utils::FileSystem module can be use-d ok
[zef]     ok 17 - Zef::Utils::SystemQuery module can be use-d ok
[zef]     ok 18 - Zef::Utils::URI module can be use-d ok
[zef]     1..18
[zef] ok 1 - Core
[zef] # Subtest: Plugins
^C
```
```
❯ zef test . --raku-test --/prove --/tap-harness --debug
===> Testing: zef:ver<0.13.7>:auth<github:ugexe>:api<0>
[zef] Testing with plugin: Zef::Service::Shell::Test+{<anon|1>}
[zef] 1..2
[zef] # Subtest: Core
[zef]     ok 1 - Zef module can be use-d ok
[zef]     ok 2 - Zef::Build module can be use-d ok
[zef]     ok 3 - Zef::Config module can be use-d ok
[zef]     ok 4 - Zef::Extract module can be use-d ok
[zef]     ok 5 - Zef::Identity module can be use-d ok
[zef]     ok 6 - Zef::Test module can be use-d ok
[zef]     ok 7 - Zef::Install module can be use-d ok
[zef]     ok 8 - Zef::Fetch module can be use-d ok
[zef]     ok 9 - Zef::Client module can be use-d ok
[zef]     ok 10 - Zef::Repository module can be use-d ok
[zef]     ok 11 - Zef::Repository::LocalCache module can be use-d ok
[zef]     ok 12 - Zef::Repository::Ecosystems module can be use-d ok
[zef]     ok 13 - Zef::Distribution module can be use-d ok
[zef]     ok 14 - Zef::Distribution::DependencySpecification module can be use-d ok
[zef]     ok 15 - Zef::Distribution::Local module can be use-d ok
[zef]     ok 16 - Zef::Utils::FileSystem module can be use-d ok
[zef]     ok 17 - Zef::Utils::SystemQuery module can be use-d ok
[zef]     ok 18 - Zef::Utils::URI module can be use-d ok
[zef]     1..18
[zef] ok 1 - Core
[zef] # Subtest: Plugins
[zef]     ok 1 - Zef::Service::FetchPath module can be use-d ok
^C
```
Frankly I don't know what you're talking about. Again, the comment you are referencing is 4 years old, and my examples above clearly show verbose output regardless of the test backend. Since both `--verbose` and `--debug` are documented generally I don't really see what the problem you're having is.

**Comment by melezhik** [comment]
The problem is one has to run with “--/prove --/tap-harness --debug” options to get verbose output, running  with just “--debug” does not produce verbose output , I am as zef user is interested in having verbose output from prove6. Zef documentation does clear that adding just “debug” flag is not enough 

So my suggestion , is either that “debug” option for zef test action would invoke “—prove —/tarness” _implicitely_ or zef docs says explicitly that uses should also combine  “—prove6 —/tarness” with “verbose” flag to get prove6 verbose output

**Comment by ugexe** [comment]
I keep telling you to stop responding to that 4 year old comment because its not valid anymore, but you keep insisting it is. In my example you can quite clearly see two different test backends run (and if you wanted to test the third one you could) both showing verbose output. My very first example quite clearly shows it is using the tap harness backend and it is quite clearly showing verbose output. Please reread everything I've told you, and if it isn' making sense then read it once more. If its still not making sense then show me proof of what you're saying since I've posted proof that what you're describing isn't how it actually works.

**Comment by ugexe** [comment]
```
❯ zef test . --/raku-test --/prove --debug
===> Testing: zef:ver<0.13.7>:auth<github:ugexe>:api<0>
[zef] Testing with plugin: Zef::Service::TAP+{<anon|1>}
```
I just don't understand your last comment given I had just posted a counter example as shown here

**Comment by ugexe** [comment]
```
❯ zef test . --debug
===> Testing: zef:ver<0.13.7>:auth<github:ugexe>:api<0>
[zef] Testing with plugin: Zef::Service::Shell::prove+{<anon|1>}

[zef] t/00-load.t .......................
[zef] 1..2
[zef] # Subtest: Core
```

**Comment by melezhik** [comment]
@ugexe I feel like our discussion is not productive here. I am going to file a separate issue into zef where I will try to make my point

**Comment by melezhik** [comment]
https://github.com/ugexe/zef/issues/454
