### ISSUE TITLE
ISSUE WITH 'stdout': zef-installer throws an error on installing

### ISSUE THREAD

**Issue by MaximilianJugendForscht** [ugexe/zef#206]
Can't follow the the Installation process described in the Readme.
## Context

After cloning the Repository and cd'ing into the 'zef'-folder, running
```
 perl6 -Ilib bin/zef install .
```
returns an error-Message.

Ubuntu Gnome, 17.4, newest Rakudo-Perl6-version.

## Expected Behavior

Zef should be installed

## Actual Behavior

Error Message: 
```
===> Testing: zef:ver('0.1.27'):auth('github:ugexe')
Method 'stdout' not found for invocant of class 'Seq'
  in method test at /home/maximilian/Schreibtisch/coding/perl/antivirus/installZef/zef/lib/Zef/Test.pm6 (Zef::Test) line 25
  in code  at /home/maximilian/Schreibtisch/coding/perl/antivirus/installZef/zef/lib/Zef/Client.pm6 (Zef::Client) line 362
  in method test at /home/maximilian/Schreibtisch/coding/perl/antivirus/installZef/zef/lib/Zef/Client.pm6 (Zef::Client) line 353
  in code  at /home/maximilian/Schreibtisch/coding/perl/antivirus/installZef/zef/lib/Zef/Client.pm6 (Zef::Client) line 530
  in sub  at /home/maximilian/Schreibtisch/coding/perl/antivirus/installZef/zef/lib/Zef/Client.pm6 (Zef::Client) line 527
  in method install at /home/maximilian/Schreibtisch/coding/perl/antivirus/installZef/zef/lib/Zef/Client.pm6 (Zef::Client) line 633
  in sub MAIN at /home/maximilian/Schreibtisch/coding/perl/antivirus/installZef/zef/lib/Zef/CLI.pm6 (Zef::CLI) line 152
  in block <unit> at bin/zef line 1


```

## Steps to Reproduce

```
git clone https://github.com/ugexe/zef.git
```
```
cd zef
```
```
perl6 -Ilib bin/zef install .
```
## Your Environment

perl-version: This is Rakudo version 2016.06 built on MoarVM version 2016.06
implementing Perl 6.c.

Normal account (no sudo), dual core-computer.

**Comment by MaximilianJugendForscht** [comment]
I just tried this in sudo too, it still doesnt work... Lol

**Comment by ugexe** [comment]
I'm not sure how its possible for the command `perl6 -Ilib bin/zef install .` to produce output saying `===> Searching for: DBLish`. Zef has no dependencies, so it's installation has no need to search for anything. And `DBLish` isn't even a module (its `DBIish`).

**Comment by ugexe** [comment]
Also `2016.06` is fairly old - current version is `2017.08`

**Comment by MaximilianJugendForscht** [comment]
Oh, im very sorry. I posted an issue to the wrong repo :/ had many repos open and posted into the wrong ...

**Comment by ugexe** [comment]
The following steps appear to work for installing zef on an older version rakudo:
```
$ git clone https://github.com/ugexe/zef.git
$ cd zef
$ git checkout v0.1.7
$ perl6 -Ilib bin/zef install .
```
Hopefully Ubuntu can update their rakudo to something `2017.06` or newer soonish.

**Comment by MaximilianJugendForscht** [comment]
Wait... no. Im confused now... Are we in the zef repo? I think we are. 
Additionally, I see, that I pasted a wrong error log, that I produced when bodging around... 

Dude. Im so confused. Hadnt had a coffee :P

**Comment by MaximilianJugendForscht** [comment]
after checking out of the repo, it seems to work. I will keep you updated ;)

**Comment by MaximilianJugendForscht** [comment]
if this :+1: 
```
===> Testing: zef:ver('0.1.7'):auth('github:ugexe')
t/00-load.t ........... ok 
t/identity.t .......... ok 
t/utils-filesystem.t .. ok 
All tests successful.
Files=3, Tests=14,  17 wallclock secs
Result: PASS
===> Testing [OK] for zef:ver('0.1.7'):auth('github:ugexe')
===> Installing: zef:ver('0.1.7'):auth('github:ugexe')

1 bin/ script [zef] installed to:
/usr/share/perl6/site/bin
```
is expectd output, then its working ;) 
Maybe update your readme saying that checkout is needed sometimes so pple arent confused ;)

Anyway, thank for the help and for the great work on zef :P
