### ISSUE TITLE
Hardcoding of the filename 'META6.json' discourages portability

### ISSUE THREAD

**Issue by titsuki** [ugexe/zef#218]
## Context
I had previously used zef as an unzip or untar tool.
However, zef currently cannot handle any files other than perl6 packages, because it hardcodes
the filename 'META6.json'.
I think it's good to use 'META6.json' as the default filename, but it's better that users can specify their target filename.

## Expected Behavior
zef doesn't say any warning messages.

## Actual Behavior
zef says "Use of uninitialized value $meta6-prefix of type Any in string context."

## Steps to Reproduce
1) Use Zef::Extract as an unzip tool:
https://github.com/titsuki/p6-MeCab/blob/0.0.5/Build.pm#L45-L46

2) run:
```
$ zef build .
```

3) You can see the warning message as I mentioned above.

## Your Environment

```
$ perl6 -v
This is Rakudo version 2017.09-254-gde0533c4d built on MoarVM version 2017.09.1-575-gd4e230a69
implementing Perl 6.c.
```

```
$ zef list --installed
===> Found via /home/itoyota/.rakudobrew/moar-nom/install/share/perl6
CORE:ver<6.c>:auth<perl>
===> Found via /home/itoyota/.rakudobrew/moar-nom/install/share/perl6/site
JSON::Pretty:ver<0.1.0>:auth<github:FROGGS>
META6:ver<0.0.18>:auth<github:jonathanstowe>
JSON::Marshal:ver<0.0.13>:auth<github:jonathanstowe>
DOM::Tiny:ver<0.3.5>:auth<github:zostay>
Test::Util::ServerPort:ver<0.0.1>:auth<github:jonathanstowe>
Acme::Advent::Highlighter:ver<1.002001>
File::Find:ver<0.1>
Terminal::ANSIColor:ver<0.4>
zef:ver<0.1.27>:auth<github:ugexe>
Digest:ver<0.3.4>:auth<Lucien Grondin>
UUID:ver<1.0.0>:auth<github:retupmoca>
OpenSSL:ver<0.1.17>:auth<github:sergot>
JSON::Class:ver<0.0.9>:auth<github:jonathanstowe>
JSON::Tiny
Encode:ver<0.0.2>:auth<github:sergot>
Pod::To::Markdown:ver<0.0.1>:auth<Jorn van Engelen>
CheckSocket:ver<0.0.4>:auth<github:jonathanstowe>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
WWW:ver<1.005002>
Digest::HMAC:ver<1.0.0>:auth<github:retupmoca>
Sofa:ver<0.0.1.0>:auth<github:jonathanstowe>
MIME::Types
Chart::Gnuplot:ver<0.0.1>
Net::ZMQ:ver<0.8>
Test::META:ver<0.0.13>:auth<github:jonathanstowe>
zef:ver<0.1.30>:auth<github:ugexe>
URI::Template:ver<0.0.6>:auth<github:jonathanstowe>
NativeHelpers::Array:ver<0.0.2>:auth<github:jonathanstowe>
Chart::Gnuplot:ver<0.0.2>
Jupyter::Kernel:ver<0.0.5>
DateTime::Parse:ver<0.0.1>
URI:ver<0.1.4>
Oyatul:ver<0.0.5>:auth<github:jonathanstowe>
Test::When:ver<1.001008>
HTTP::Status
IO::Socket::SSL:ver<0.0.1>:auth<github:sergot>
Digest::SHA256::Native:ver<0.02>
JSON::Fast:ver<0.9.6>
File::Temp
Text::Markdown:ver<1.0.2>:auth<github:retupmoca>
Shell::Command
Log::Async:ver<0.0.5>
HTTP::UserAgent:ver<1.1.37>:auth<github:sergot>
zef:ver<0.1.24>:auth<github:ugexe>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
File::Directory::Tree:auth<labster>
Algorithm::Manacher
IO::Capture::Simple
Pastebin::Gist:ver<1.004001>
HTTP::Tinyish
JSON::Name:ver<0.0.2>:auth<github:jonathanstowe>
File::Which
App::Mi6:ver<0.0.3>
Inline::Perl5:ver<0.29>:auth<github:niner>
JSON::Unmarshal:ver<0.08>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
CPAN::Uploader::Tiny:ver<0.0.2>
HTML::Escape:ver<0.0.1>
```

**Comment by ugexe** [comment]
Ah yes. This would have been caused by https://github.com/ugexe/zef/pull/209/commits/677d0c4fb9884f26a336ea77b590eebc0dd3fcbb

The META6.json file itself isn't checked to be used, it is only checked to determine where to report the extracted location. The code to check for META6.json should actually be moved into Zef::Client around anywhere it calls .extract, and 

What needs to happen is to expose the various plugins (`::Service::tar`, `::Service::unzip`, etc) .list method through Zef::Extract (as `Zef::Extract.ls-files`) so that inside Zef::Client anywhere .extract is called (1 spot?) so it can mimick the META6.json path prefix finding code being removed from the `::Service::*` plugins.
