### ISSUE TITLE
Can't install Text::Markdown::Discount

### ISSUE THREAD

**Issue by AlexDaniel** [ugexe/zef#223]
Not sure if that's a zef issue or not, but this tracker is probably a good start.
```bash
zef install Text::Markdown::Discount
```
```
===> Searching for: Text::Markdown::Discount
No candidates found matching identity: Text::Markdown::Discount
```

Even though it is listed on https://modules.perl6.org/search/?q=discount

And the repo still exists also: https://github.com/hartenfels/Text-Markdown-Discount

**Comment by ugexe** [comment]
http://modules.perl6.org/update.log
