### ISSUE TITLE
｢depends｣ command seems to be broken

### ISSUE THREAD

**Issue by AlexDaniel** [ugexe/zef#230]
`depends` command does not work.

## Context
I tried `zef depends Pastebin::Gist` and it errored out. @timo [reproduced the issue](https://irclog.perlgeek.de/perl6/2018-02-16#i_15823872).

## Expected Behavior
It should list module dependencies, much like `rdepends` does but in reverse (note that `rdepends` works fine)

## Actual Behavior
```bash
zef depends Pastebin::Gist
```
```
Failed to resolve some missing dependencies
  in block  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/D5DCCAA069375A0DAF6A9A3E96ADDE053D18C65E (Zef::Client) line 157
  in sub MAIN at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/45E857DB9077739278E770E5F8B5CC14168F38BA (Zef::CLI) line 299
  in block <unit> at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/resources/55E6E17CBBB212E3C50BAE19936B78E98334E913 line 3
  in sub MAIN at /home/alex/.rakudobrew/bin/../moar-master/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/alex/.rakudobrew/bin/../moar-master/install/share/perl6/site/bin/zef line 2
```

## Steps to Reproduce
Run ``zef depends Pastebin::Gist``, you can use any other module.

## Your Environment

* perl6 -v
```
This is Rakudo version 2018.01-204-gbeaad7b97 built on MoarVM version 2018.01-94-gc7774e37d
implementing Perl 6.c.
```

**Comment by ugexe** [comment]
This only affects modules that list a core module as a dependency somewhere in its overall chain.
