### ISSUE TITLE
Problems with repo-only dependencies

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#234]
zef bails out if one of the dependencies is an URL

## Context

I'd like to install a particular module from a fork.  Same issue would arise if the module has not been published.

zef is able to install things directly from github, however it breaks with:

```
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 127
Use of uninitialized value @identities of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 140
===> Searching for missing dependencies: , HTTP::UserAgent, Cache::LRU
No such method 'starts-with' for invocant of type 'Any'
  in method candidates at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/site/sources/9323DE80BA98E91D8C4C7DEB220C13E720187340 (Zef::Repository) line 9
  in method find-candidates at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 111
  in block  at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 143
  in sub MAIN at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/site/sources/81436475BD18D66BFD96BBCEE07CCCDC0F368879 (Zef::CLI) line 137
  in block <unit> at /home/jmerelo/.rakudobrew/moar-2018.03/install/share/perl6/site/resources/D822DF07A6D5CB602F97ED307F62A1B3B5D2C90D line 3
  in sub MAIN at /home/jmerelo/.rakudobrew/bin/../moar-2018.03/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/jmerelo/.rakudobrew/bin/../moar-2018.03/install/share/perl6/site/bin/zef line 2
```

## Expected Behavior

Just go ahead and use it. Maybe have some way of specifying the module it maps to. Or be able to specify, as version, the repo. 

## Actual Behavior

Error above.

## Steps to Reproduce

Use an URL as dependency, for instance, this one: https://github.com/JJ/perl6-WebService-GitHub/

## Your Environment

* perl6 -v
* zef list --installed

Perl6 2018.03 and latest zef version

**Comment by ugexe** [comment]
Add .git to the end of your GitHub url and it will work. There has to be some hint in the uri to tell zef it is a tar file, git repo, etc.

However this will never be allowed inside of “depends” field. It is not up to the meta data or module authors WHERE something comes from. If you -really- want to do this you can create your own json ecosystem file and add it to your local zef config, or abuse a Build.pm to directly run a new instance of zef to install from the uri.

**Comment by ugexe** [comment]
Also if you have a module ‘Foo’ that depends on unreleased module ‘Bar’ in its depends you would typically do:

zef install Foo https://github.com/ugexe/bar.git

which will allow the name ‘Bar’ to be picked up and discovered via that url.

**Comment by JJ** [comment]
OK, thanks for taking the time to address this.
