### ISSUE TITLE
zef locate cannot find files in resources/

### ISSUE THREAD

**Issue by Kaiepi** [ugexe/zef#244]
## Context

In a repo of mine, I ran `zef locate resources/config.json`, and it returned the path to Zef's `resources/config.json` instead. `zef locate $PWD/resources/config.json` returns nothing. The file's actually in the cached resources dir, though.

## Expected Behavior

It should return the path given relative to the current directory.

## Actual Behavior

Zef either returns the path to its own `resources/config.json` file or fails to find it.

## Steps to Reproduce

```
$ git clone git@github.com:hoelzro/p6-linenoise.git
$ cd p6-linenoise
$ zef install .
$ zef locate resources/libraries/liblinenoise.so
```

## Your Environment

* perl6 -v
This is Rakudo version 2018.02.1-470-g29b092c94 built on MoarVM version 2018.04-19-g1b78b04c0
implementing Perl 6.c.

(Rakudo version is weird because my system doesn't recognize new tags for some reason)
* zef list --installed
DateTime::Parse:ver<0.0.1>
Encode:ver<0.0.2>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Temp:ver<0.0.6>
File::Which:ver<1.0.1>
HTML::Entity:auth<Alexander Moquin>
HTTP::Client:ver<0.0.2>
HTTP::Status
HTTP::UserAgent:ver<1.1.39>:auth<github:sergot>
IO::Capture::Simple
IO::Socket::Async::SSL:ver<0.6.1>
IO::Socket::SSL:ver<0.0.1>:auth<github:sergot>
IRC::Client:ver<3.007006>
JSON::Class:ver<0.0.10>:auth<github:jonathanstowe>
JSON::Fast:ver<0.9.11>
JSON::Marshal:ver<0.0.14>:auth<github:jonathanstowe>
JSON::Name:ver<0.0.2>:auth<github:jonathanstowe>
JSON::Unmarshal:ver<0.08>
LibraryCheck:ver<0.0.6>:auth<github:jonathanstowe>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
META6:ver<0.0.19>:auth<github:jonathanstowe>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
Net::LibIDN2:ver<0.0.1>
OpenSSL:ver<0.1.18>:auth<github:sergot>
Pastebin::Shadowcat:ver<2.001003>
Pod::To::HTML:ver<0.3.15>
Pod::To::Markdown:ver<.0.1.3>
RakudoBot:ver<0.0.1>
Readline:ver<0.0.2>:auth<github:drforr>
Shell::Command
Test::META:ver<0.0.13>:auth<github:jonathanstowe>
Test::Notice:ver<1.001003>
Test::Util::ServerPort:ver<0.0.1>:auth<github:jonathanstowe>
Test::When:ver<1.001008>
URI::Encode:ver<0.05>
URI:ver<.0.1.4>
WWW:ver<1.005003>
zef:ver<0.2.3>:auth<github:ugexe>

**Comment by ugexe** [comment]
It works if you use the known name:
```
$ zef locate "resources/libraries/linenoise"
===> From Distribution: Linenoise:ver<0.1.1>:auth<Rob Hoelz>:api<>
resources/libraries/linenoise => /home/nickl/.rakudobrew/moar-blead-master/install/share/perl6/site/resources/323767E89F2D0CBE48797015570799E56F6F4FE5.so
```

---

`zef locate resources/config.json` looks for installed items. It does not locate non-installed items. I cannot tell if this is the problem with your first comment though.

**Comment by Kaiepi** [comment]
The package is installed and `config.json` is included in META6.json's resources. It's [RakudoBot](https://github.com/Kaiepi/p6-RakudoBot).

**Comment by ugexe** [comment]
I see. for me it actually did show your resources but *not* zefs ( even though zef was installed ).

```
$ zef locate resources/config.json
===> From Distribution: RakudoBot:ver<0.0.1>:auth<>:api<>
resources/config.json => /home/nickl/.rakudobrew/moar-blead-master/install/share/perl6/site/resources/04945E22B2BF01123C57F25350D82DEF62CE8E49.json
```

I suspect https://github.com/ugexe/zef/blob/66799c04ece37d83b171778b70ad0e967c2ef381/lib/Zef/CLI.pm6#L349 needs to be removed, but cannot test right now.

**Comment by Kaiepi** [comment]
That works:

```
morfent% zef locate resources/config.json          
===> From Distribution: zef:ver<0.2.8>:auth<github:ugexe>:api<>
resources/config.json => /home/morfent/.perl6/share/perl6/site/resources/B0428055D618D09937ADE2AB1E801FB341CB4482.json

===> From Distribution: RakudoBot:ver<0.0.1>:auth<>:api<>
resources/config.json => /home/morfent/.perl6/share/perl6/site/resources/04945E22B2BF01123C57F25350D82DEF62CE8E49.json
```

Should I make a pulreq?

**Comment by ugexe** [comment]
Sure
