### ISSUE TITLE
zef TAP parsing is not able to handle todos

### ISSUE THREAD

**Issue by ufobat** [ugexe/zef#250]
Hi all,

i've noticed that installing Bailador failes on a jmerelo/alpine-perl6 docker image. 
 * zef install Bailador # fails
* zef install -serial Bailador # fails, but dependencies got installed. one is TAP::Harness
* zef install Bailador # works

Bailador uses the "todo" feature of Test in one of its testcases. So my assumption is that zef's TAP parsing without TAP::Harness failes to understand todos.

**Comment by ugexe** [comment]
That also appears to be a version of zef from September 2017 ( can’t tell though since the requested ‘zef list —installed’ was not shown )

**Comment by ugexe** [comment]
Everything works ok when I tested using every variation of testing invocation with and without zef/TAP::Harness/prove/prove6/etc. I do not use jmerelo/alpine-perl6 so maybe continue looking for clues there, but the presence of that version of zef makes me believe the stack must be similarly outdated.

**Comment by ufobat** [comment]
/srv # zef list --installed
===> Found via /root/.rakudobrew/moar-master/install/share/perl6/site
File::Find:ver<0.1>
File::Which:ver<1.0.1>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
Shell::Command
zef:ver<0.3.1>:auth<github:ugexe>
===> Found via /root/.rakudobrew/moar-master/install/share/perl6
CORE:ver<6.c>:auth<perl>

**Comment by ufobat** [comment]
this is my starting point.
is there a more simple way to reproduce this? Installing Bailador is quite a large thing.

**Comment by ufobat** [comment]
you're right, i did update the docker image, but the issue with Bailador is still the same.

what I did was copy the TAP output of the 30-example-app.t file and wrote a dummy module that replays this output. Dummy module installs just fine.
Ill try the commands you have suggested later.

thanks!
