### ISSUE TITLE
zef requires build step to return true to not fail build step? [p6doc]

### ISSUE THREAD

**Issue by aeruder** [ugexe/zef#256]
## Context
This is really more of a question.  I am trying to `zef install p6doc`and finding that it fails.  I've tracked it down to needing this diff in p6doc to get it to succeed:

     class Build {
         method build($workdir) {
             my $doc-dir   = $workdir.IO.child('doc');
             my $dest-pref = $*REPO.repo-chain.grep(/site/).first.prefix.child("doc");
             mkdir($dest-pref) unless $dest-pref.d;
    
             my @files = find(dir => "$workdir/doc", type => 'file').list;
    
             for @files -> $file {
                 next if $file.basename eq 'HomePage.pod6';
    
                 my $rel-dest = $file.relative($doc-dir);
                 my $abs-dest = IO::Path.new($rel-dest, :CWD($dest-pref)).absolute;
    
                 mkdir($abs-dest.IO.parent) unless $abs-dest.IO.parent.d;
    
                 say "Copying {$rel-dest} to {$abs-dest}";
    
                 copy($file, $abs-dest);
             }
    +        True;
         }
         method isa($what) { # Only needed for older panda compatibility
             return True if $what.^name eq 'Panda::Builder';
             callsame;
         }
     }

Is this intentional?  I'm having a hard time really finding Build.pm's requirement to return truth documented anywhere so I suspect this may in fact be a bug in zef.

## Expected Behavior
`zef install p6doc` succeeds

## Actual Behavior
`zef install p6doc` fails the build step.

## Steps to Reproduce
Install zef from this repository, try to install p6doc.

## Your Environment

This is Rakudo version 2018.05-88-g64394152c built on MoarVM version 2018.05-124-g4eda279b5
implementing Perl 6.c.

Running zef 0.4.4

**Comment by ugexe** [comment]
Yes, it is intentional. Otherwise there would be no way to tell if the code failed when spawned in a stand-alone way ( i.e. new process ):
https://github.com/ugexe/zef/blob/df00e35bc486f31b03c2d2244c635a0ad77f5137/lib/Zef/Service/Shell/LegacyBuild.pm6#L19

**Comment by aeruder** [comment]
Thanks! I'll submit a fix to p6doc!
