### ISSUE TITLE
Is there a pre-processing hook for installation?

### ISSUE THREAD

**Issue by lembark** [ugexe/zef#257]
Need to relase some t/*.t files as symlinks, which mi6 is bundling as files instead.
One fix would be using Perl's symlink to generate the links on install.

If this were using EMM I'd add the symlink statements to the Makefile.PL. Is there something similar in zef? If so, where is it documented?

## Context

zef install FindBin;

**Comment by ugexe** [comment]
Can I ask if you already read the documentation to see if something like this exists? Or are you asking me to do this for you?
