### ISSUE TITLE
Missing or wrong version of dependency

### ISSUE THREAD

**Issue by pjscott** [ugexe/zef#267]
I am on

    CentOS Linux release 7.5.1804 (Core)

and I did

    yum install rakudo         [rakudo-0.2018.04-1.el7]
    yum install rakudo-zef  [rakudo-zef-0.2.9-1.el7.x86_64]

Both came from epel.  But running zef results in:

# zef 
===SORRY!===
Missing or wrong version of dependency 'perl#sources/C57EBB9F7A3922A4DA48EE8FCF34A4DC55942942 (CompUnit::Repository::Staging)' (from 'vendor#sources/CFF02A04DA02DEF471ED43CA09ABB9EC81C52C47 (Zef::Utils::SystemQuery)')

**Comment by ugexe** [comment]
This is an issue for whoever packaged zef for centos ( which is not me ).

**Comment by ugexe** [comment]
ping @gerd

**Comment by pjscott** [comment]
I discovered that it is fixed in a rakudo-zef-0.2.9-3 package. While 
documentation suggests that it should be downloadable for Centos 7 from 
epel-testing, this was not the case.  I eventually downloaded it from 
https://kojipkgs.fedoraproject.org//packages/rakudo-zef/0.2.9/3.fc28/x86_64/rakudo-zef-0.2.9-3.fc28.x86_64.rpm 
and it is working.
