### ISSUE TITLE
Using JSON::Fast for a potential speedup in `Searching for: …` phase

### ISSUE THREAD

**Issue by AlexDaniel** [ugexe/zef#272]
The IRC discussion started around [here](http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-15#l540) (it continues on the next day).

TL;DR:
> \<timotimo\> i see 4 seconds of json parsing
> \<timotimo\> if i see it correctly, parsing 150 json documents

> \<nine\> Well I was pretty sure that almost all of that waiting time is JSON parsing

> \<AlexDaniel\> I see 0.825388s + 0.63321996s for parsing both ecosystem files with JSON::Fast
> \<AlexDaniel\> 5.636712s + 5.20290931s using Rakudo::Internals

So json parsing can be made >6x as fast by just using `JSON::Fast` if it is installed (and falling back to Rakudo::Internals otherwise).

I'm slightly worried about differences in produced outputs or in the way they handle weird stuff like unicode combiners, but otherwise seems to be a good idea to make things faster?

**Comment by AlexDaniel** [comment]
By the way, it was also discussed if JSON::Fast can be used by rakudo itself when available.

**Comment by ugexe** [comment]
Also see https://github.com/ugexe/zef/pull/262

**Comment by tony-o** [comment]
@AlexDaniel what was the result of the discussion about `JSON::Fast` being used by rakudo internals if available?  I'd be willing to make that change ..

**Comment by AlexDaniel** [comment]
@tony-o see http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-18#l3

To me it makes sense to replace what we have in rakudo internals with the code from JSON::Fast. In the long run people seem to want no JSON module in rakudo at all, but I have no idea how to achieve that with the current state of things.

**Comment by ugexe** [comment]
A json parser in rakudo cannot be avoided -- https://github.com/rakudo/rakudo/blob/d275ea09bb156d5a37076e272728628030dfacff/src/core/CompUnit/Repository/FileSystem.pm6#L24-L35

**Comment by tony-o** [comment]
Agreed @ugexe.  You can't have the binaries relying on an external module out of the gate.  I agree with `[Coke]`, ideally we wouldn't have it.  I don't like the idea of snapshotting a module (I wrote an earlier iteration of that module that timo merged in at some point but it looks like he's made it better since then).  I'd be willing to implement a faster internal JSON parser in rakudo if we're really that worried about speed.

**Comment by tony-o** [comment]
@AlexDaniel ^^

**Comment by AlexDaniel** [comment]
@tony-o yes, we're worried about the speed. But what do you mean when you say you can implement a faster internal JSON parser? Because you said that you don't like the idea of snapshotting JSON::Fast, so I'm wondering what are your plans exactly.

**Comment by tony-o** [comment]
@AlexDaniel the plan would be to write a faster JSON parser for rakudo internal that you don't need to CLA.

**Comment by zoffixznet** [comment]
> to write a faster JSON parser for rakudo internal that you don't need to CLA.

FWIW, JSON::Fast is written by timotimo, who already signs the CLA

**Comment by tony-o** [comment]
@zoffixznet ++

**Comment by tony-o** [comment]
I'm going to close this issue unless there's any objection.  `zef` needs to use the same JSON parser as rakudo internals for the CUR reasons and this discussion probably belongs to rakudo. @AlexDaniel

**Comment by AlexDaniel** [comment]
@tony-o There was some discussion on #perl6-dev: http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-19#l281

My understanding is that we can simply replace the code of the internal json parser with code from JSON::Fast and that will give immediate speed improvement without creating any new problem (just talk to @timo to make sure they are OK with that). Other questions (like if Zef should rely on rakudo internals) can be discussed later, and maybe eventually we will figure out a better solution.

**Comment by tony-o** [comment]
@AlexDaniel ++, my only question was about whether timo wanted to CLA the JSON stuff, @zoffixznet cleared that up.  What [Coke] said is what my concern was, re: relying on a module being CLA'd or not.  timo has my vote for pushing what he has to rakudo core -

**Comment by ugexe** [comment]
zef would not have to rely on rakudo internals if the json parsing/emitting was encapsulated in e.g. `CompUnit::Repository::Distribution` via e.g. `serialize`/`deserialize` methods.

**Comment by lizmat** [comment]
`CompUnit::Repository::Distribution` ?  Where do I find this?
