### ISSUE TITLE
performance: can plugins be skipped for certain commands?

### ISSUE THREAD

**Issue by timo** [ugexe/zef#275]
I've been briefly looking into why "zef list --installed" takes ~2.7s on my machine, and it looks like the whole first second is taken up by going through all plugins. I stumbled upon it, because `Zef::Service::Tap` appeared somewhere in the call graph and felt out of place to me.

## Expected Behavior

Plugins related to finding installed packages (or without --installed, all packages) are probed and loaded.

## Actual Behavior

Every plugin available to zef will be probed and loaded for any command.

## Steps to Reproduce
Run `zef list --installed` with ZEF_PLUGIN_DEBUG enabled and see how long the individual parts of the program take, for example by hitting ctrl-c as soon as the plugin loading part is finished. Annoyingly, moreutil's "ts" command doesn't get the output right, maybe due to buffering?

## Your Environment
    This is Rakudo version 2018.10-187-g762c708fd built on MoarVM version 2018.10-99-g88a776d1a
    implementing Perl 6.d.

**Comment by ugexe** [comment]
Generally: It essentially boils down to https://github.com/rakudo/rakudo/issues/1920 The plugin code used to be entirely lazy / delayed, but the introduction of .hyper/.race to speed up other things lead to the discovery of the issue mentioned above.

Now lets consider if issue 1920 gets resolved. In zef the design must be able to late-load plugin modules while coping with the fact that plugins may be getting installed during zef runtime. Something like `zef install foo --serial`,  `TAP::Harness` getting pulled in as a dependency somewhere, `TAP::Harness` gets tested with `Zef::Service::Shell::prove`, and `foo` may then get tested with `Zef::Service::Tap`. This shouldn't be hard to avoid, but it should be considered in the design.

---

Specially to `zef list --installed`

First it does `create-client`:
https://github.com/ugexe/zef/blob/d3b073283e114ab1295171f6a5f758b583a1740a/lib/Zef/CLI.pm6#L229
which does `Zef::Client.new(...)` with some common options:
https://github.com/ugexe/zef/blob/d3b073283e114ab1295171f6a5f758b583a1740a/lib/Zef/CLI.pm6#L837-L838
but ultimately `Zef::Client`s `TWEAK` loads the modules:
https://github.com/ugexe/zef/blob/d3b073283e114ab1295171f6a5f758b583a1740a/lib/Zef/Client.pm6#L49-L52

So a solution might add a `Zef::Client.new(tester => Zef::Test.new(:backends())` inside the `MAIN('list'` of `Zef::CLI`.

But then what about when the user does `zef install foo --/test`? I would expect that too to be lazy. And there are many variants on that such that it would require lots of one-off logic for various functionality. This is why I'm not particularly interested in this non-generic option.

---

The "workaround" would be `zef list --installed --/tap-harness`... you can enable/disable any plugins by their short-name https://github.com/ugexe/zef/blob/d3b073283e114ab1295171f6a5f758b583a1740a/resources/config.json#L134
