### ISSUE TITLE
Document the hash form of the build META6.json attribute

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#281]
That form is only used in [this module](https://github.com/niner/Inline-Python/blob/master/META6.json), does not seem to be documented anywhere. Be it an experimental form or a spec way of using zef, it should be documented so that anyone in the community can use it for her own modules.

## Context

This behavior of the `depends` attribute, which is apparently defined here: 

https://github.com/ugexe/zef/blob/7c9d05bd1a04baed844d7676605fc2a2452e5a3a/lib/Zef/Distribution.pm6#L68-L76

shows that there are two possible keys, `build` and `runtime`, and that each of them needs a `requires` field which seems to have the form of a list of dependencies. However, the rest of the fields which are used in the module above, `from`,  `bin`, are not documented anywhere. 

## Expected Behavior

zef is the default, and for the time being only, module manager in Perl 6. Its behavior should be documented so that it can be used by anyone, and easily replicated by other module installers that might arise in the future.

## Actual Behavior

I haven't found any documentation, not even as inline documentation. The [zef wiki](https://github.com/ugexe/zef/wiki) is empty. The [test which uses the feature](https://github.com/ugexe/zef/blob/master/t/distribution-depends-parsing.t) is neither linked nor documented, and as a matter of fact does not use (and thus test) the `bin` value for `from` which is used in the other example of this feature. 

## Your Environment

This is the source of zef at commit 9cb53c84ba9808fa2b96bcb80b2b16cd0e56aea1

**Comment by ugexe** [comment]
I don't know that the hash form will stay or not, nor is it fully implemented -- hence it not being documented and it only being in use by a single module author who is also subject matter expert, for the explicit purpose of testing this way of doing depends.

I do not document features that I may remove and do not plan on having a deprecation policy for.

**Comment by JJ** [comment]
As far as I understand it, there's a [next generation zef](https://github.com/ugexe/zef2) which is *not* officially bundled with Rakudo Star. Experimental|non documented features would be best kept in experimental|non officially released branches or repos, because as long as they're released and used "in the wild", they are bound to be seen (and people will feel confused about them and/or will want to use them for their own purposes). Also, these features are going, and will be, used in unforeseen (by the user or the feature or the creator of the feature) ways (as I have commented elsewhere #222, META6.json could be used simply as a vehicle for expressing dependencies for an app with nothing to install). In this case, [Module Citation](https://github.com/finanalyst/ModuleCitation) as well as [p6-river](https://github.com/JJ/p6-river) read all META6.json in the ecosystem and will of course fail when they find this undocumented feature. "Toaster" modules such as [Blin](https://github.com/perl6/Blin) will suffer the same fate.
My point is that documenting it or not does not depend on it being experimental or not, but on the fact that as long as it's there, even in a single module, it's bound to be consumed by other modules, that will fail if it's not.
