### ISSUE TITLE
Prevent improper version identities?

### ISSUE THREAD

**Issue by CurtTilmes** [ugexe/zef#288]
I'm really complaining about an issue that I believe (is that correct?) is a URI Bug (see https://github.com/perl6-community-modules/uri/issues/40).

In `META6.json`, it specifies:
```
"version"     : "v0.1.4"
```

which seems to gum things up with `zef`.

Perhaps `zef` could either just 'do the right thing' (treat "v0.1.4" the same as "0.1.4"), or fail completely with good error messages?
```
zef info URI
- Info for: URI
- Identity: URI:ver<.0.1.4>
...
```

```
zef install 'URI:ver<.0.1.4>'
===> Searching for: URI:ver<.0.1.4>
No candidates found matching identity: URI:ver<.0.1.4>
```

**Comment by CurtTilmes** [comment]
The more I look at this, I think it is a real `zef` bug as well (triggered by the malformed version in `URI`).

If my module depends on `URI`, and I run `zef depends .` it says `URI:ver<.0.1.4>`, but that isn't a valid identity I can hand back into e.g. `zef info`.

**Comment by ugexe** [comment]
I'm just going to remove the code that strips a leading `v` from versions. This means the current version will show up as `URI:ver<v.0.1.4>` -- so the version of URI should still be fixed but the version shown as-is will be query-able and still work when doing `use URI:ver<v.0.1.4>`
