### ISSUE TITLE
zef does not upgrade NativeHelpers-Blob

### ISSUE THREAD

**Issue by patzim** [ugexe/zef#290]
## Context
I tried to install NativeHelpers-Blob yesterday morning, which failed. Afterwards [this commit](https://github.com/salortiz/NativeHelpers-Blob/commit/78190e692d5ee912139c3f406866e89e9cad1619) happened, which fixes the bug that makes it fail to install on my end. When I now try to install NativeHelpers-Blob again it still tries to install the commit that failed yesterday.

`zef update && zef install --force-install NH::B`
`zef uninstall NH::B && zef update && zef install NH::B` 
`zef update && zef  upgrade NH::B`

All the above commands try to install the commit that failed for me yesterday.

I suspect zef falls back to what is in its cache as long as the version number in the repo does not increase. But that approach would be flawed with p6c, since you end up and are stuck with the same version but different code depending on when you install a distribution the first time.

## Expected Behavior
zef installs the latest commit.

## Actual Behavior
zef installs the stuff it fetched yesterday.

## Steps to Reproduce
```
zef install NativeHelpers::Blob
# commit something in NativeHelpers::Blob
zef uninstall NativeHelpers::Blob
zef update
zef install NativeHelpers::Blob
```

## Your Environment

* perl6 -v
```
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.
```
* zef list --installed
```
===> Found via /opt/rakudo-pkg/share/perl6
CORE:ver<6.d>:auth<perl>
zef:ver<0.6.0>:auth<github:ugexe>:api<0>
===> Found via /home/patrickb/.perl6
Base64:ver<0.0.1>:auth<github:ugexe>
Cro::Core:ver<0.8.0>
Cro::HTTP:ver<0.8.0>
Cro::OpenAPI::RoutesFromDefinition:ver<1.0.1>
Cro::TLS:ver<0.8.0>
Cro::WebSocket:ver<0.8.0.1>
Crypt::Random:ver<0.4.1>:auth<github:skinkade>
DateTime::Parse:ver<0.9.1>
Digest::HMAC:ver<1.0.0>:auth<github:retupmoca>
Digest::SHA1::Native:ver<0.04>
Digest:ver<0.3.4>:auth<Lucien Grondin>
Docker::File:ver<1.0>:auth<github:jnthn>
File::Find:ver<0.1>
File::Ignore
File::Which:ver<1.0.1>
HTTP::HPACK:ver<0.9.2>
IO::Path::ChildSecure:ver<1.001011>
IO::Socket::Async::SSL:ver<0.7.3>
JSON::Class:ver<0.0.11>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.9.12>
JSON::JWT:ver<1.0>:auth<github:retupmoca>
JSON::Marshal:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
JSON::Pointer:ver<1.0>
JSON::Unmarshal:ver<0.08>
LibraryCheck:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
META6:ver<0.0.22>:auth<github:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
OO::Monitors:ver<1.1>
OpenAPI::Model:ver<1.0.3>
OpenAPI::Schema::Validate:ver<1.0>
OpenSSL:ver<0.1.21>:auth<github:sergot>
Readline:ver<0.1.4>:auth<github:drforr>
Shell::Command
Terminal::ANSIColor:ver<0.5>
YAMLish:ver<0.0.5>:auth<Leon Timmermans>
cro:ver<0.8.0>
if:ver<0.1.1>:auth<github:FROGGS>
```

**Comment by ugexe** [comment]
You can modify your zef config to prefer p6c by putting it before the cpan item. Or you can e.g. disable cpan via —/cpan or the cache with —/cached But this is otherwise desired behavior as there is no way to decide what is the real version XXX

Module authors must understand what they are doing by releasing to a given (or multiple) ecosystems and accommodate them. This includes bumping versions when changes occur for p6c since a given identity is considered immutable for perl6 installed distributions themselves.

**Comment by patzim** [comment]
At least according to https://modules.perl6.org/search/?q=+NativeHelpers%3A%3ABlob that module is not released on CPAN.

So if I understand this correctly the problem is inherent to how perl6 module management is meant to work and how using a development git repo diverges from that.
So what module authors could do to keep p6c releases consistent is have a separate release branch and push there only on version bumps or bump the version with every single commit.
Or even better move to CPAN for good. :-)

I think this issue can be closed then.

**Comment by patzim** [comment]
Thanks for the explanation!

**Comment by ugexe** [comment]
> the problem is inherent to how perl6 module management is meant to work and how using a development git repo diverges from that.

To be clear it is not just external module management but also internal. For instance: if you had old v0.0.2 installed and cloned the new v0.0.2 and tried to install it would fail. And it is not just git repos -- if someone mispackaged tarballs such that there were two v0.0.2 available on e.g. cpan this same problem would emerge. But these are problems that individual ecosystem policy and module authors must manage.

> So what module authors could do to keep p6c releases consistent is have a separate release branch and push there only on version bumps or bump the version with every single commit.

There are multiple ways. One could update their source-url to point at the last release like `"source-url" : "https://github.com/ugexe/Perl6-Text--Table--Simple.git@v0.0.4"`. Or one could keep the version at `"version" : "0.0.3.PREVIEW"` and when releasing to cpan remove the `.PREVIEW` (0.0.3 is newer than 0.0.3.PREVIEW). Or one can do manual entries in the META.list for each version linking directly from github https://github.com/ugexe/Perl6-PathTools/archive/0434191c56e0f3254ab1d756d90f9191577de5a0.tar.gz

**Comment by patzim** [comment]
Ohh, I start to see how nice this could work if used correctly. We should really write this down somewhere prominent.
Thanks again for this explanation!
