### ISSUE TITLE
Manual installation from git doesn't work without --config-path

### ISSUE THREAD

**Issue by drclaw1394** [ugexe/zef#291]
After cloning the repo on to machines which previously have not had Zef installed, the manual installation procedure  fails with 'Failed to find the zef config file'
 
The manual instructions on the README say to install with `perl6 -I. bin/zef install .` . On a couple of systems I've tested, this fails as the the config file in ~/.config/zef doesn't exist yet.

Adding the the `--config-path resources/config.json` allows the install to work.
`perl6 -I. bin/zef install .  --config-path resources/config.json`

Rakudo version 2016.12  (quite old I know)
Debian 4.9.88 and Raspberrian

**Comment by ugexe** [comment]
If it is what I think it is then -Ilib instead of -I. will work (a Rakudo bug since fixed).
