### ISSUE TITLE
WARNING: unhandled Failure detected in DESTROY

### ISSUE THREAD

**Issue by CurtTilmes** [ugexe/zef#293]
I'm packaging zef in an an environment that doesn't have write permission to /usr/share/perl6/site/short, but it seems to keep trying that, which is ok, but it doesn't handle the Failure well, so even during a successful run, I get pages of warnings like this:

```
WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
Failed to create directory '/usr/share/perl6/site/short' with mode '0o777': Failed to mkdir: Permission denied
  in block  at /usr/share/perl6/vendor/sources/47BFC724EB4738A4187F5A6C013244F5B909AEA4 (Zef) line 133
  in code  at /usr/share/perl6/vendor/sources/47BFC724EB4738A4187F5A6C013244F5B909AEA4 (Zef) line 124
  in method report at /usr/share/perl6/vendor/sources/6EA0D56F8C507DA7D08722F0782BBD717201A832 (Zef::Report) line 11
  in block  at /usr/share/perl6/vendor/sources/D0D4354DAAA6913994CA382AECCD79B8DA4CD8F3 (Zef::CLI) line 868
  in block  at /usr/share/perl6/vendor/sources/76B2A8509505785CE0ADAEC4376294187DB6E1AB (Zef::Client) line 363
  in method test at /usr/share/perl6/vendor/sources/76B2A8509505785CE0ADAEC4376294187DB6E1AB (Zef::Client) line 335
  in sub  at /usr/share/perl6/vendor/sources/76B2A8509505785CE0ADAEC4376294187DB6E1AB (Zef::Client) line 561
  in method make-install at /usr/share/perl6/vendor/sources/76B2A8509505785CE0ADAEC4376294187DB6E1AB (Zef::Client) line 591
  in sub MAIN at /usr/share/perl6/vendor/sources/D0D4354DAAA6913994CA382AECCD79B8DA4CD8F3 (Zef::CLI) line 183
  in sub MAIN at /usr/share/perl6/vendor/sources/D0D4354DAAA6913994CA382AECCD79B8DA4CD8F3 (Zef::CLI) line 25
  in block <unit> at /usr/share/perl6/vendor/resources/40367DA146C5351EC80EF7674F54A2C6EDA856C1 line 3
  in sub MAIN at /usr/bin/zef line 3
  in block <unit> at /usr/bin/zef line 1
```

## Steps to Reproduce

I've tried several ways, and it is very difficult to reproduce outside my environment -- I think it has to do with "/usr/share/perl6/site/short" being NOT writable, and being memory constrained enough that DESTROY() gets called a lot.  That is what warns about the unhandled Failures.

I'm having so much trouble reproducing outside my environment, it is possible that the problem is unique to my environment.

## Your Environment
I'm using alpine 3.9

```
$ perl6 -v
This is Rakudo version 2019.03 built on MoarVM version 2019.03
implementing Perl 6.d.
```

**Comment by ugexe** [comment]
I don't think this is an issue with zef. See [this code](https://github.com/rakudo/rakudo/blob/70d61b21446fb5156d0b00a9187de7b04add6b8c/src/core/CompUnit/Repository/Installation.pm6#L63) which will try to create that directory if it does not exists. This is further evidenced by the error message pointing at https://github.com/ugexe/zef/blob/a56b65a120d27e2dfb6c470e5f179993ef5c8c95/lib/Zef.pm6#L133 which is the plugin module loading code.

**Comment by CurtTilmes** [comment]
Thanks for looking at it.  I'll try to figure it out.

**Comment by ugexe** [comment]
See https://github.com/rakudo/rakudo/issues/1515 for a seemingly similar issue
