### ISSUE TITLE
Zef install is very slow

### ISSUE THREAD

**Issue by melezhik** [ugexe/zef#294]
## Context

Installing my source code with zef. All dependencies are met, but install takes minutes 

## Expected Behavior
Normally I'd expect no more 10 seconds for my typical install

## Actual Behavior
It takes more than 2 minutes

## Steps to Reproduce
Install dependencies, it's nothing install here, but even this steps takes `10 sec`, I basically okay with that, but next step is way too slow 

```
git clone https://github.com/melezhik/Sparrow6
cd Sparrow6
[melezhik@localhost Sparrow6]$ time zef install --deps-only . --verbose
The following local path candidates are already installed: .
All candidates are currently installed

real	0m10.089s
user	0m13.209s
sys	0m1.010s

```

Install module itself:

```
[melezhik@localhost Sparrow6]$ time zef install . --force-install --verbose
The following local path candidates are already installed: .
===> Testing: Sparrow6:ver<0.0.1>
t/00-load.t ................. ok
t/01-sparrow6-runner.t ...... ok
t/02-sparrow6-sparrowhub.t .. ok
t/03-sparrow6-dsl.t ......... ok
All tests successful.
Files=4, Tests=4,  9 wallclock secs ( 0.14 usr  0.02 sys + 13.02 cusr  1.40 csys = 14.58 CPU)
Result: PASS
===> Testing [OK] for Sparrow6:ver<0.0.1>
===> Installing: Sparrow6:ver<0.0.1>
===> Install [OK] for Sparrow6:ver<0.0.1>

1 bin/ script [s6] installed to:
/home/melezhik/.perl6/bin

real	2m24.004s
user	3m36.418s
sys	0m17.652s
```
[Top stats](https://asciinema.org/a/Z00AYHVqTU6UmlUijUW03vy5T) for the *last* step shows high usage of CPU.

## Your Environment

* OS

Centos7

```
uname -r
3.10.0-862.14.4.el7.x86_64
```
* perl6 -v

This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.

* zef list --installed

===> Found via /home/melezhik/.perl6
App::Mi6:ver<0.2.3>:auth<cpan:SKAJI>
Bailador:ver<0.0.15>:auth<github:Bailador>
CPAN::Uploader::Tiny:ver<0.0.6>:auth<cpan:SKAJI>
Config::INI
Config::Simple:auth<Sylvain Colinet>
DBIish:ver<0.5.17>
Data::Dump:ver<.0.0.8>:auth<github:tony-o>
Digest::HMAC:ver<1.0.0>:auth<github:retupmoca>
Digest:ver<0.3.4>:auth<Lucien Grondin>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Temp:ver<0.0.6>
File::Which:ver<1.0.1>
HTML::Escape:ver<0.0.1>
HTTP::Easy:ver<1.1.0>
HTTP::HPACK:ver<0.9.2>
HTTP::MultiPartParser
HTTP::Request::Supply:ver<0.1.1>:auth<github:zostay>
HTTP::Server::Ogre:ver<0.0.3>
HTTP::Status
HTTP::Tinyish:ver<0.1.3>:auth<cpan:SKAJI>
Hash::Merge:ver<1.0.0>:auth<github:scriptkitties>:api<1>
JSON::Class:ver<0.0.10>:auth<github:jonathanstowe>
JSON::Fast:ver<0.9.12>
JSON::Marshal:ver<0.0.14>:auth<github:jonathanstowe>
JSON::Name:ver<0.0.2>:auth<github:jonathanstowe>
JSON::Pretty:ver<0.1.0>:auth<github:FROGGS>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
Log::Any:ver<0.9.4>
META6:ver<0.0.19>:auth<github:jonathanstowe>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
NativeHelpers::Blob:ver<0.1.10>:auth<github:salortiz>
PSGI:ver<1.2.0>
Path::Iterator:ver<0.0.1>:auth<Leon Timmermans>
Pod::Load:ver<0.4.0>
Pod::To::HTML:ver<0.6.1>:auth<Perl 6>
Pod::To::Markdown:ver<.0.1.4>
Shell::Command
Sparky:ver<0.0.24>
Sparrow6:ver<0.0.1>
Sparrowdo:ver<0.0.42>
Sparrowdo:ver<0.0.43>
Sparrowdo:ver<0.0.44>
Sparrowdo:ver<0.0.45>
Temp::Path:ver<1.001003>
Template::Mojo:ver<.0.1>
Template::Mustache:ver<1.0.1>:auth<github:softmoth>
Terminal::ANSIColor:ver<0.5>
Test::META:ver<0.0.14>:auth<github:jonathanstowe>
Testo:ver<1.003004>
Text::Markdown:ver<1.0.2>:auth<github:retupmoca>
Time::Crontab:ver<0.1.0>
Tomtit:ver<0.0.28>
URI::Encode:ver<0.07>
URI:ver<.0.1.4>
YAMLish:ver<0.0.4>:auth<Leon Timmermans>
sake
===> Found via /opt/rakudo-pkg/share/perl6
CORE:ver<6.d>:auth<perl>
zef:ver<0.6.0>:auth<github:ugexe>:api<0>

**Comment by ugexe** [comment]
Installation includes precompilation, and that is handled inside Rakudo. You could not install these any faster manually using the CompUnit::Repository api, and as such there is nothing zef can do to reduce installation time. If your distribution contains lots of modules it will take longer to precompile period.

**Comment by melezhik** [comment]
Well, `sudo yum update` did he trick ( \~ 1300 packages updated because I've not update for awhile ). Install time has dropped to 14 sec from 2-3 minutes! WOW.

    [melezhik@localhost Sparrow6]$ time zef install --/test --force-install .
    ===> Installing: Sparrow6:ver<0.0.1>
    
    1 bin/ script [s6] installed to:
    /home/melezhik/.perl6/bin
    
    real	0m14.424s
    user	0m22.596s
    sys	0m1.884s
