### ISSUE TITLE
[install] "auth<github:ugexe>:api" test fail, and "Too few positionals passed" after force

### ISSUE THREAD

**Issue by WillForan** [ugexe/zef#298]
I'm trying to install using the readme instructions on debian stable. I've also tried to accumulate solutions that have worked for other issues. 
Auth api fails testing and force install has a zef error with 
> Too few positionals passed; expected 2 arguments but got 1

```
perl6 -Ilib -I. bin/zef install . --config-path resources/config.json 
===> Testing: zef:ver<0.7.4>:auth<github:ugexe>:api<0>
===> Testing [FAIL]: zef:ver<0.7.4>:auth<github:ugexe>:api<0>
Aborting due to test failure: zef:ver<0.7.4>:auth<github:ugexe>:api<0> (use --force-test to override)
```

## Context
Install's test fails, but can be forced. After forcing zef is unable to search or install.

## Expected Behavior
zef installs its self to `~/.perl6/bin` and runs `zef search URI` without error

## Actual Behavior
install can be forced but zef errors out when run
```
zef search URI
Too few positionals passed; expected 2 arguments but got 1
```

Using zef like the install command also reports the same error
`perl6 -I. -Ilib bin/zef search URI --config-path resources/config.json `
> Too few positionals passed; expected 2 arguments but got 1

## Steps to Reproduce
```
git clone https://github.com/ugexe/zef.git
cd zef
perl6 -I. -Ilib bin/zef search URI --config-path resources/config.json
# Too few positionals passed; expected 2 arguments but got 1

perl6 -I. bin/zef install --force .
zef search URI  
# Too few positionals passed; expected 2 arguments but got 1
```

## Your Environment
`perl6 -v`
> This is Rakudo version 2016.12 built on MoarVM version 2016.12
> implementing Perl 6.c.

`zef list --installed`
> ===> Found via /usr/share/perl6
> CORE:ver<6.c>:auth<perl>
> ===> Found via /home/foranw/.perl6
> zef:ver<0.7.4>:auth<github:ugexe>:api<0>

`cat /etc/debian_version`
> 9.8

**Comment by ugexe** [comment]
I'm gonna take a wild guess and say your `perl6` version is too old. You might try cloning an older version of zef from around `2016.12`.

**Comment by WillForan** [comment]
Ahh that seems obvious now. 

Sun Jun 18 23:18:34 2017 - 4c2976d - fails 
Wed Jun 14 22:08:58 2017 - c6c2584 - search works,  $PRE-DIST-INTERFACE causes install failure

I haven't checkout a commit that doesn't crash on install yet
2017: &zrun from Zef::Shell, because it already exists in this lexical scope
2015/6: Could not find Zef::Utils::SystemTools

probably easier to get perl6 outside of apt-get :)

**Comment by ugexe** [comment]
debian testing has something from late 2018 from what I'm told
