### ISSUE TITLE
cro fails to install

### ISSUE THREAD

**Issue by jelkner** [ugexe/zef#299]
## Your Environment

* perl6 -v
* zef list --installed

**Comment by jelkner** [comment]
$ perl6 -v
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

$ zef list --installed
===> Found via /home/jelkner/.perl6
Readline:ver('0.1.5'):auth('github:drforr')
zef:ver('0.1.15'):auth('github:ugexe')
LibraryCheck:ver('0.0.8'):auth('github:jonathanstowe'):api('1.0')
OpenSSL:ver('0.1.22'):auth('github:sergot')
===> Found via /opt/rakudo-pkg/share/perl6
CORE:ver('6.d'):auth('perl')
zef:ver('0.7.1'):auth('github:ugexe'):api('0')

I ran: zef --debug install Cro::HTTP  which resulted in the following failure:

https://pastebin.com/uKH6T6zp

**Comment by Altai-man** [comment]
The response is at https://colabti.org/irclogger/irclogger_log/perl6?date=2019-05-31#l489

**Comment by Altai-man** [comment]
The issue can be fixed executing `/opt/rakudo-pkg/bin/install-zef-as-user` command from rakudo-pkg package.
