### ISSUE TITLE
zef test needs a META6.json

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#300]
## Context

In some cases you just want to run the tests before META6.json has been created or simply in a package that does not have that information.

## Expected Behavior

An option should allow running tests without parsing META6.json, or forcing tests in that case.

## Actual Behavior

```
No meta file? Path: .
```

## Steps to Reproduce

Run `zef test .`

## Your Environment

zef version 0.7.4

**Comment by ugexe** [comment]
You cannot test a single file either.  Nor can one just install a distribution without a META6.json. zef is for managing distributions, not authoring them, so it gets to make certain assumptions about the state of the code it works with.
