### ISSUE TITLE
Possible zef issue build a dependency

### ISSUE THREAD

**Issue by pmqs** [ugexe/zef#302]
Not sure if this is a zef issue or a module issue, so here goes.

Building **[Archive::SimpleZip](https://github.com/pmqs/Archive-SimpleZip)** on travis used to work, but is now failing with the **[CompUnit::Util](https://github.com/LLFourn/p6-CompUnit-Util)** dependency. 

Below if taken from a build today -- https://travis-ci.org/pmqs/Archive-SimpleZip/jobs/542263527

```
===> Fetching: CompUnit::Util
Enabled fetching backends [git path curl wget] don't understand git://github.com/LLFourn/p6-CompUnit-Util
You may need to configure one of the following backends, or install its underlying software - [pswebrequest]
The command "zef --debug --depsonly install ." failed and exited with 1 during .
```

Here is a build I did a couple of months ago (https://travis-ci.org/pmqs/Archive-SimpleZip/jobs/513845783) where everything was fine.

```
Fetching with plugin: Zef::Service::Shell::git+{<anon|1>}
===> Fetching [OK]: CompUnit::Util:ver<0.6.0> to /home/travis/.zef/tmp/1554063082.7455.8095/p6-CompUnit-Util.git
```

The thing is, the failing module **CompUnit::Util** hasn't changed in a couple of years.

Is this a **zef** issue or a **CompUnit::Util** issue (or pilot error on my part)?

**Comment by ugexe** [comment]
It probably broke when the ecosystem mirror was switched. The old mirror (I *think*) changed all `git://` urls to `https://` and added `.git` to the end. The new mirror leaves all source-url as their original value. The problem is then that `zef` only considers url ending with `.git` as git url:

https://github.com/ugexe/zef/blob/e73897378b36cbf53f2ed8d98363d94bac70767d/lib/Zef/Service/Shell/git.pm6#L11-L14

...which should probably be
```
$url.starts-with('git:') || ($url.starts-with('http:' | 'ssh:') && $url.ends-with('.git'));
```

**Comment by pmqs** [comment]
Thanks. That makes sense. 

I'll send a pull request for CompUnit::Util to fix the issue.

**Comment by pmqs** [comment]
Problem not with zef, so closing this issue.

**Comment by FCO** [comment]
I'm getting this same error on GitHub actions: https://github.com/FCO/Red/runs/6242265753?check_suite_focus=true
