### ISSUE TITLE
Perl6::Typegraph cannot be installed

### ISSUE THREAD

**Issue by antoniogamiz** [ugexe/zef#304]
## Context

Yesterday I published a new module in the perl6 ecosystem and it gives this error:

Output: (zef install Perl6::TypeGraph)

~~~
===> Searching for: Perl6::TypeGraph
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
Invocant of method 'match' must be a type object of type 'Any', not an object instance of type 'Pair'.  Did you forget a 'multi'?
~~~

## Steps to Reproduce

`zef install Perl6::TypeGraph`

## Your Environment => Ubuntu 16.04
* perl6 -v
~~~
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
~~~

**Comment by Altai-man** [comment]
A fix is provided at https://github.com/ugexe/zef/pull/305

**Comment by ugexe** [comment]
Before publishing a module you should be testing that it installs and works locally. Ignore that zef failed to install this -- rakudo would have no idea how to understand how to parse your `resources` section and thus I'm not sure that distribution can possibly work as expected.
