### ISSUE TITLE
Failed to update cpan mirror

### ISSUE THREAD

**Issue by cup** [ugexe/zef#306]
~~~
$ zef --version
v0.7.4

$ zef install Text::More
===> Searching for: Text::More
===> Updating cpan mirror:
https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
!!!> Failed to update cpan mirror:
https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
~~~

**Comment by ugexe** [comment]
And?

**Comment by cup** [comment]
sorry I was not clear - it appears that Zef is unable to install any packages

what more information are you needing?

**Comment by ugexe** [comment]
If zef was unable to install packages others would have this same problem. Instead there is something about your system specifically (of which I also know nothing about from this issue) causing it to not fetch some url (or maybe the url was down at the moment you tried it... again insufficient information). For instance: do you have curl or wget installed? These types of questions can be answered in IRC, where there is a higher number of people to help debug.

**Comment by cup** [comment]
> do you have curl or wget installed

cURL is installed and on my PATH

> These types of questions can be answered in IRC, where there is a higher
> number of people to help debug.

I prefer using GitHub issue, as its on the same site as the source code, which
is simpler than visiting another site. If you refuse to help based on this fact
I understand, but I would appreciate the assistance. Thank you

**Comment by ugexe** [comment]
But this isn't an issue with the source code, its likely an issue with your system setup. Thats why I don't think you're going to get a timely (or good) answer here. And while I'm happy to help debug issues with this software I'm less inclined to provide more general systems support. Have you tried fetching the url zef has told you it is failing to fetch to verify your claim that this is an issue with zef?

**Comment by cup** [comment]
~~~
$ curl -I https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
HTTP/1.1 200 OK
~~~

**Comment by ugexe** [comment]
https://github.com/ugexe/zef/blob/master/lib/Zef/Service/Shell/curl.pm6

Clone zef and edit the file above to debug what it is doing (removing `--silent` might be a good start). You'll want to run zef via `perl6 -I. bin/zef install Text::More` to be sure you use the changed file. The only thing I can guess now is that it is failing to write the file `$HOME/.zef`.

**Comment by ugexe** [comment]
Something like

```
        react {
            my $cwd := $save-as.parent;
            my $ENV := %*ENV;
            my $proc = zrun-async('curl', '-L', '-z', $save-as.absolute, '-o', $save-as.absolute, $url);
            whenever $proc.stdout { .say  }
            whenever $proc.stderr { .note }
            whenever $proc.start(:$ENV, :$cwd) { $passed = $_.so }
        }
```

**Comment by cup** [comment]
Hm, why is Zef using a call to cURL binary? shouldnt it be using `LWP::Simple` or similar?

https://rosettacode.org/wiki/HTTP#Perl_6

**Comment by ugexe** [comment]
You are free to write a plugin to do just that. But in its core form no -- how would LWP::Simple get installed? And I don't mean how would it get install from github, I mean how would it get installed from a DarkPAN, or a local copy, or via a network, or...

**Comment by cup** [comment]
Yeah good point, I guess I am just used to Python and Ruby that have built in network support. Does Perl 6 really have not any built in ability for HTTP requests?

**Comment by ugexe** [comment]
HTTP requests isn't sufficient. Also need HTTPS/OpenSSL and a way to extract files. Someone wanting a bunch of modules already installed would be using Rakudo Star.

**Comment by cup** [comment]
> https://github.com/ugexe/zef/blob/master/lib/Zef/Service/Shell/curl.pm6
>
> Clone zef and edit the file above to debug what it is doing (removing
> `--silent` might be a good start).

Doing this and running as:

~~~
perl6 -Izef-master zef-master/bin/zef install Text::More
~~~

seems to have changed nothing, I didnt even get different output. However this
raises a question: why is this project created in such a way that user has to
clone and edit a file just to get debug output? shouldnt Zef have some debug
flag that removes the cURL silent flag, among other things?

> HTTP requests isn't sufficient. Also need HTTPS/OpenSSL

I am still confused why something like this isnt in base Perl 6. Python has
HTTP/HTTPS via:

https://docs.python.org/library/urllib.request

Ruby has HTTP/HTTPS via:

http://ruby-doc.org/stdlib/libdoc/net/http/rdoc/Net/HTTP.html

Go has HTTP/HTTPS via:

https://golang.org/pkg/net/http

D has HTTP/HTTPS via:

https://dlang.org/library/std/net/curl

Nim has HTTP/HTTPS via:

http://nim-lang.github.io/Nim/httpclient

> and a way to extract files

I am not sure why you mention this, as cURL doesnt do extracting.

> Someone wanting a bunch of modules already installed would be using Rakudo
> Star.

This is confusing because it seems that Rakudo Star is the only current option:

https://rakudo.org/files

So I dont know what other Perl 6 you would be referring to. and even with Rakuko
Star, it seems you are alluding to the fact that a built in HTTP client is not
available, let alone a HTTPS one.

**Comment by ugexe** [comment]
PRs are welcome if you feel like something is missing. This is entirely off topic at this point.

**Comment by cup** [comment]
Trying just removing silent, and also trying your patch seems to give exact
output as original request.

If you wish to close the issue thats your business, but this feels as a
legitimate issue. While I am a novice to Perl 6, I am not a novice computer
programmer.

As alluded to in my previous comment I have written HTTPS clients
in several other languages, and all I have done essentially is run a stock
Rakudo installation with no modifications and Zef is not working.

**Comment by tony-o** [comment]
@cup - how did you install perl6 and zef?

**Comment by cup** [comment]
@tony-o 

https://rakudo.org/files

**Comment by tony-o** [comment]
Did you build from source or, which distribution are you on?

How long does that install command take to time out and report the update failed?

Sent from my iPhone

On Jul 19, 2019, at 6:37 PM, Steven Penny <notifications@github.com<mailto:notifications@github.com>> wrote:


Trying just removing silent, and also trying your patch seems to give exact
output as original request.

If you wish to close the issue thats your business, but this feels as a
legitimate issue. While I am a novice to Perl 6, I am not a novice computer
programmer.

As alluded to in my previous comment I have written HTTPS clients
in several other languages, and all I have done essentially is run a stock
Rakudo installation with no modifications and Zef is not working.

**Comment by cup** [comment]
> Did you build from source or, which distribution are you on?

Windows

> How long does that install command take to time out and report the update
> failed?

About 1 second, either with stock Zef, or with @ugexe modified version

**Comment by tony-o** [comment]
How are you running zef? Cygwin? Moar or JVM? Can perl6 find your curl bin? How is curl installed? If you modify the source to output the curl command that actually gets run, does that command ever get echo’d and if it does, does it succeed, does it succeed if you run it with perl6 rather than directly in the XYZ environment?

https://github.com/ugexe/zef/blob/master/README.pod#output-verbosity

Sent from my iPhone

On Jul 19, 2019, at 7:14 PM, Steven Penny <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you build from source or, which distribution are you on?

Windows

How long does that install command take to time out and report the update
failed?

About 1 second, either with stock Zef, or with @ugexe<https://github.com/ugexe> modified version

**Comment by cup** [comment]
I solved it. Zef requires these on the PATH, which makes sense:

~~~
C:\rakudo\bin
C:\rakudo\share\perl6\site\bin
~~~

but it also requires this on the PATH:

~~~
C:\Windows\System32
~~~

I am not sure at this point what Zef is calling from the Windows sytem folder,
but adding that to the PATH fixes the problem. Thanks for the help all.

**Comment by niner** [comment]
On Samstag, 20. Juli 2019 03:25:01 CEST Steven Penny wrote:

> I am still confused why something like this isnt in base Perl 6. Python has
> HTTP/HTTPS via:
> 
> https://docs.python.org/library/urllib.request

And Python has had huge issues with security implications because of this:
https://lwn.net/Articles/582065/

And because in Python, there's preferably only one obvious way to do 
something, there's http/https in httplib, urllib, urllib2 and now urllib3:
https://lwn.net/Articles/309091/ accompanied by requests and now Requests III.
