### ISSUE TITLE
Path to cmd.exe

### ISSUE THREAD

**Issue by cup** [ugexe/zef#307]
This line:

https://github.com/ugexe/zef/blob/e73897378b36cbf53f2ed8d98363d94bac70767d/lib/Zef.pm6#L3

Assumes that `cmd.exe` is on the PATH. This is not guaranteed on a Windows
system, so it might be helpful to change to the full path:

~~~
C:\Windows\System32\cmd.exe
~~~

or to emit some warning if not found. The current incarnation of Zef just fails
silently with regard to a missing `cmd.exe`.

**Comment by ugexe** [comment]
I tried replacing `cmd.exe` with `%SystemRoot%\\System32\\cmd.exe`. This passed tests in `xt/` on a local windows VM, but it isn't working on appveyor (which *does* have a `C:\Windows\System32\cmd.exe`, and shows the `C:\Windows` for `echo %SystemRoot%`). Not really sure how what is going on...

**Comment by cup** [comment]
I cant test right now, but couple of things. when I did test it on my system, i just changed it to

~~~
C:\Windows\System32\cmd.exe
~~~

not

~~~
C:\\Windows\\System32\\cmd.exe
~~~

not sure if i was using wrong syntax and got lucky, but the single backslash was working for me. also `%SystemRoot%` seems fishy, as Perl would have no notion of what that is, I would think `%*ENV` would be better, but i dont know the parsing rules inside of `<>`. i can test more when i get home

**Comment by cup** [comment]
So Zef is not the only culprit. Rakudo Star also includes the module
Shell::Command:

https://github.com/rakudo/star/tree/master/modules

which makes the same assumption about `cmd.exe`:

https://github.com/tadzik/Shell-Command/blob/1145ea0f/lib/Shell/Command.pm#L7

However instead of being found under:

~~~
lib/Shell/Command.pm
~~~

Rakudo Star puts it in the file:

~~~
share/perl6/site/sources/A8DEB6B92199DFB3A54F3218FA4BE0FCB99045C0
~~~

I tried editing the file, but I dont think it works because of precompilation?
I dont know.

**Comment by ugexe** [comment]
To test -- clone a local copy of the repo, change into the directory, and do `perl6 -Ilib ...` (which will use the local copy instead of the installed one)

**Comment by ugexe** [comment]
I think `%*ENV<ComSpec>` should give the path to `cmd.exe`

**Comment by cup** [comment]
@ugexe using this:

~~~
perl6.bat -Izef-master zef-master/bin/zef update
~~~

and this:

~~~
C:\Windows\System32\cmd.exe
~~~

fixed the issue. Few points:

1. `C:/Windows/System32/cmd.exe` didnt work

2. `%*ENV<ComSpec>` didnt work

3. `%*ENV<COMSPEC>` didnt work (cygwin upcases environ vars)

4. I only needed to change Zef, it seems Shell::Command is not causing the
   problem in this case

**Comment by cup** [comment]
looks like this is the problem:

~~~
> %*ENV<COMSPEC>
C:\Windows\system32\cmd.exe

> <%*ENV<COMSPEC>>.Slip
(%*ENV<COMSPEC>)
~~~

**Comment by ugexe** [comment]
The quote constructs `<` `>` don't interpolate. It'd need to be `<<%*ENV<ComSpec>>>` (`<<` and `>>`), but that doesn't handle when `ComSpec` vs `COMSPEC`. A more robust solution would probably look like this:
```
my @zrun-invoke = BEGIN $*DISTRO.is-win ?? ((%*ENV.first({.key.lc eq 'comspec'}).?value // 'cmd.exe').Str,  '/x/d/c') !! '';
```

**Comment by cup** [comment]
`COMSPEC` should be fine - Cygwin upcases and is case sensitive - I believe all other shells are case insensitive

**Comment by ugexe** [comment]
`%*ENV` isn't part of the shell, so yes it matters

**Comment by cup** [comment]
Ah, I see its really just a Perl hash at that point, so yes the case would need to be checked, good call

**Comment by ugexe** [comment]
As I already mentioned: using the full path is fragile. What if windows is not installed on the C volume? That is actually a less robust solution that the existing ‘cmd.exe’

**Comment by cup** [comment]
understood - your new code is robust, just verbose for my liking

another option would be to just warn if `cmd.exe` is not found on the PATH - same could be done with cURL, then user would know to add `cmd.exe` in the first case, and install cURL or user PowerShell option in the other.

but its your repo - i think the problem is pretty much solved at this point, just a matter of which fix to use, thanks

**Comment by cup** [comment]
@ugexe I just noticed that this command works under Cygwin:

~~~pl
my @zrun-invoke = BEGIN $*DISTRO.is-win ?? '' !! '';
~~~

so it seems that `cmd.exe` is actually only needed if that is the persons shell. Does Perl 6 have a way to check the persons shell? I know bash does:

~~~
$ bash -c 'echo $SHELL'
/bin/bash
~~~

this might be a better fix than previously discussed - as if a persons shell is `cmd.exe`, almost assuredly it will be on the path so `COMSPEC` wouldnt be needed. Let me know what you think
