### ISSUE TITLE
Use module instead of cURL

### ISSUE THREAD

**Issue by cup** [ugexe/zef#308]
HTTP::UserAgent:

https://github.com/sergot/http-useragent

Is included with Rakudo Star:

https://github.com/rakudo/star/tree/139ba633/modules

So it might be better to use that instead of relying on the cURL binary:

https://github.com/ugexe/zef/blob/e73897378b36cbf53f2ed8d98363d94bac70767d/lib/Zef/Service/Shell/curl.pm6#L18

**Comment by ugexe** [comment]
Zef is intended to run on any bare perl6 implementation, not just Rakudo and not just the distribution containing a bunch of modules (Rakudo star uses zef to package its modules even). As I mentioned earlier anyone is free to write plugins to use whatever they want — see the configuration file.

**Comment by cup** [comment]
Youre sacrificing one for the other.

Every Windows Perl 6 user will have HTTP::UserAgent, but not every Windows
Perl 6 user will have cURL. That is your decision of course, but I felt it right
to mention.

As an alternative, Windows have FTP support via `ftp.exe`, and FTP, HTTP, HTTPS
support via `powershell.exe`.

**Comment by ugexe** [comment]
There is already a powershell script capable of downloading https://github.com/ugexe/zef/blob/e73897378b36cbf53f2ed8d98363d94bac70767d/resources/config.json#L95-L98

You were asked if you had curl installed because curl is preferred.

**Comment by cup** [comment]
good points, thank you
