### ISSUE TITLE
zef should recognize $RAKU_PREFIX for module installation location

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#311]
Or use whatever standard environment variable is standardized for such use.

**Comment by tbrowder** [comment]
It would be useful for system admins wanting to install Rakudo and all ecosystem modules to a well-known system location.

**Comment by ugexe** [comment]
The ‘site’ repo will always be under a compiler’s prefix — there is no reason to understand that env car when one can use —install-to=site (which is also the default) or even a path via —install-to=$FOO_PREFIX/whatever

**Comment by ugexe** [comment]
Additionally that env var is intended to point and contain 1 specific version of Rakudo. Installing modules from multiple versions (via upgrading Rakudo or having multiple versions installed) would not work since the repository format can change between versions.

**Comment by tbrowder** [comment]
Thanks. Closing.
