### ISSUE TITLE
A version different from that specified in META6.json is sometimes installed (or it fails)

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#312]
## Context

Pod::To::Cached was recently changed to a new repo. The new META6.json changed version (to 0.3.5) as well as added an "auth" field (which didn't exist before).

zef sometimes installs 0.3.3 (which is the old version, no longer in the ecosystem), sometimes does not complain, but it apparently does not install anything.

* Installing incorrect version here [here](https://travis-ci.org/perl6/Documentable/builds/580343036?utm_medium=notification&utm_source=email)
* It fails [here](https://circleci.com/gh/perl6/Documentable/120)

Please note that installation does not fail, but running tests that use it do.

Info seems correct:

```
zef info -v Pod::To::Cached
- Info for: Pod::To::Cached
- Identity: Pod::To::Cached:ver<0.3.5>:auth<finanalyst>
- Recommended By: Zef::Repository::Ecosystems<p6c>
- Installed: Yes
Description:	 Precompile a collection of pod files into a cache.
License:	 Artistic-2.0
Source-url:	 https://github.com/finanalyst/pod-cached.git
Provides: 2 modules
-----------------------------------------------------------------------------------------------
Module                                      |Path-Name                                         
-----------------------------------------------------------------------------------------------
Pod::To::Cached                             |lib/Pod/To/Cached.pm6                             
CompUnit::PrecompilationRepository::Document|lib/CompUnit/PrecompilationRepository/Document.pm6
-----------------------------------------------------------------------------------------------
Support:
#   source:	https://github.com/finanalyst/pod-cached/issues
Depends: 3 items
-----------------------------------
ID|Identity             |Installed?
-----------------------------------
1 |File::Directory::Tree|✓         
1 |JSON::Fast           |✓         
1 |Test::Output         |✓         
-----------------------------------
```

## Expected Behavior

Either install it correctly as it's available in the ecosystem (and found by zef search)

## Actual Behavior

Either install a previous version, or fail installation silently.

## Steps to Reproduce

This is going to be hard. It might be adding the "auth" field, it might be the change of author, it might be something totally different...

## Your Environment

The environments where CI is running is listed in the links.

**Comment by ugexe** [comment]
Looks like something strange with github. If I look at the ~/.zef/store/p6c/p6c.json file zef downloads it only shows this version:
```
   {  
      "support":{  
         "source":"https://github.com/finanalyst/pod-cached/issues"
      },
      "provides":{  
         "CompUnit::PrecompilationRepository::Document":"lib/CompUnit/PrecompilationRepository/Document.pm6",
         "Pod::To::Cached":"lib/Pod/To/Cached.pm6"
      },
      "version":"0.3.3",
      "source-type":"git",
      "license":"Artistic-2.0",
      "depends":[  
         "File::Directory::Tree",
         "JSON::Fast"
      ],
      "description":"Precompile a collection of pod files into a cache.",
      "perl":"6.*",
      "test-depends":[  
         "Test",
         "Test::Output",
         "JSON::Fast:ver<0.9.18+>",
         "File::Directory::Tree"
      ],
      "source-url":"https://github.com/finanalyst/pod-cached.git",
      "authors":"Richard Hainsworth",
      "name":"Pod::To::Cached"
   }
```

yet if I go to https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json manually it has the correct version
```
{
  "authors": "Richard Hainsworth",
  "depends": [
    "File::Directory::Tree",
    "JSON::Fast:ver<0.9.18+>"
  ],
  "description": "Precompile a collection of pod files into a cache.",
  "license": "Artistic-2.0",
  "name": "Pod::To::Cached",
  "perl": "6.*",
  "provides": {
    "CompUnit::PrecompilationRepository::Document": "lib/CompUnit/PrecompilationRepository/Document.pm6",
    "Pod::To::Cached": "lib/Pod/To/Cached.pm6"
  },
  "source-type": "git",
  "source-url": "https://github.com/perl6/Pod-To-Cached.git",
  "support": {
    "source": "https://github.com/perl6/Pod-To-Cached/issues"
  },
  "test-depends": [
    "Test::Output"
  ],
  "version": "0.3.5"
}
```

**Comment by ugexe** [comment]
...but https://ecosystem-api.p6c.org/projects1.json only shows version 0.3.3

**Comment by ugexe** [comment]
Pretty sure this is just a side effect of using the p6c ecosystem with modules that list a `master` as their source-url since the ecosystems aren't updated instantly.

Probably isn't great that it lists an issue tracker as a support source url either since that is a alternative to `source-url` and not for a bugtracker.
