### ISSUE TITLE
Cannot install Pod::To::Cache version 0.3.5

### ISSUE THREAD

**Issue by atroxaper** [ugexe/zef#313]
## Context
Try to install the last version of Pod::To::Cache (0.3.5). If I try to `zef install Pod::To::Cache` I got 0.3.3 version. If I try to install 0.3.5 version then:
```
zef install 'Pod::To::Cached:ver<0.3.5>:auth<finanalyst>'
===> Searching for: Pod::To::Cached:ver<0.3.5>:auth<finanalyst>
===> Testing: Pod::To::Cached:ver<0.3.3>
# test pod extraction
# testing freeze
# Heavy duty test optional
===> Testing [OK] for Pod::To::Cached:ver<0.3.3>
===> Installing: Pod::To::Cached:ver<0.3.3>
!!!> Install failures: Pod::To::Cached:ver<0.3.5>:auth<finanalyst>
```

## Expected Behavior
The last version of Pod::To::Cached should be installed

## Actual Behavior
0.3.3 version installed or fail

## Steps to Reproduce
`zef install Pod::To::Cache`

## Your Environment
MacOs 10.14
* perl6 -v
`This is Rakudo version 2019.07.1-254-g17d036ad4 built on MoarVM version 2019.07.1-134-ga37504d12 implementing Perl 6.d.`
* zef list --installed
```
Documentable:ver<1.0.9>:auth<github:perl6>:api<1>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Temp:ver<0.0.6>
File::Which:ver<1.0.1>
JSON::Class:ver<0.0.13>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.10>
JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::Unmarshal:ver<0.08>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.6.0>:auth<github:jonathanstowe>:api<1.0>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
Perl6::TypeGraph:ver<2.1.1>:auth<github:antoniogamiz>:api<2>
Pod::Load:ver<0.5.5>
Pod::To::HTML:ver<0.6.2>:auth<Perl 6>
Pod::Utilities:ver<0.0.1>
Shell::Command
Template::Mustache:ver<1.0.1>:auth<github:softmoth>
Terminal::Spinners:ver<1.3.0>:auth<github:ryn1x>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
Test::Output:ver<1.001002>
URI:ver<0.3.0>
zef:ver<0.7.4>:auth<github:ugexe>:api<0>
```

```
zef search Pod::To::Cached
===> Found 2 results
-----------------------------------------------------------------------------------------------------------------------
ID|From                            |Package                                    |Description
-----------------------------------------------------------------------------------------------------------------------
0 |Zef::Repository::LocalCache     |Pod::To::Cached:ver<0.3.3>                 |Precompile a collection of pod files ..
1 |Zef::Repository::Ecosystems<p6c>|Pod::To::Cached:ver<0.3.5>:auth<finanalyst>|Precompile a collection of pod files ..
-----------------------------------------------------------------------------------------------------------------------
```

**Comment by ugexe** [comment]
Its failing during precompilation inside rakudo (outside of zef control). It is a bug in `Pod::To::Cached`

**Comment by JJ** [comment]
No it's not. [It passes all tests without a problem, locally or in CI](https://travis-ci.com/perl6/Pod-To-Cached)

**Comment by ugexe** [comment]
That doesn't mean there isn't a bug in the module. Does it test installation? No? Then how exactly can you say it is not?

**Comment by JJ** [comment]
Let's say it does, why does it try to install another version, which is not the one that was requested? Also, I'd appreciate you showed us how to get to that error.

**Comment by JJ** [comment]
I'm also installing it locally without a problem.

**Comment by ugexe** [comment]
It is not my job to do all the debugging for this. Instead i'd appreciate YOU figure it out -- i've already given you direction in that it isn't related to zef.

**Comment by JJ** [comment]
OK, let me see.
* We ask zef to install 0.3.5+
* zef instead tries to install 0.3.3 (for some reason)
* Testing 0.3.3 is OK
* But it says it *fails to install 0.3.5* (of course, since it didnt' even try to download it).

You say that zef didn't install it because there was a bug (you don't say if it's in 0.3.3 or in 0.3.5). But what seems to say above is that it's failing to install something that it didn't actually download.
It's probably the case that there's some error in the META6.json that we are missing. But in that case it woule *really* be helpful if that specific error was pointed out so that we can debug it.

**Comment by ugexe** [comment]
So send a PR to rakudo to give helpful errors when a module is passed to `.install`

**Comment by JJ** [comment]
I'm sorry, but I fail to understand how the bug that might or might not be in the mentioned module (and that is not found anywhere else) makes zef want to install a different version from the one requested.

**Comment by ugexe** [comment]
If that module had been released to cpan (or with any source-url that points to a specific version) then this would not be an issue.
