### ISSUE TITLE
error while attempting to use a Build.pm6 file

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#319]
## Context

In a repo directory with a Build.pm6  file and testing the build yields an error:

```
$ zef build --debug .
===> Building: Documentable:ver<1.1.0>:auth<github:perl6>:api<1>
Building with plugin: Zef::Service::Shell::LegacyBuild+{<anon|1>}
Command: /usr/local/rakudo.d/bin/perl6 -Ilib -e require '/usr/local/git-repos/forks/Documentable/Build.pm6'; ::('Build').new.build('/usr/local/git-repos/forks/Documentable') ?? exit(0) !! exit(1);
===> Building [FAIL]: Documentable:ver<1.1.0>:auth<github:perl6>:api<1>
Aborting due to build failure: Documentable:ver<1.1.0>:auth<github:perl6>:api<1> (use --force-build to override)
```

Using `--force-build` gives essentially the same error:

```
$ zef build --force-build --debug .
===> Building: Documentable:ver<1.1.0>:auth<github:perl6>:api<1>
Building with plugin: Zef::Service::Shell::LegacyBuild+{<anon|1>}
Command: /usr/local/rakudo.d/bin/perl6 -Ilib -e require '/usr/local/git-repos/forks/Documentable/Build.pm6'; ::('Build').new.build('/usr/local/git-repos/forks/Documentable') ?? exit(0) !! exit(1);
===> Building [FAIL]: Documentable:ver<1.1.0>:auth<github:perl6>:api<1>
Failed to build, but continuing with --force-build
!!!> Build failure: . at /usr/local/git-repos/forks/Documentable
```

The error seems to be an unquoted `perl6 -e` command in module `Zef::Service::Shell::LegacyBuild+{<anon|1>}`.  Creating the command at the CLI:

```
$ /usr/local/rakudo.d/bin/perl6 -Ilib -e require '/usr/local/git-repos/forks/Documentable/Build.pm6';
===SORRY!=== Error while compiling -e
Undeclared routine:
    require used at line 1
```

Properly quoting the command seems to work fine:

```
/usr/local/rakudo.d/bin/perl6 -Ilib -e "require '/usr/local/git-repos/forks/Documentable/Build.pm6'";
```

## Your Environment

```
$ perl6 -v
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
```
```
$ zef list --installed
App::Prove6:ver<0.0.10>:auth<cpan:LEONT>
Concurrent::Stack:ver<1.2>
DB::Pg:ver<0.6>
DB::SQLite:ver<0.3>
...LIST OF 96 MODULES...
```

I'll try to submit a PR soon.

**Comment by ugexe** [comment]
What is shown on stdout is not the same as what is run since quoting and escaping are implied with `run(@args)`. So this cannot be the cause of your build failure. Improving the output doesn't show quotes because the quotes used isn't known to zef (single quotes wouldnt work on windows for instance).

You must understand many modules use Build.pm already.

**Comment by ugexe** [comment]
What is your Build.pm6 code? Does method build return a true value (try adding return 1)?

**Comment by ugexe** [comment]
What is your Build.pm6 code? Does method build return a true value (try adding return 1)?

**Comment by tbrowder** [comment]
The error exists, but this report is incorrect. I will close this and open a new one if I can get a better example/
