### ISSUE TITLE
need a test for the Build phase using a Build.pm6 hook file

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#320]
I cannot get a successful "zef build --debug ." with any Build.pm6 file. I need to see a successful example.

**Comment by ugexe** [comment]
https://github.com/niner/Inline-Perl5/blob/master/Build.pm
https://github.com/krunen/term-termios/blob/master/Build.pm
https://github.com/titsuki/p6-MeCab/blob/master/Build.pm
https://github.com/titsuki/p6-Chart-Gnuplot/blob/master/Build.pm
https://github.com/titsuki/p6-Terminal-Readsecret/blob/master/Build.pm
https://github.com/bduggan/p6-digest-sha1-native/blob/master/Build.pm
https://github.com/jnthn/p6-ssh-libssh/blob/master/Build.pm
https://github.com/p6-pdf/Base64-Native-p6/blob/master/Build.pm

**Comment by tbrowder** [comment]
thanks!

**Comment by tbrowder** [comment]
I got myself into trouble when seeing the warning about perl6 -e when using zef --debug and started thinking there was a problem.  I messed around with changing code in zef and broke things. I started over and just ignored that warning and all seems to be working fine.

Sorry for the false alarm.

**Comment by tbrowder** [comment]
And the closed issue #319 was also a mistake...sorry for the false alarm... all is working well.
