### ISSUE TITLE
add a hook like Build.pm6 for cleanup prior to installation [FEATURE REQUEST]

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#321]
The Build.pm6 file permits module authors to modify local data prior to installation, sometimes for testing purposes. It would be useful to have a cleanup step prior to installation to delete unneeded files and directories. This would be very useful when testing installation of a module in its repo by the "zef install ." method.

## Proposal

Use a Clean.pm6 module, in like manner to Build.pm6, to be used after the test step, but before the install step, to do any post-test cleanup needed by the author.

**Comment by niner** [comment]
Experience from Perl 5 suggest that running arbitrary code as part of building/installing a module can become a nightmare to support for toolchain maintainers. That's also clear by just looking at how many Build.pm files still contain code for supporting panda which has been superseeded by zef for years. At the same time, zef needs to support a Build.pm structure that was defined by whatever tadzik first could get to work long before Perl 6 even had a stable release.

The problem with such build modules is that they do not tell the installer what needs to be done but only what to do exactly. This insight led to the development of the Distribution::Builder interface and the extensive possibilities that META6.json files actually give the author. https://design.perl6.org/S22.html#Dependency_hints

Unfortunately after developing and implementing those, I ran out of steam and never got to actually converting those Build.pm6 files out in the wild. The possibilities also barely made it into the documentation, so few people actually know about them. However, I'm still convinced that this is a much better direction for future extension.

**Comment by tbrowder** [comment]
Okay, got it. Can I help in any way?

**Comment by tbrowder** [comment]
I understand a bit more now, and no longer see the need for this.

The original motivation was to help with tests before deploying module Documentable which, IMHO, is beyond help in this regard.
