### ISSUE TITLE
p6c repo modules show dodgy behavior

### ISSUE THREAD

**Issue by patrickbkr** [ugexe/zef#328]
When installing a p6c module based on a git repository zef downloads the latest commit and caches it. Zef uses that cache irrespective of any further commits to that repository. This behavior is difficult to manage and understand. Unless one bumps the version on every single commit, a specific version can contain different sources, depending on when the module was cached.

[oo-monitors#16](https://github.com/jnthn/oo-monitors/issues/16) is an example of the confusion this behavior causes.

## Expected Behavior
I could imagine several alternative behaviors that would be less error prone and easier to understand. Here are two I came up with:
- Fully dynamic: Never cache modules based on a repository. Such modules are redownloaded every time. The version number of such modules is completely ignored. I'm not sure whether such a module should satisfy any version request or always fail when a specific version is requested.
- Fully static: Make zef inspect the repository and when searching for a given version take the oldest commit on `master` that declares the requested version. When not requesting a specific version, take the oldest commit that declares the same version as HEAD. That way a given version always points to the same commit and does not change.

We could also deprecate the p6c ecosystem and encourage people to move to CPAN.

**Comment by ugexe** [comment]
Well, a developer might refuse to depend on any modules in the p6c ecosystem for instance for this very reason using `--/p6c` or removing it from the zef config file entirely.

Both the dynamic and static solution just moves the layer where problems will occur. CUR doesn't understand what a git repository is or if the installed copy of v0.1 is newer than a modified copy of v0.1 -- it only understands exactly what the META6 declares that it is. If zef did some elaborate git-fu (which also ignores that not everything has to be `git`) people would just run into issues at the CURI level which is even harder to debug. zef emulates CUR behavior, and this consistency is a feature.

Now, that isn't to say these things couldn't be implemented at an ecosystem policy level -- indeed I've been stating this for awhile. Nothing is stopping anyone from creating an ecosystem where people submit their repos, and the ecosystem figures out what *it* will call some given identity when multiple commits share it.

More as-is authors are free to use an appropriate `source-url` / `support : source`, such as e.g. `https://github.com/ugexe/zef.git@v1.2.3` or `https://github.com/ugexe/zef.git@89u2982j39jl238jdih23fi` in the p6c ecosystem, updating these urls whenever they finally decide to bump versions.
