### ISSUE TITLE
apparently random "Enabled fetching backends [git path curl wget] don't understand http://www.cpan.org/…"

### ISSUE THREAD

**Issue by dakkar** [ugexe/zef#332]
Sometimes, when installing packages, I get this error message while `zef` is fetching dependencies:

    Enabled fetching backends [git path curl wget] don't understand http://www.cpan.org/authors/id/M/MO/MORITZ/Perl6/JSON-Tiny-1.0.tar.gz

(it's not always the same package, for example I also saw the same error about `Test::META`)

Other times it works.

## Context

This happened on a fresh build of rakudo 2019.11

## Steps to Reproduce

`$ zef install App::Prove6 Cro Grammar::Debugger Log::Timeline Test::META p6doc` failed for me, but running `zef` on each package separately didn't fail.

## Your Environment

* `raku -v`: This is Rakudo version 2019.11 built on MoarVM version 2019.11
* `zef list --installed` was empty before I started

**Comment by ugexe** [comment]
What if you use —fetch-degree=1 ?

Also note zef list —installed cannot be empty if zef is installed.

**Comment by ugexe** [comment]
Also, if zef list —installed is really empty (no old versions of zef you didn’t know about in e.g. ~/.perl6) it seems like a possible Rakudo bug since the check is just

method fetch-matcher($url) { $ = $url.lc.starts-with('http://' | 'https://') }

**Comment by dakkar** [comment]
ok, I have `rm -rf` both `~/.perl6` and the `share/perl6/site/` directory (under `rakudobrew`).
then `rakudobrew build-zef`, so I see this:
```
$ zef list --installed
===> Found via /home/dakkar/src/rakudobrew/versions/moar-2019.11/install/share/perl6/site
zef:ver<0.8.2>:auth<github:ugexe>:api<0>
===> Found via /home/dakkar/src/rakudobrew/versions/moar-2019.11/install/share/perl6/core
CORE:ver<6.d>:auth<perl>
```

then `zef install App::Prove6 Cro Grammar::Debugger Log::Timeline Test::META p6doc` worked.

So: either it's more random than I thought, or there were some leftovers from a previous installation.
I'm pretty sure I had the problem on a machine where I had just built rakudo 2019.11 for the first time, no previous traces of it, but maybe I was confused. I'll close this now, and if it happens again, I'll re-open it.
