### ISSUE TITLE
rakudobrew build zef fails on Windows 10

### ISSUE THREAD

**Issue by rubiot** [ugexe/zef#333]
rakudobrew build zef fails on Windows 10

## Context
Build fails.

## Expected Behavior
zef building OK.

## Actual Behavior
Fails with the following output:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>rakudobrew build zef
Your branch is up to date with 'origin/master'.
===> Testing: zef:ver<0.8.2>:auth<github:ugexe>:api<0>
[zef] Can't load TAP::Parser: TAP/Parser/Iterator/Stream.pm did not return a true value at C:/tools/Strawberry/perl/lib/TAP/Parser/SourceHandler/File.pm line 7.
[zef] BEGIN failed--compilation aborted at C:/tools/Strawberry/perl/lib/TAP/Parser/SourceHandler/File.pm line 7.
[zef] Compilation failed in require at C:/tools/Strawberry/perl/lib/TAP/Parser.pm line 14.
[zef] BEGIN failed--compilation aborted at C:/tools/Strawberry/perl/lib/TAP/Parser.pm line 14.
[zef] Compilation failed in require at (eval 17) line 2.
[zef]  at C:/tools/Strawberry/perl/lib/App/Prove.pm line 546.
===> Testing [FAIL]: zef:ver<0.8.2>:auth<github:ugexe>:api<0>
Aborting due to test failure: zef:ver<0.8.2>:auth<github:ugexe>:api<0> (use --force-test to override)
Failed running C:\Users\rubio\rakudobrew\versions\moar-blead\install\bin\perl6.exe -Ilib bin/zef test . at C:/Users/rubio/rakudobrew/bin/../lib/Rakudobrew/Build.pm line 121.

```
## Steps to Reproduce
rakudobrew build zef

## Your Environment
Windows 10 1809

**Comment by ugexe** [comment]
It looks like your system's `prove` command is broken? Note the errors don't mention perl6/raku at all -- `C:/tools/Strawberry/perl/lib/App/Prove.pm line 546.` All zef does is call `prove $some-options`

You can run with `--/prove` command to disable using that, but unfortunately I can't help you configure your system to have `prove` work correctly. zef certainly works in windows as shown [here](https://ci.appveyor.com/project/ugexe/zef/branch/master)

**Comment by ugexe** [comment]
Please see https://github.com/ugexe/zef/issues/326 with other instructions on how to avoid this

**Comment by rubiot** [comment]
Thanks, that was it. `cpan install TAP::Parser` fixed it.
