### ISSUE TITLE
zef debian stretch installation

### ISSUE THREAD

**Issue by cjaburto** [ugexe/zef#335]
hi, im trying do the installation but, it askme for some json file.

`
 perl6 -I. bin/zef install . 
`

the message is
`
===SORRY!===
Failed to find the zef config file at: /root/.config/zef/config.json, /root/resources/config.json
`

i cant find info about it.
hope it helps

thanks in advance.

**Comment by cjaburto** [comment]
> hi, im trying do the installation but, it askme for some json file.
> 
> `perl6 -I. bin/zef install . `
> 
> the message is
> `===SORRY!=== Failed to find the zef config file at: /root/.config/zef/config.json, /root/resources/config.json`
> 
> i cant find info about it.
> hope it helps
> 
> thanks in advance.

i guess is not supported or some. like that?
buster installation do everything. well whatever.

**Comment by ugexe** [comment]
What is the output of `perl6 -v`?
