### ISSUE TITLE
Vague error message after installing from nxadm/rakudo-pkg

### ISSUE THREAD

**Issue by littlebenlittle** [ugexe/zef#338]
## Context

Full disclosure: I'm not sure if this an issue with `zef` iself or a problem with the way I installed it. Either way, the result is a mostly unhelpful error message and no debug information with the `--debug` flag.

This is the content of my `Dockerfile`:

```
FROM debian:10

RUN apt-get update && apt-get install -y gpg ca-certificates \
 && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61 \
 && echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs stretch main" | tee -a /etc/apt/sources.list.d/rakudo-pkg.list \
 && apt-get update && apt-get install rakudo-pkg \
 && ln -s /opt/rakudo-pkg/bin/perl6 /usr/bin/perl6 \
 && ln -s /opt/rakudo-pkg/bin/raku /usr/bin/raku \
 && ln -s /opt/rakudo-pkg/bin/nqp /usr/bin/nqp \
 && ln -s /opt/rakudo-pkg/bin/moar /usr/bin/moar \
 && ln -s /opt/rakudo-pkg/bin/zef /usr/bin/zef
```

The command I am using to start the container:  (Note the `$HOME/*` directories already exist, otherwise docker creates them with root as owner, messing up the permissions)

```
docker run -it --rm $(id -u) \
    --workdir /work \
    --volume  $PWD:/work \
    --volume  $HOME/.raku:/home/raku/.raku \
    --volume  $HOME/.zef:/home/raku/.zef \
    --volume  $HOME/.perl6:/home/raku/.perl6 \
    benlittle6/rakudo
```

## Expected Behavior

From this point, I expect that I should be able to use `zef` as I normally would. In lieu of that, I would expect to see error or debug messages pointing to the underlying cause.

## Actual Behavior

When running `zef install *` where `*` is any package (`JSON::Tiny` for example), or when running `zef update`, `zef list`, or `zef smoke`, the following error occurs:

```
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
!!!> Failed to update cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
!!!> Failed to update cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updating cpan mirror: git://github.com/ugexe/Perl6-ecosystems.git
!!!> Failed to update cpan mirror: git://github.com/ugexe/Perl6-ecosystems.git
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
!!!> Failed to update p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updating p6c mirror: git://github.com/ugexe/Perl6-ecosystems.git
!!!> Failed to update p6c mirror: git://github.com/ugexe/Perl6-ecosystems.git
===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
!!!> Failed to update p6c mirror: http://ecosystem-api.p6c.org/projects1.json
```

## Steps to Reproduce

Either build or pull the docker image described above and run any of the commands. I've created a script that runs all of the `zef` subcommands: https://gist.github.com/littlebenlittle/2ccb293a97ca3edfd9ad74a83dc478e7

Here is the output I am getting: https://gist.github.com/littlebenlittle/ad5ab3e99a243ff6ac13f255e4799c84

## Your Environment

```
I have no name!@1031f10ab4ed:/work$ perl6 -v
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
```

```
I have no name!@1031f10ab4ed:/work$ zef list --installed
===> Found via /opt/rakudo-pkg/share/perl6/core
CORE:ver<6.d>:auth<perl>
zef:ver<0.8.3>:auth<github:ugexe>:api<0>
```

**Comment by niner** [comment]
Apparently zef simply cannot access the network from your container and arguably it tells you so.

**Comment by littlebenlittle** [comment]
But there's no indication as to why it cannot access those resources. Other container processes can access the network (`ping` for example).

**Comment by littlebenlittle** [comment]
This issue is not present on the master branch, leading me to believe this an issue with `nxadm/rakudo-pkg` and not `zef`.

**Comment by littlebenlittle** [comment]
So after much digging, this is indeed a `zef` "problem". Here is [the offending line](https://github.com/ugexe/zef/blob/e77560688e6a5508b476bd9dba013523aa695b15/lib/Zef/Repository/Ecosystems.pm6#L42). The `try` statement prefix is suppressing the somewhat more actionable error message:

```
===> Searching for: JSON::Tiny
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
!!!> Failed to update cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
!!!> Failed to update p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
Enabled fetching backends [path] don't understand https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
You may need to configure one of the following backends, or install its underlying software - [git curl wget pswebrequest]
```

**Comment by ugexe** [comment]
Could you instead add the note inside of a `CATCH` inside of this `try` block https://github.com/ugexe/zef/blob/e77560688e6a5508b476bd9dba013523aa695b15/lib/Zef/Repository/Ecosystems.pm6#L42 ? Various other `Zef::*` aggregators use a similar `die` pattern to what is changed in this PR, so it would be best to not change that without changing it everywhere else (which should probably themselves use `$logger.emit(...)` instead of `note`/`die`)
