### ISSUE TITLE
git path psunzip failure in Windows 7, but not 10

### ISSUE THREAD

**Issue by ToddAndMargo** [ugexe/zef#341]
Windows 7, x64 SP1
RakudoStar-2020.01.01-win-x86_64-(JIT).msi
Git-2.24.0.2-64-bit.exe
Note: works in Windows 10-1909, x64

>zef install OAuth2::Client::Google
===> Searching for: OAuth2::Client::Google

Enabled extracting backends [git path psunzip] don't understand C:\Users\todd/.zef/tmp\1585022838.2848.5555.088006717173\OAuth2-Client-Google-0.1.1.tar.gz

**Comment by Tyil** [comment]
That error also included a helpful message of what it could use to handle this:

```
You may need to configure one of the following backends, or install its
underlying software - [tar p5tar unzip]
```

Have you tried installing any of those things?

**Comment by ToddAndMargo** [comment]
Could not figure out how to do that.  But as far as I can tell, comparing W10 and W7's C:\Program Files\Git\usr\bin, they are identical.  Neither has a p5tar.

C:\Program Files\Git\usr\bin>ls | grep -i tar
gpgtar.exe
start
tar.exe

C:\Program Files\Git\usr\bin>ls | grep -i zip
bunzip2.exe
bzip2.exe
bzip2recover.exe
funzip.exe
gunzip
gzip.exe
unzip.exe
unzipsfx.exe
zipgrep
zipinfo.exe

**Comment by ugexe** [comment]
They are clearly not identical. They share the fact that neither lists a `p5tar` (which requires perl, but is besides the point) but that isn't quite what identical means. Clearly there is a `tar` listed in one of those outputs and that corresponds directly to the messages you are seeing.

I can not advise you on how to install `tar` on windows. Personally I would use something like `chocolately` to install it but explaining this is outside the scope of this issue tracker.

**Comment by ToddAndMargo** [comment]
Tar is installed on both of them. I did a system wide search on both OS'es for tar and they both contain the same tar in the same location.  Would you like a side by side comparision?

**Comment by ToddAndMargo** [comment]
Okay, I have a fix (workaround?) for this.  Windows 10 works without this:
--> <win><r> sysdm.cpl
  --> Advanced (tab at the top)
   --> Enviromental Variables (button, lower right)
    --> Path, Edit, add to the end
              ;C:\Program Files\Git\usr\bin
This should done by the installer at the same time it is adding raku to the path

**Comment by Tyil** [comment]
On Thu, Apr 09, 2020 at 03:39:41AM -0700, ToddAndMargo wrote:
> Okay, I have a fix (workaround?) for this.  Windows 10 works without this:
> --> <win><r> sysdm.cpl
>   --> Advanced (tab at the top)
>    --> Enviromental Variables (button, lower right)
>     --> Path, Edit, add to the end
>               ;C:\Program Files\Git\usr\bin
> This should done by the installer at the same time it is adding raku to the path
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ugexe/zef/issues/341#issuecomment-611459217

That doesn't seem like a thing for Raku or Zef to do, though. That looks to be
Git related, if anything.

-- 
With kind regards,

Patrick Spek


www:  https://www.tyil.nl/
mail: p.spek@tyil.nl
pgp:  1660 F6A2 DFA7 5347 322A  4DC0 7A6A C285 E2D9 8827

social: https://soc.fglt.nl/tyil
git:    https://home.tyil.nl/git
