### ISSUE TITLE
Install zef using homebrew

### ISSUE THREAD

**Issue by luolong** [ugexe/zef#347]
As a brand new Perl6/Raku user I am always a little surprised that while all Rakudo resources talk about using Zef package manager, the _state of the art_ of installing a package manager for Rakudo is essentially what amounts to a "manual install".

Every time I install Zef by cloning a repository from Github, I feel a little dirty inside.

## Context

Beginners curious about a language are interested in the whole experience and having essential language package managers installable 

## Expected Behavior

I would have expected that installing rakudo, would have installed zef as well, but even lacking that, I would have expected that  typing `brew install zef` should install Zef on my box.

**Comment by ankane** [comment]
Was just looking for this and found it's included in the Rakudo Star formula (fwiw).

```sh
brew install rakudo-star
```

**Comment by luolong** [comment]
Yes, this seems to have been resolved a while ago.
