### ISSUE TITLE
Dependency installation fails with multiple dependencies.

### ISSUE THREAD

**Issue by finanalyst** [ugexe/zef#351]
Failure to install Linenoise after a new install of Rakudo. Problem occurs when installing Library::Make

zef correctly installed each dependency separately.

(Same problem with ReadLine, but different dependencies)

## Command Line output
```
$ zef install Linenoise
===> Searching for: Linenoise
===> Searching for missing dependencies: LibraryMake
===> Searching for missing dependencies: Shell::Command
===> Searching for missing dependencies: File::Which, File::Find
===> Fetching [FAIL]: LibraryMake:ver<1.0.0>:auth<github:retupmoca> from git://github.com/retupmoca/P6-LibraryMake.git
Aborting due to fetch failure: LibraryMake:ver<1.0.0>:auth<github:retupmoca> (use --force-fetch to override)
richard@gandalf:~$ zef install File::Which
===> Searching for: File::Which
===> Testing: File::Which:ver<1.0.1>
[File::Which] # Found perl6 at '/opt/rakudo-pkg/bin/perl6'
[File::Which] # Found perl6 at '/opt/rakudo-pkg/bin/perl6' using whence
===> Testing [OK] for File::Which:ver<1.0.1>
===> Installing: File::Which:ver<1.0.1>
richard@gandalf:~$ zef install File::Find
===> Searching for: File::Find
===> Testing: File::Find:ver<0.1>
===> Testing [OK] for File::Find:ver<0.1>
===> Installing: File::Find:ver<0.1>
richard@gandalf:~$ zef install Shell::Command
===> Searching for: Shell::Command
===> Testing: Shell::Command
===> Testing [OK] for Shell::Command
===> Installing: Shell::Command
richard@gandalf:~$ zef install LibraryMake
===> Searching for: LibraryMake
===> Testing: LibraryMake:ver<1.0.0>:auth<github:retupmoca>
===> Testing [OK] for LibraryMake:ver<1.0.0>:auth<github:retupmoca>
===> Installing: LibraryMake:ver<1.0.0>:auth<github:retupmoca>
```
OS: ubuntu 18.04
after - sudo apt install rakudo-pkg

**Comment by niner** [comment]
Is the error actually reproducible? A fetch failure could be a simple 
networking hickup or a temporary issue on github.

**Comment by finanalyst** [comment]
This has happened to me quite regularly. I thought that it might be a fetch failure, but it does seem to occur when there is a dependency tree. In this case, I tried both `zef install ReadLine` and `zef install Linenoise` and got the same sort of error, but for different dependency trees.

Once Linenoise was successfully installed, the ReadLine installation failed at a different point. But since I don't need both Linenoise and ReadLine, I stopped investigating Linenoise.

I also have a directory `rakumods` with a single META6.json file, which I use to load all the modules I use, rather than the Rakudo Star modules, eg. `cd rakumods;; zef install .` zef generates errors on several modules. 

(Actually it would be nice to be able to run zef on a standard list in a file, eg, `zef install --filelist=/home/me/rakumods.json` or similar but that;s not the issue here)

But since zef sometimes works on multiple dependencies, I cant seem to duplicate the problem consistently.

**Comment by ugexe** [comment]
You might want to try with `--fetch-degree=1` so it does not try to fetch multiple repos at once. Your network might not like it, github rate limiting might not like you for some reason, but either way it seems like a fetch/networking issue. It almost certainly must be particular to your situation since I install tens of modules with varying degrees of dependency depth weekly (for years), and Blin regularly runs the entire ecosystem without regularly encountering such an issue regularly.

**Comment by finanalyst** [comment]
OK
