### ISSUE TITLE
zef don't understand http://www.cpan.org/authors/id/T/TI/TIMOTIMO/Perl6/JSON-Fast-0.10.tar.gz 

### ISSUE THREAD

**Issue by melezhik** [ugexe/zef#352]
## Context
 zef install PDF

## Expected Behavior
it should install without issues

## Actual Behavior
it fails with error `don't understand http://www.cpan.org/authors/id/T/TI/TIMOTIMO/Perl6/JSON-Fast-0.10.tar.gz `

## Steps to Reproduce

http://rakudist.raku.org/sparky/report/debian/147

## Your Environment

See http://rakudist.raku.org/sparky/report/debian/147

---

Interesting the very next build on the _same_ environment succeeds (nothing's changed since the failure ) - http://rakudist.raku.org/sparky/report/debian/148

If it's a sporadic failure ( due to temporary network issue or something ) output from zef still does not give good details of what has happened.

**Comment by ugexe** [comment]
I’m not sure what other diagnosis zef can give you. The check for if e.g. curl understands a url is pretty simple https://github.com/ugexe/zef/blob/0414984b70c401114e3e84c48cc7d342c8af3d83/lib/Zef/Service/Shell/curl.pm6#L4

**Comment by melezhik** [comment]
So, do I. But what bothers me mos  that the same test succeeds in the second attempt, I have no idea  _why_ the first test failed.

**Comment by ugexe** [comment]
I’d guess some rakudo bug involving optimization with the junction or the ‘$ =‘

**Comment by melezhik** [comment]
yeah, is it a flickering bug?

**Comment by ugexe** [comment]
Well if it’s caused by a bad rakudo optimization then yes it would be sporadic

**Comment by melezhik** [comment]
worth to create a ticket to Rakudo?

**Comment by ugexe** [comment]
While I think it’s a rakudo bug, I’m not sure what your bug report would say. “zef randomly doesn’t work” isn’t really enough for anyone to make an educated guess, and it’s not reproducible enough that someone is likely to both get the error *and* have whatever debugging mechanisms in place to understand what happened.

**Comment by melezhik** [comment]
Ok, Nick. you can close this one then. Thank you.

**Comment by melezhik** [comment]
Nick. The error continues on and off. http://rakudist.raku.org/sparky/report/debian/179

I am prepared to say that it could be caused by some none zef related factors, but how can I get more details from zef itself?

The weird thing is if I run a following build it usually succeeds.

**Comment by ugexe** [comment]
No clue... but what other details could it give you? Its telling your `$url.lc.starts-with('http://' | 'https://')` doesn't match... naturally zef can't tell you why rakudo isn't matching. And yes doing it again will usually succeed because its non-deterministic.

**Comment by melezhik** [comment]
could it be memomy/CPU consumption? i am not positive but it happens to modules with quite a few deoendencies when zef takesca lot of system resources to build a tree? I guess this behaviour could be managed by respected zef options, when we define the depth of dependency tree to be processed. I am not sure though. just a thoughts.

**Comment by ugexe** [comment]
Well I'd never add an option to process only part of a dependency tree... especially to work around a bug in something else.

**Comment by ugexe** [comment]
And yes it will be more likely to happen with more dependencies... because it does more comparisons.

**Comment by ugexe** [comment]
If you want to experiment you could try to change that check to `$url.lc.starts-with('http://') || $url.lc.starts-with('https://')` to see if you get the same failure rate. If that works around the issue then we can make that change, and we'd have a better idea of the cause. If that doesn't affect the failure rate maybe get rid of the `$ =`, get rid of the `.lc`, or mark `$url is rw`.

**Comment by melezhik** [comment]
do you mean I have to patch zef source code? if so you could make changes
in zef branch and I'd tweak sparrow scenario to install zef from that
branch.

https://github.com/melezhik/sparrow6-rakudo-install/blob/3600edf8288ce27ad2f6afb4fc6096c743b9cd7e/lib/Sparrow6/Rakudo/Install.pm6#L140

**Comment by melezhik** [comment]
so, git-scm function accepts branch name as an optional input parameter.

**Comment by melezhik** [comment]
interesting ... the issue has not seen recently.

I would still blame it on intermittent CPAN mirros accessibility error. Could it be that `zef` just does not handle such an errors and does not produce a proper output?

**Comment by ugexe** [comment]
The error can only be produced by the method shown earlier returning non-true. Connection won’t even be made until that check returns true.

**Comment by JJ** [comment]
I have been checking this out, because the error continues, and I'm kinda seeing where Rakudo might be erroring. There are two definitions of fetch-matcher, one public and the other private:

https://github.com/ugexe/zef/blob/602c54f1069631fd527473f4028451e5c47bc42c/lib/Zef/Fetch.rakumod#L73-L82

They have different signatures. Notably, they return different types: one Bool, the other returns array of `Fetcher`. Wonder why they are called the same (the second could be called `fetch-matchers`, for instance, since it returns an array, un plural). But the problem is not there. It might be here:

https://github.com/ugexe/zef/blob/602c54f1069631fd527473f4028451e5c47bc42c/lib/Zef/Fetch.rakumod#L88

This is clearly intended for the private version, as far as I can tell. But while namespaces for private and public methods are kept separate, is that true also for caches? Anyway, I'm going to follow my nose here and propose a change along those lines.
