### ISSUE TITLE
Incorrect? behavior of native dependencies

### ISSUE THREAD

**Issue by antoniogamiz** [ugexe/zef#357]
## Context

I have described this issue [here](https://github.com/Raku/Documentable/issues/96). I am trying to specify native dependencies for `Documentable` (node, perl, etc).

## Expected Behavior

`zef` should be able to recognize these dependencies (because they are indeed installed)

## Actual Behavior

`zef install .` fails due to unmet dependencies.

## Steps to Reproduce

Create a simple module and add
~~~json
  "depends": [
    "node:from<native>",
    "perl:from<native>",
  ],
~~~
to the `META6.json` file.

## Your Environment

* perl6 -v
~~~
This is Rakudo version 2020.06 built on MoarVM version 2020.06
implementing Raku 6.d.
~~~
* zef list --installed
~~~
===> Found via /home/antonio/.rakudobrew/versions/moar-2020.06/install/share/perl6/core
CORE:ver<6.d>:auth<perl>
===> Found via /home/antonio/.rakudobrew/versions/moar-2020.06/install/share/perl6/site
Digest:ver<0.3.4>:auth<Lucien Grondin>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Which:ver<1.0.1>
JSON::Class:ver<0.0.14>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.10>
JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::Unmarshal:ver<0.08>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.9.0>:auth<github:jonathanstowe>:api<1.0>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
Shell::Command
Temp::Path:ver<1.001007>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
Testo:ver<1.003006>
URI:ver<0.3.0>
zef:ver<0.8.5>:auth<github:ugexe>:api<0>
~~~

**Comment by niner** [comment]
Does Documentable really need a libnode.so? Is there even such a thing? I can understand zef not finding libperl.so, as that's usually installed into a non-standard location.
Or did you actually mean `"node:from<bin>"`?
It's possible, that zef doesn't understand this stringified form yet. But then it does support `{"name": "node", "from": "bin"}`

**Comment by antoniogamiz** [comment]
Oh, I think `bin` is the solution. I will try it and comment.

**Comment by antoniogamiz** [comment]
Yep, it was that. Thanks a lot, docs does not cover these arguments well enough I think...
