### ISSUE TITLE
Tar library

### ISSUE THREAD

**Issue by nu8** [ugexe/zef#362]
When encountering a Tar file, currently Zef tries to run a Tar executable:

https://github.com/ugexe/zef/blob/cb15ffc9be8a16b2e84af62ec48a37c1b4f3b564/lib/Zef/Service/Shell/tar.pm6#L11

or tries to run Perl 5 executable:

https://github.com/ugexe/zef/blob/cb15ffc9/resources/scripts/perl5tar.pl

it might be better to call a Raku library, instead of calling an executable for
this purpose. It seems some are available:

https://modules.raku.org/search?q=libarchive

**Comment by ugexe** [comment]
You should explain why it might it be better... because while I agree its nice to dog food our stuff, I also don't think its much value. We don't really want to deal with native dependency failures in zef, so for libarchive thats a hard no for core inclusion (although anyone feel free to write some plugin that zef can install, and then would use after editing zef config).

Pure raku tar extraction that lived in this repo would be acceptable, and indeed @tony-o has written code to serve that purpose. But without raku gzip decompression it is pointless to bring into the zef code base. If someone wants to be a hero please write a pure raku `Zef::Utils::Decompress::gzip(...)`.

**Comment by nu8** [comment]
these both seems to handle gzip:

https://github.com/CurtTilmes/perl6-libarchive
https://github.com/frithnanth/perl6-Archive-Libarchive

**Comment by ugexe** [comment]
I thought I made it pretty clear that only pure Raku solutions would be acceptable in core zef, and nativecall stuff is a hard no.

**Comment by ugexe** [comment]
Please explain why it would be better. I asked earlier but you must have missed it?

**Comment by nu8** [comment]
Dude what is your problem? I have interacted with you a few times over the last year or so, and every single time you find some way to be a jerk. Why do you have to talk to people like that?

I am not that knowledgeable with Raku. But in general its better to avoid calling executables because firstly it adds overhead versus a native solution, and secondly not all systems are guaranteed to even have a Tar executable. For example some Windows versions. So it would be better if an executable must be called, to bundle it with the Raku distribution, or perhaps to modify the PATH to where Tar is likely to be found (`/usr/bin` Linux, `C:\Windows\System32` Windows).

**Comment by niner** [comment]
@nu8 quite frankly, the only unacceptable behaviour I see **in this issue** is your personal attack. ugexe did explain why your suggestion is not a good idea for zef's default, while also pointing out that it'd be perfectly acceptable as a plugin.

Personally I'd like to know how depending on libarchive would be better than depending on finding a tar or perl executable. My openSUSE box doesn't even have a libarchive installed. It's not a part of the default installation and the system works perfectly fine without it. Arguably it will be hard to find any UNIX system that doesn't have a tar installed. As for Windows, it usually doesn't ship any of tar, perl or libarchive. But perl is at least required to compile rakudo, so there's a chance that at least that is available. Using libarchive instead wouldn't buy us anything, would it?

**Comment by nu8** [comment]
@niner why dont we just call executables for everything then? Why not just use
shell scripts for everything?
