### ISSUE TITLE
`zef --contained install` fails for modules that explicitly depend on core modules

### ISSUE THREAD

**Issue by codesections** [ugexe/zef#367]
## Context
When a module explicitly lists one of the [core modules](https://docs.raku.org/language/modules-core) as a dependency in its META6.json file, `zef --contained install` cannot install the core module, which causes the entire contained install to fail.  This isn't a big deal – removing the explicit dependency from the META6.json file fixes it while still allowing the installed module to function.  But I thought you might appreciate the bug report, especially given the `BETA` note.

## Expected Behavior
`zef --contained install` should install the module.

## Actual Behavior
`zef --contained install` fails with an error.

## Steps to Reproduce
Perform a contained install of any module that explicitly depends on a core module.  For example:

```sh
 $  zef  --contained --debug install 'Pod::Weave:auth<github:codesections>:ver<0.0.2>'
===> Searching for: Pod::Weave:ver<0.0.2>:auth<github:codesections>
===> Found: Pod::Weave:ver<0.0.2>:auth<github:codesections> [via Zef::Repository::LocalCache]
===> Dependencies: Pod::Literate, Pod::Load, Pod::To::HTML, Pod::To::Markdown, Pod::To::Text
===> Searching for missing dependencies: Pod::Literate:auth<github:codesections>, Pod::Load:ver<0.5.2>, Pod::To::HTML:auth<github:Raku>, Pod::To::Markdown:ver<v0.1.4>, Pod::To::Text
===> Failed to find dependencies: Pod::To::Text
Failed to resolve some missing dependencies
```

## Your Environment

* perl6 -v: 
```
This is Rakudo version 2020.07 built on MoarVM version 2020.07
implementing Raku 6.d.
```
* zef list --installed

```
===> Found via /home/$user/.raku
App::Mi6:ver<1.0.3>:auth<cpan:SKAJI>
CPAN::Uploader::Tiny:ver<0.0.6>:auth<cpan:SKAJI>
Digest:ver<0.3.4>:auth<Lucien Grondin>
Documentable:ver<2.0.1>:auth<github:Raku>:api<1>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Temp:ver<0.0.8>
File::Which:ver<1.0.1>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
HTML::Escape:ver<0.0.1>
HTTP::Tinyish:ver<0.1.4>:auth<cpan:SKAJI>
JSON::Class:ver<0.0.14>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.15>
JSON::Fast:ver<0.9.18>
JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::Pretty:ver<0.1.0>:auth<github:FROGGS>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.9.0>:auth<github:jonathanstowe>:api<1.0>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
Markdown::Grammar:ver<0.0.1>
Perl6::TypeGraph:ver<2.1.3>:auth<github:antoniogamiz>:api<2>
Pluggable:ver<0.5>:auth<github:tony-o>
Pod::From::Cache:ver<0.2>:auth<github:finanalyst>
Pod::Literate:ver<0.0.2>:auth<github:codesections>
Pod::Load:ver<0.5.2>
Pod::Load:ver<0.5.4>
Pod::Tangle:ver<0.0.1>:auth<github:codesections>
Pod::Tangle:ver<0.0.2>:auth<cpan:CODESECTS>
Pod::To::HTML:ver<0.7.1>:auth<github:Raku>
Pod::To::Markdown:ver<v.0.1.4>
Pod::Utilities:ver<0.0.1>
Shell::Command
TAP:ver<0.1.0>
Temp::Path:ver<1.001007>
Template::Mustache:ver<1.2.2>:auth<github:softmoth>
Terminal::ANSIColor:ver<0.5>
Terminal::Spinners:ver<1.5.0>:auth<github:ryn1x>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
Test::Output:ver<1.001002>
Testo:ver<1.003006>
Text::Markdown:ver<1.1.0>:auth<github:retupmoca>
URI:ver<0.3.0>
cmark::Simple:ver<0.0.2>:auth<github:JJ>
zef:ver<0.8.5>:auth<github:ugexe>:api<0>
===> Found via /opt/rakudo-pkg/share/perl6/core
CORE:ver<6.d>:auth<perl>
zef:ver<0.8.5>:auth<github:ugexe>:api<0>
```

**Comment by ugexe** [comment]
You could try adding that module here -- https://github.com/ugexe/zef/blob/cb15ffc9be8a16b2e84af62ec48a37c1b4f3b564/lib/Zef/Client.pm6#L64 and see if that fixes it.

Technically pure-raku modules could be reinstalled from a `CompUnit::Repository::(FileSystem|Installation)` like how https://github.com/Raku/roast/blob/fdcc5a283c15c81ed5c0f818299afe9f4cc57ebe/S11-repository/cur-candidates.t#L130 queries a repo for a distribution, and then passes it to another for installation. I think I was exploring that idea in this commit https://github.com/ugexe/zef/commit/63782093f6068329f89b93c0d1d8d950e2ae7c51 But also note the CORE distribution (what the grouping of raku modules that get installed by default is called) [doesn't get versioned](https://github.com/rakudo/rakudo/blob/c5cffd40dd42a44d97fe315216725238264392cc/tools/build/install-core-dist.raku#L41) beyond e.g. `6.d`, when they really need to be incrementally versioned to more safely do this.
