### ISSUE TITLE
zef does not install (recently) updated version.

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#368]
## Context

[`ake` was recently upgraded and released](https://github.com/Raku/ake/issues/32), so I tried to install it; it went from 0.0.3 to 0.1.0

1. `zef install ake`

```
All candidates are currently installed
No reason to proceed. Use --force-install to continue anyway
```
OK, maybe repos have not been updated yet

2. `zef search ake`

```
...
6 |Zef::Repository::Ecosystems<p6c> |ake:ver<0.1.0>:auth<Jonathan Scott Duff <duff@pobox.com>>  
```

OK, so it's there. Also, new version of repos has been downloaded. `zef install ake`, same thing.

3. `zef update`: Repo indices are updated. `zef install ake`, same thing.

Finally, `zef install "ake:ver<0.1.0>" did the job. 

## Expected Behavior

I expected 0.1.0 to be installed as soon as it was detected in the repositories.

## Actual Behavior

It had to be installed explicitly, despite

```
> say v0.0.3 cmp v0.1.0
Less
```

## Steps to Reproduce

Indicated above

## Your Environment

Raku 2020.08.2, zef 0.8.5

Installed (after installation of the new version)
```
===> Found via /home/jmerelo/.rakudobrew/moar-2020.08.2/install/share/perl6/site
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Temp:ver<0.0.8>
JSON::Class:ver<0.0.14>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.15>
JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::Unmarshal:ver<0.08>
License::SPDX:ver<3.9.0>:auth<github:jonathanstowe>:api<1.0>
META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
Perl6::TypeGraph:ver<2.1.3>:auth<github:antoniogamiz>:api<2>
Stats:ver<0.0.6>:auth<github:MattOates>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
URI:ver<0.3.0>
ake:ver<0.0.3>:auth<Jonathan Scott Duff <duff@pobox.com>>
ake:ver<0.1.0>:auth<Jonathan Scott Duff <duff@pobox.com>>
zef:ver<0.8.5>:auth<github:ugexe>:api<0>
===> Found via /home/jmerelo/.rakudobrew/moar-2020.08.2/install/share/perl6/core
CORE:ver<6.d>:auth<perl>
```

**Comment by ugexe** [comment]
The issue template explicitly asks you to list zef installed —list

**Comment by ugexe** [comment]
You are asking for `aka`, which is the same as `ake:ver<*>`. Indeed `ake:ver<*>` is already installed before you try to update to `:ver<0.1.0>` which you can verify via `use ake:ver<*>`, so the request to install `zef install ake` is already fulfilled. And naturally a request for `zef install "ake:ver<0.1.0>"` cannot be fullfilled by `ake:ver<0.0.3>`, so it has to go grab that specific version in that case. If you want to install the lastest version of a module without specifying a version/version-range that you already have installed you need to do `zef upgrade Foo` -- https://github.com/ugexe/zef/blob/cb15ffc9be8a16b2e84af62ec48a37c1b4f3b564/.travis.yml#L81-L82
