### ISSUE TITLE
zef test <module> differs from zef install --deps-only && prove6 --lib

### ISSUE THREAD

**Issue by finanalyst** [ugexe/zef#386]
In a Travis environment, `zef test .` fails, but 
`zef install --deps-only . && prove6 --lib` does not fail.

## Context
I am running tests using the docker file created by JJMerelo on Travis because it is used to run any new module placed in the Ecosystem.

Locally on my system, the module passes all tests.  Thus in my local directory `~/development/raku-pod-render/`
```
zef test .
===> Testing: Raku::Pod::Render:ver<3.6.2>:auth<github:finanalyst>
===> Testing [OK] for Raku::Pod::Render:ver<3.6.2>:auth<github:finanalyst>
```
However, when Raku::Pod::Render is installed as a dependency for another module, the docker test fails.

Further, `zef` is causing a failure and stating a reason that is not correct.

## Expected Behavior

`zef test .` and `zef install --deps-only . && prove6 --lib` should produce the same result, and `zef` should provide a reason for the failure that leads to an understanding of the failure.

## Actual Behavior

I have a test line in a standard test file, thus
```
use-ok 'Pod::To::MarkDown:auth<github:finanalyst>';
```
I have a file  
`lib/Pod/To/MarkDown.pm6`   
In the file I have the lines
```
use ProcessedPod;
unit class Pod::To::MarkDown:auth<github:finanalyst> is ProcessedPod;
```

I have in META6.json in '.' the lines:
```
"provides": {
    "Pod::Render::Exceptions": "lib/Pod/Render/Exceptions.pm6",
    "Pod::To::HTML2:auth<github:finanalyst>": "lib/Pod/To/HTML2.pm6",
    "Pod::To::HTML2::Mustache:auth<github:finanalyst>": "lib/Pod/To/HTML2.pm6",
    "Pod::To::MarkDown:auth<github:finanalyst>": "lib/Pod/To/MarkDown.pm6",
    "ProcessedPod": "lib/ProcessedPod.pm6",
    "ExtractPod": "lib/ExtractPod.pm6",
    "test-templates": "bin/test-templates",
    "InstallAtomHighlighter": "lib/InstallAtomHighlighter.pm6",
    "raku-pod-render-install-highlighter": "bin/raku-pod-render-install-highlighter"
  },
```
When I run the following
```
sudo docker run -t --user root --entrypoint="/bin/sh" -v /home/richard/development/raku-pod-render:/test jjmerelo/raku-test -c "zef install --deps-only . && prove6 --lib -v"
```
The output (truncating all but last dependency installation) is:
```
===> Installing: Pod::Load:ver<0.5.6>
1..1
ok 1 - ProcessedPod module can be use-d ok
t/000-sanity.t .......... ok
1..1
ok 1 - Pod::To::MarkDown:auth<github:finanalyst> module can be use-d ok
t/005-md-sanity.t ....... ok
ok 1 - Pod::To::HTML2:auth<github:finanalyst> module can be use-d ok
1..1
t/010-html-sanity.t ..... ok
1..1
ok 1 - ExtractPod module can be use-d ok
t/015-extract-sanity.t .. ok
All tests successful.
Files=4, Tests=4,  5 wallclock secs
Result: PASS
```
When I run
```
sudo docker run -t --user root -v /home/richard/development/raku-pod-render:/test jjmerelo/raku-test
```
The output fails, and is (again only showing after last install)
```
===> Installing: Pod::Load:ver<0.5.6>
===> Testing: Raku::Pod::Render:ver<3.6.2>:auth<github:finanalyst>
[Raku::Pod::Render] # Failed test 'Pod::To::MarkDown:auth<github:finanalyst> module can be use-d ok'
[Raku::Pod::Render] # at t/005-md-sanity.t line 3
[Raku::Pod::Render] # Could not find Pod::To::MarkDown:auth<github:finanalyst> in:
[Raku::Pod::Render] #     file#/test
[Raku::Pod::Render] #     inst#/root/.raku
[Raku::Pod::Render] #     inst#/home/raku/.raku/share/perl6/site
[Raku::Pod::Render] #     inst#/home/raku/.raku/share/perl6/vendor
[Raku::Pod::Render] #     inst#/home/raku/.raku/share/perl6/core
[Raku::Pod::Render] #     ap#
[Raku::Pod::Render] #     nqp#
[Raku::Pod::Render] #     perl5#
[Raku::Pod::Render] # 
[Raku::Pod::Render] # Please note that a 'META6.json' file was found in '.', of which the 'provides' section was used to determine if a dependency is available or not.  Perhaps you need to add 'Pod::To::MarkDown:auth<github:finanalyst>' in the <provides> section of that file?  Or need to specify a directory that does *not* have a 'META6.json' file?
[Raku::Pod::Render] # You failed 1 test of 1
[Raku::Pod::Render] # Failed test 'Pod::To::HTML2:auth<github:finanalyst> module can be use-d ok'
[Raku::Pod::Render] # at t/010-html-sanity.t line 3
[Raku::Pod::Render] # Could not find Pod::To::HTML2:auth<github:finanalyst> in:
[Raku::Pod::Render] #     file#/test
[Raku::Pod::Render] #     inst#/root/.raku
[Raku::Pod::Render] #     inst#/home/raku/.raku/share/perl6/site
[Raku::Pod::Render] #     inst#/home/raku/.raku/share/perl6/vendor
[Raku::Pod::Render] #     inst#/home/raku/.raku/share/perl6/core
[Raku::Pod::Render] #     ap#
[Raku::Pod::Render] #     nqp#
[Raku::Pod::Render] #     perl5#
[Raku::Pod::Render] # 
[Raku::Pod::Render] # Please note that a 'META6.json' file was found in '.', of which the 'provides' section was used to determine if a dependency is available or not.  Perhaps you need to add 'Pod::To::HTML2:auth<github:finanalyst>' in the <provides> section of that file?  Or need to specify a directory that does *not* have a 'META6.json' file?
[Raku::Pod::Render] # You failed 1 test of 1
===> Testing [FAIL]: Raku::Pod::Render:ver<3.6.2>:auth<github:finanalyst>
Aborting due to test failure: Raku::Pod::Render:ver<3.6.2>:auth<github:finanalyst> (use --force-test to override)
```
As you can see, `zef` is asserting that `META6.json` has been found but does not contain references to the required modules in 'provides', but the only META6.json file that can be seen by zef DOES have these module names.

## Steps to Reproduce

Raku::Pod::Render is at `https://github.com/finanalyst/raku-pod-render`, and the Travis file
has commands that allow for a successful install.
An unsuccessful install can be reproduced with the same Tavis file but using a module that has a META6.json file with 
```
depends: ["Raku::Pod::Render"]
```

Adding the debug flag only produced one extra line, that is:
```
[Raku::Pod::Render] Testing with plugin: Zef::Service::Shell::Test+{<anon|1>}
```

## Your Environment
JJMerelo's docker environment.

* raku -v
* zef list --installed

**Comment by ugexe** [comment]
> In a Travis environment, zef test . fails, but
> zef install --deps-only . && prove6 --lib does not fail.

Because they are not the same. `zef` does `-I.` while your other command presumably does `-Ilib`. These are not the same.

> As you can see, zef is asserting that META6.json has been found but does not contain references to the required modules in 'provides', but the only META6.json file that can be seen by zef DOES have these module names.

No, *rakudo* is asserting that. I'm pretty sure if you did `prove -e 'raku -I.' t/` it would fail too.

Including a `/lib` folder instead of the parent folder with the meta file is almost always the wrong thing to do, and you'll avoid a lot of problems by simply not using it if a meta file exists. In fact it will point out problems with your code that would occur during installation. In this case you are declaring e.g. auth in provides, which rakudo itself does not understand. The fact it happens to work with `/lib` is because it ignores what you are declaring that you expect to be there (by not even looking at the meta file) -- this wouldn't work once installed, and indeed using `-I.` instead of `-Ilib` catches this before it inevitably fails inside rakudo during precompilation of the installed files.

> zef test . and zef install --deps-only . && prove6 --lib should produce the same result, and zef should provide a reason for the failure that leads to an understanding of the failure.

zef is doing the correct thing, and given the error is from rakudo itself I think it did a pretty good job of explaining the problem. I don't believe it is documented anywhere that you can use `auth` in the provides section, so just don't do that.
