### ISSUE TITLE
A dependency specification with parentheses works for installing, but not from API

### ISSUE THREAD

**Issue by Altai-man** [ugexe/zef#392]
## Context

There is a module `CSS::Selector::To::XPath` with this in [dependencies](https://modules.raku.org/dist/CSS::Selector::To::XPath:cpan:WARRINGD/META6.json#L6):

```
    "depends"     : [ "CSS::Grammar:ver(v0.3.3+)", "CSS::Module::CSS3::Selectors", "XML" ],
```

Note it uses `CSS::Grammar:ver(v0.3.3+)` instead of `CSS::Grammar:ver<v0.3.3+>`.

It is a question whether this notation is correct or not to me, but if you try to install it, zef has no issues with reading this dependency:

```
zef install CSS::Selector::To::XPath
===> Searching for: CSS::Selector::To::XPath
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for missing dependencies: CSS::Module::CSS3::Selectors
===> Searching for missing dependencies: CSS::Grammar:ver<0.3.5+>
===> Testing: CSS::Grammar:ver<0.3.5>:auth<github:css-raku>
...
```

But if you try to utilize the `Zef::Distribution::DependencySpecification` API for it (in Blin), it is not accepted:

```
> Zef::Distribution::DependencySpecification.new('CSS::Gramma:ver<v0.0.3>').name
CSS::Gramma
> Zef::Distribution::DependencySpecification.new('CSS::Gramma:ver(v0.0.3)').name
(Any)
```

## Expected Behavior

Logically from my ignorant point of view, zef should either be confused about this notation and not accept it when doing `zef install` or it should handle the parentheses case in DependencySpecification, or there should be something completely different with a more correct approach towards reading the spec strings.

## Actual Behavior

Zef can install the module nicely, but an attempt to utilize the API for Blin purposes does not go too well.

## Steps to Reproduce

```
➜  ~ zef install CSS::Selector::To::XPath # installs the module
➜  ~ raku -e "use Zef::Distribution; say Zef::Distribution::DependencySpecification.new('CSS::Gramma:ver<v0.0.3+>').name"
CSS::Gramma
➜  ~ raku -e "use Zef::Distribution; say Zef::Distribution::DependencySpecification.new('CSS::Gramma:ver(v0.0.3+)').name"
(Any)
```

## Your Environment

* raku -v

>Welcome to Rakudo(tm) v2020.12.

* zef list --installed

```
➜  ~ zef list --installed
===> Found via /home/koto/.rakudobrew/versions/moar-2020.12/install/share/perl6/site
App::GPTrixie:ver<0.29>
Archive::Libarchive::Raw:ver<0.1.0>
Base64:ver<0.0.2>:auth<github:ugexe>
BitEnum:ver<0.5>:auth<github:CurtTilmes>:api<1>
Config::INI
Cro::Core:ver<0.8.4>
Cro::HTTP:ver<0.8.4>
Cro::TLS:ver<0.8.4>
Crypt::Random:ver<0.4.1>:auth<github:skinkade>
DateTime::Parse:ver<0.9.1>
Digest::HMAC:ver<1.0.2>:auth<github:retupmoca>
Digest::SHA256::Native:ver<0.03>
Digest:ver<0.3.4>:auth<Lucien Grondin>
Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
Encode:ver<0.0.3>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1.1>
File::Temp:ver<0.0.8>
File::Which:ver<1.0.1>
HTTP::HPACK:ver<0.9.2>
HTTP::Roles:ver<0.2.0>:auth<github:tony-o>
HTTP::Server::Async:ver<0.1.9>:auth<github:tony-o>
HTTP::Status:ver<0.0.1>
HTTP::UserAgent:ver<1.1.51>:auth<github:sergot>
IO::Capture::Simple:ver<v.0.0.1>
IO::Path::ChildSecure:ver<1.001011>
IO::Socket::Async::SSL:ver<0.7.6>:auth<jnthn>
IO::Socket::SSL:ver<0.0.2>:auth<github:sergot>
IRC::Client:ver<3.007011>
IRC::TextColor:ver<0.3.0>:auth<github:samcv>
JSON::Class:ver<0.0.15>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.15>
JSON::JWT:ver<1.0>:auth<github:retupmoca>
JSON::Marshal:ver<0.0.19>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::Unmarshal:ver<0.08>
LibCurl:ver<1.3>:auth<github:CurtTilmes>:api<1>
LibXML:ver<0.5.14>:auth<cpan:WARRINGD>
Libarchive:ver<0.1>:auth<github:CurtTilmes>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.11.0>:auth<github:jonathanstowe>:api<1.0>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
Lingua::Conjunction:ver<1.001001>
Log::Async:ver<0.0.7>
Log::Timeline:ver<0.3>
META6:ver<0.0.24>:auth<github:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
MeCab:ver<0.0.17>:auth<titsuki>
Method::Also:ver<0.0.5>:auth<cpan:ELIZABETH>
NativeHelpers::Callback:ver<0.1>
NativeLibs:ver<0.0.9>:auth<github:salortiz>
Number::Bytes::Human:ver<0.0.3>
Number::Denominate:ver<2.002001>
OO::Monitors:ver<1.1.1>
OpenSSL:ver<0.1.23>:auth<github:sergot>
Pakku::Meta:ver<0.0.3>:auth<github:hythm7>
Pakku::RecMan::Client:ver<0.0.2>:auth<github:hythm7>
Pakku::Spec:ver<0.0.1>:auth<github:hythm7>
Pakku:ver<pupa>:auth<github:hythm7>
Pastebin::Gist:ver<1.004002>
Retry:ver<0.0.4>:auth<github:hythm7>
SVG
SVG::Plot
Shell::Command
Spreadsheet::XLSX:ver<0.2.2>:auth<Edument>
Stats:ver<0.0.6>:auth<github:MattOates>
System::Query:ver<0.1.5>:auth<zef:tony-o>
Terminal::ANSIColor:ver<0.5>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
Test::Notice:ver<1.001003>
Test::Util::ServerPort:ver<0.0.2>:auth<github:jonathanstowe>:api<1.0>
Test::When:ver<1.001008>
Text::Diff::Sift4:ver<1.4.1>
URI:ver<0.3.0>
URL:ver<0.2.1>:api<0>
WWW:ver<1.005006>:auth<github:raku-community-modules>
Whateverable:ver<1.0.10>
XML::Writer
XML:ver<0.3.0>:auth<Timothy Totten>
ake:ver<0.1.0>:auth<Jonathan Scott Duff <duff@pobox.com>>
if:ver<0.1.1>:auth<github:FROGGS>
zef:ver<0.11.0>:auth<github:ugexe>:api<0>
===> Found via /home/koto/.rakudobrew/versions/moar-2020.12/install/share/perl6/core
CORE:ver<6.d>:auth<perl>
➜  ~ 
```

**Comment by ugexe** [comment]
Parens should not be allowed for declaring dependencies since it implies running arbitrary code just to build a dependency graph. `use Test:ver(say q|rm /foo/bar|)` works in code, but we don't want `"depends" : "use Test:ver(say q|rm /foo/bar|)"` to eval code.

zef installs despite `Zef::Distribution::DependencySpecification` not understanding the `:ver(...)` is because there is [another dependency](https://github.com/css-raku/CSS-Module-CSS3-Selectors-raku/blob/b6ec89207521f3ed8c5e6964da5b8a88087cb7ff/META6.json#L5) that uses the `:ver<...>` string

Currently zef [ignores dependencies](https://github.com/ugexe/zef/blob/0c153175eb7a3f491c64397f3222c17bf17488e2/lib/Zef/Distribution.rakumod#L161) it does not know how to parse, because zef is meant to be used with content that is assumed to be correct / validated. Perhaps something like a warning for what the `.grep(*.name)` filters, but on the other hand this normally would be caught by the author if they didn't also have another dependency using the correct dependency spec.

**Comment by ugexe** [comment]
It might be an improvement to get the dependency list in Blin from META6 data via something like `Zef::Distribution`
```
raku -I. -e '                                    \
    use Zef::Distribution;                       \
    my %meta = from-json("META6.json".IO.slurp); \
    my $dist = Zef::Distribution.new(|%meta);    \
    say $dist.depends-specs;                     \
    say $dist.test-depends-specs;                \
    say $dist.build-depends-specs;
'
```
which will give you the same behavior as zef (ignoring names it can't parse, parsing hash form dependencies, and parsing conditional logic dependencies like `Inline::Python` uses)

**Comment by Altai-man** [comment]
Thanks a lot for your insight! I reported the case to the module author.

Your suggestion related to building `Zef::Distribution` looks very promising, though a couple of seconds after I've got

```
Type check failed in binding to parameter '@!resources'; expected Positional but got Hash ({})
  in method TWEAK at /home/koto/.rakudobrew/versions/moar-2020.12/install/share/perl6/site/sources/C5229592186DF33515E5D1A8E5FF27E16D00D348 (Zef::Distribution) line 144
  in method new at /home/koto/.rakudobrew/versions/moar-2020.12/install/share/perl6/site/sources/C5229592186DF33515E5D1A8E5FF27E16D00D348 (Zef::Distribution) line 142
  in block  at bin/blin.p6 line 173
  in sub MAIN at bin/blin.p6 line 168
  in block <unit> at bin/blin.p6 line 16
```
for the `Farabi6` module (indeed https://github.com/azawawi/farabi6/blob/master/META6.json#L12), I suspect there will be more such modules, so it's a trade-off. Anyway, for the time being this can surely be closed.

**Comment by ugexe** [comment]
Ah yeah, zef prefixes such calls with `try`, and if it gets back `Nil` then it will ignore it (since we don't want something like searching for resources to be prevented by one bad module)

https://github.com/ugexe/zef/blob/0c153175eb7a3f491c64397f3222c17bf17488e2/lib/Zef/Repository/Ecosystems.rakumod#L227-L228

However if a distribution is throwing the error shown I wonder how installable they were in the first place (it kind of feels like if it worked then it was coincidental)
