### ISSUE TITLE
CPAN module refactoring and dependency resolution

### ISSUE THREAD

**Issue by dwarring** [ugexe/zef#395]
HarfBuzz:ver<0.0.2> included the class HarfBuzz::Font::FreeType.

The latest release HarfBuzz:ver<0.0.5>, does not inlcude this class, rather it's been factored
out into its own module HarfBuzz::Font::FreeType:v<0.0.1>

There's a third module HarfBuzz::Shaper::Cairo that has dependencies on HarfBuzz:ver<0.0.5> and HarfBuzz::Font::FreeType.

This leads to upgrade issues as described below.

## Context

To reproduce the issue:
```
zef install --force 'HarfBuzz:ver<0.0.2>' # so we've got this version installed
git clone https://github.com/harfbuzz-raku/HarfBuzz-Shaper-Cairo-raku
cd HarfBuzz-Shaper-Cairo-raku
zef --deps-only install .
# ===> Searching for missing dependencies: HarfBuzz::Shaper:ver<0.0.5+>
# ...
```

So it's not resolving HarfBuzz::Font::FreeType as a separate dependencies when there
is an older version of HarfBuzz that contains this class.

## Expected Behavior

HarfBuzz::Font::FreeType should be resolved as a distinct dependency?

## Actual Behavior

As above

## Steps to Reproduce

As above. I'll leave HarfBuzz:ver<0.0.2> up on CPAN for now

## Your Environment

* raku -v
Welcome to Rakudo(tm) v2020.12.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.12.
* zef list --installed

**Comment by ugexe** [comment]
You are installing `HarfBuzz:ver<0.0.2>`, which means you will already have `HarfBuzz::Font::FreeType` installed. Since v0.0.2 contains a module matching `HarfBuzz::Font::FreeType:ver<*>:api<*>:auth<>` there is no need to look for the dependency at all.

**Comment by tony-o** [comment]
The correct solution to your refactoring issue would be to specify the version requirement in your META6 of HarfBuzz and version your `HarfBuzz::Font::FreeType` appropriately (eg `"depends": ["HarfBuzz::Font::FreeType:ver<666+>"]` in your project and `"ver": "666"`)

**Comment by dwarring** [comment]
Installing as expected after Bumping HarfBuzz::Font::FreeType to v0.0.5 and depending on HarfBuzz::Font::FreeType:ver<0.0.5+>.
