### ISSUE TITLE
zef list command write strings to both STDOUT and STDERR

### ISSUE THREAD

**Issue by skaji** [ugexe/zef#397]
## Context

Because [the issue template](https://github.com/ugexe/zef/blob/master/.github/ISSUE_TEMPLATE.md) needs `zef list --installed`, I tried

```
❯ zef list --installed | pbcopy
```

But, currently `zef list` command write strings to both STDOUT (via `say`) and STDERR (via `note`), so I was not able to capture the whole output.
https://github.com/ugexe/zef/blob/0c153175eb7a3f491c64397f3222c17bf17488e2/lib/Zef/CLI.rakumod#L541-L545

I think `zef list` should write strings to either STDOUT or STDERR, not both.

## Expected Behavior

`zef list` write strings to either STDOUT or STDERR

## Actual Behavior

`zef list` write strings to both STDOUT and STDERR

## Steps to Reproduce

See "Context".

## Your Environment

* raku -v
    ```
    Welcome to Rakudo(tm) v2021.02.1.
    Implementing the Raku(tm) programming language v6.d.
    Built on MoarVM version 2021.02.
    ```
* zef list --installed
    ```
    ===> Found via /Users/skaji/env/rakuenv/versions/2021.02.1-01/share/perl6/site
    zef:ver<0.11.4>:auth<github:ugexe>:api<0>
    ===> Found via /Users/skaji/env/rakuenv/versions/2021.02.1-01/share/perl6/core
    CORE:ver<6.d>:auth<perl>
    ```

**Comment by tony-o** [comment]
Any reason `zef list --installed 2>&1 | pbcopy` won't work?

**Comment by skaji** [comment]
STDOUT has buffer, so we have lines with unexpected order.

```
❯ zef list --installed 2>&1 | pbcopy

❯ pbpaste
===> Found via /Users/skaji/env/rakuenv/versions/2021.02.1-01/share/perl6/site
zef:ver<0.11.4>:auth<github:ugexe>:api<0>
CORE:ver<6.d>:auth<perl>
===> Found via /Users/skaji/env/rakuenv/versions/2021.02.1-01/share/perl6/core
```

**Comment by ugexe** [comment]
Everywhere else uses `say "===> ..."` so from that aspect it makes sense to get rid of that `note`. I used note in this case though so users could get/pipe a list of module names to install without grepping away the `===>` lines, but maybe that isn't really that useful.
