### ISSUE TITLE
can't install Inline::Perl5 by zef

### ISSUE THREAD

**Issue by xiaoyafeng** [ugexe/zef#401]
C:\>zef install Inline::Perl5
===> Searching for: Inline::Perl5
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for missing dependencies: Distribution::Builder::MakeFromJSON:ver<0.6+>, perl:from<bin>
===> Failed to find dependencies: perl:from<bin>
Failed to resolve some missing dependencies
## Your Environment

* raku -v
C:\>raku -v
This is Rakudo version 2020.05.1 built on MoarVM version 2020.05
implementing Raku 6.d.
* zef list --installed
===> Found via C:\rakudo\share\perl6\core
CORE:ver<6.d>:auth<perl>
===> Found via C:\rakudo\share\perl6\site
App::Prove6:ver<0.0.12>:auth<cpan:LEONT>
DBIish:ver<0.5.19>
DateTime::Format
DateTime::Parse:ver<0.9.1>
Debugger::UI::CommandLine
Digest::MD5:ver<0.05>:auth<Cosimo Streppone>
Digest:ver<0.3.4>:auth<Lucien Grondin>
Encode:ver<0.0.3>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1>
File::Temp:ver<0.0.8>
File::Which:ver<1.0.1>
Getopt::Long:ver<0.1.6>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
Grammar::Profiler::Simple:ver<0.02>
HTTP::Easy:ver<1.1.0>
HTTP::Status:ver<0.0.1>
HTTP::UserAgent:ver<1.1.49>:auth<github:sergot>
IO::Capture::Simple
IO::Socket::SSL:ver<0.0.1>:auth<github:sergot>
JSON::Class:ver<0.0.14>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.10>
JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::RPC:ver<1.0.0>:auth<bbkr>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
LWP::Simple:ver<0.106>:auth<github:perl6>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.8.0>:auth<github:jonathanstowe>:api<1.0>
META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
NativeHelpers::Blob:ver<0.1.12>:auth<github:salortiz>
OO::Monitors:ver<1.1.1>
OpenSSL:ver<0.1.23>:auth<github:sergot>
PSGI:ver<1.2.0>
Perl6::TypeGraph:ver<2.1.2>:auth<github:antoniogamiz>:api<2>
Pod::Load:ver<0.5.5>
Pod::To::BigPage:ver<0.5.1>:auth<Perl 6>
Pod::To::HTML:ver<0.7.0>:auth<github:Raku>
Pod::Utilities:ver<0.0.1>
SVG
SVG::Plot
Shell::Command
Slang::Tuxic:ver<0.0.1>:auth<github:FROGGS>
Star::Modules:ver<2020.02.27>
TAP:ver<0.1.0>
Temp::Path:ver<1.001007>
Template::Mojo:ver<v.0.1>
Template::Mustache:ver<1.1.4>:auth<github:softmoth>
Terminal::ANSIColor:ver<0.5>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
Test::Mock:ver<1.5>
Test::Output:ver<1.001002>
Test::Util::ServerPort:ver<0.0.2>:auth<github:jonathanstowe>:api<1.0>
Test::When:ver<1.001008>
Testo:ver<1.003006>
Text::CSV:ver<0.009>:auth<github:Tux>
URI:ver<0.3.0>
XML::Writer
p6doc:ver<1.003>:auth<perl6>
zef:ver<0.8.4>:auth<github:ugexe>:api<0>

**Comment by ugexe** [comment]
use `--exclude=perl` to skip the dependency

**Comment by hakonhagland** [comment]
Same issue, Windows 10, zef version 0.11.7, raku version 2021.05 : 
```
> zef install Inline::Perl5
===> Searching for: Inline::Perl5
===> Updating fez mirror: http://360.zef.pm/
===> Updated fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Searching for missing dependencies: perl:from<native>, File::Temp, Distribution::Builder::MakeFromJSON:ver<0.6+>
===> Failed to find dependencies: perl:from<native>
Failed to resolve some missing dependencies (use e.g. --exclude="perl" to skip)
```
I then tried to use `--exclude=perl` (what does this option do? and why do we need it?) : 
```
> zef --exclude=perl install Inline::Perl5
===> Searching for: Inline::Perl5
===> Searching for missing dependencies: File::Temp, Distribution::Builder::MakeFromJSON:ver<0.6+>
===> Searching for missing dependencies: File::Directory::Tree, System::Query
===> Searching for missing dependencies: JSON::Fast
===> Building: Inline::Perl5:ver<0.53>:auth<github:niner>
===> Building [FAIL]: Inline::Perl5:ver<0.53>:auth<github:niner>
Aborting due to build failure: Inline::Perl5:ver<0.53>:auth<github:niner> (use --force-build to override)

```

**Comment by ugexe** [comment]
`--exclude=perl` makes zef skip the dependency named `perl` https://github.com/niner/Inline-Perl5/blob/e125cc4fbfa67a969cfc19b3e5a60b76cd473d64/META6.json#L21

As for why it doesn't successfully build for you on windows... can you build it manually? I'm guessing you cannot, and that Inline::Perl5 make stuff isn't windows friendly.
