### ISSUE TITLE
Alpine zef needs missing rakudo-m

### ISSUE THREAD

**Issue by bbkr** [ugexe/zef#403]
Looks like there is some inconsistency in Alpine `rakudo` and `zef` packages:

Dockerfile:
```dockerfile
FROM alpine

RUN apk add --no-cache rakudo zef
```

In container:
```
zef install JSON::Tiny

...
[JSON::Tiny] Could not execute (/usr/bin/rakudo-m t/01-parse.t): open3: exec of /usr/bin/rakudo-m t/01-parse.t failed: No such file or directory at /usr/share/perl5/core_perl/TAP/Parser/Iterator/Process.pm line 165.
```

So looks like `rakudo` package is not providing symlink `raku` -> `rakudo-m`, which zef wants to use.

**Comment by ugexe** [comment]
I don't think thats a problem with zef, its a problem with https://github.com/rakudo/rakudo/pull/4358

**Comment by bbkr** [comment]
It does, sort of - https://github.com/ugexe/zef/blob/602c54f1069631fd527473f4028451e5c47bc42c/lib/Zef/Service/Shell/prove.rakumod#L114 .

```
~ $ raku -e 'say $*EXECUTABLE.absolute'
/usr/bin/rakudo-m
```

So where this bug should go?
* Alpine `rakudo` package, because it is sane to assume binary pointed by `$*EXECUTABLE.absolute` should be present or at least symlinked?
* Rakudo itself, because it is reporting something nonexistent?

**Comment by ugexe** [comment]
Probably both. I would expect Alpine to include a `rakudo` regardless of this issue, but I would also expect `$*EXECUTABLE` to always point to an existing file

**Comment by ugexe** [comment]
ping @patrickbkr

**Comment by patrickbkr** [comment]
The [Alpine Rakudo package](https://pkgs.alpinelinux.org/contents?branch=edge&name=rakudo&arch=x86_64&repo=community) *does* contain a `/usr/bin/rakudo-m`. I don't have a good hypothesis yet of what actually goes wrong.
I agree this is surely not a bug in zef.

**Comment by patrickbkr** [comment]
Latest Alpine only has Rakudo 2020.12. That indeed doesn't provide rakudo-m. I now think it's a bug in the Alpine Rakudo 2020.12 package. I'm investigating.

**Comment by patrickbkr** [comment]
Nope, not the Alpine packages fault. It was a legitimate Rakudo bug.
