### ISSUE TITLE
Feature Request: Add support for `install 'Some::Mod:ver<1.2.3>:auth<tld:author>'`

### ISSUE THREAD

**Issue by littlebenlittle** [ugexe/zef#404]
Allow installing a specific version of a module using the Raku package syntax.

The advantage here is that you can copy and paste the full module specification from a Raku project and get the same module that the author is using.

**Comment by ugexe** [comment]
This has worked for 5+ years

**Comment by ugexe** [comment]
see https://github.com/ugexe/zef#install-identities
