### ISSUE TITLE
zef update commands takes a long time / provides no progress feedback

### ISSUE THREAD

**Issue by Altai-man** [ugexe/zef#410]
## Context

When running a Blin with zef, I noticed `zef update` command takes a significant time. When I decided to check if it's just a docker issue or maybe the config is broken, I run it locally, but:

```
> time zef --debug update
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated fez mirror: http://360.zef.pm/
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
----------------------------------------------------
Content Storage                  |Distribution Count
----------------------------------------------------
Zef::Repository::Ecosystems<p6c> |914               
Zef::Repository::Ecosystems<cpan>|2779              
Zef::Repository::Ecosystems<fez> |402               
Zef::Repository::LocalCache      |184               
----------------------------------------------------

________________________________________________________
Executed in  250.21 secs    fish           external
   usr time  251.42 secs  498.00 micros  251.42 secs
   sys time   12.14 secs   66.00 micros   12.14 secs

[13:29:19] koto@fedora /home/koto  
> raku --version
Welcome to Rakudo(tm) v2021.05.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05.
[13:34:55] koto@fedora /home/koto  
> zef --version
v0.11.7
[13:34:58] koto@fedora /home/koto  
> cat /proc/cpuinfo | grep name | uniq
model name	: AMD Ryzen 9 5950X 16-Core Processor
[13:36:02] koto@fedora /home/koto  
> time zef --debug update
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated fez mirror: http://360.zef.pm/
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
----------------------------------------------------
Content Storage                  |Distribution Count
----------------------------------------------------
Zef::Repository::LocalCache      |184               
Zef::Repository::Ecosystems<fez> |402               
Zef::Repository::Ecosystems<p6c> |914               
Zef::Repository::Ecosystems<cpan>|2779              
----------------------------------------------------

________________________________________________________
Executed in  288.74 secs    fish           external
   usr time  284.43 secs  614.00 micros  284.43 secs
   sys time   13.70 secs   83.00 micros   13.70 secs
```

So it took 250 seconds natively, while in docker it takes even more time.
The lines `Updated ...` are showing almost immediately, so it is not a network issue, and then 99% of time pass before the table of results is printed. It is 1)unclear if the whole thing just hangs or not; 2)takes much longer than expected.

## Expected Behavior

A feedback is present and/or it takes less time.

## Actual Behavior

Updating metadata for ecosystems on 5950X takes 4 minutes.

## Steps to Reproduce

`time zef --debug update`. I'll post any relevant configs / command outputs if it can help.

## Your Environment

* raku -v

Welcome to Rakudo(tm) v2021.05.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05.

* zef list --installed

```
===> Found via /home/koto/.rakubrew/versions/moar-2021.05/install/share/perl6/core
CORE:ver<6.d>:auth<perl>
===> Found via /home/koto/.rakubrew/versions/moar-2021.05/install/share/perl6/site
App::IRC::Log:ver<0.0.10>:auth<cpan:ELIZABETH>
App::IRC::Log:ver<0.0.11>:auth<cpan:ELIZABETH>
App::IRC::Log:ver<0.0.5>:auth<cpan:ELIZABETH>
App::IRC::Log:ver<0.0.7>:auth<cpan:ELIZABETH>
App::OrgSleep:ver<0.0.8>
Archive::Libarchive::Raw:ver<0.1.0>
Archive::Libarchive:ver<0.0.14>
Array::Sorted::Util:ver<0.0.6>:auth<cpan:ELIZABETH>
AttrX::Lazy:ver<0.0.3>
Base64:ver<0.0.2>:auth<github:ugexe>
CBOR::Simple:ver<0.0.9>:auth<zef:japhb>
CompUnit::Repository::Mask:ver<0.0.1>
CompUnit::Repository::Tar:ver<0.0.2>:auth<github:ugexe>:api<0>
Config::JSON:ver<1.001003>
Config::TOML:ver<0.1.1>:auth<atweiden>
Crane:ver<0.1.0>:auth<atweiden>
Cro::Core:ver<0.8.5>
Cro::Core:ver<0.8.6>
Cro::HTTP:ver<0.8.5>
Cro::HTTP:ver<0.8.6>
Cro::TLS:ver<0.8.5>
Cro::TLS:ver<0.8.6>
Cro::WebApp:ver<0.8.5>
Cro::WebApp:ver<0.8.6>
Crypt::Random:ver<0.4.1>:auth<github:skinkade>
DB::Pg:ver<1.1>:auth<github:CurtTilmes>:api<1>
DateTime::Parse:ver<0.9.1>
DateTime::Timezones:ver<0.3.5>:auth<github:alabamenhu>
Digest::HMAC:ver<1.0.2>:auth<github:retupmoca>
Digest::SHA1::Native:ver<0.04>
Digest:ver<0.3.4>:auth<Lucien Grondin>
Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
Distribution::Common:ver<0.0.2>:auth<github:ugexe>:api<0>
Encode:ver<0.0.3>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1.1>
File::Temp:ver<0.0.8>
File::Which:ver<1.0.1>
HTTP::HPACK:ver<0.9.2>
HTTP::Status:ver<0.0.1>
HTTP::UserAgent:ver<1.1.51>:auth<github:sergot>
IO::Capture::Simple:ver<v.0.0.1>
IO::Path::ChildSecure:ver<1.001011>
IO::Socket::Async::SSL:ver<0.7.7>:auth<jnthn>
IO::Socket::SSL:ver<0.0.2>:auth<github:sergot>
IRC::Channel::Log:ver<0.0.31>:auth<cpan:ELIZABETH>
IRC::Channel::Log:ver<0.0.33>:auth<cpan:ELIZABETH>
IRC::Log::Colabti:ver<0.0.28>:auth<cpan:ELIZABETH>
IRC::Log::Colabti:ver<0.0.30>:auth<cpan:ELIZABETH>
IRC::Log::Colabti:ver<0.0.31>:auth<cpan:ELIZABETH>
IRC::Log:ver<0.0.5>:auth<cpan:ELIZABETH>
IRC::Log:ver<0.0.6>:auth<cpan:ELIZABETH>
IRC::Log:ver<0.0.7>:auth<cpan:ELIZABETH>
Inline::Perl5:ver<0.53>:auth<github:niner>
JSON::Class:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.15>
JSON::Fast:ver<0.16>
JSON::JWT:ver<1.0>:auth<github:retupmoca>
JSON::Marshal:ver<0.0.20>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.5>:auth<github:jonathanstowe>:api<1.0>
JSON::Unmarshal:ver<0.08>
LibCurl:ver<1.4>:auth<github:CurtTilmes>:api<1>
LibGit2:ver<0.4>:auth<github:CurtTilmes>:api<1>
LibUUID:ver<0.5>:auth<github:CurtTilmes>
LibraryCheck:ver<0.0.10>:auth<github:jonathanstowe>:api<1.0>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.13.0>:auth<github:jonathanstowe>:api<1.0>
Log::Timeline:ver<0.3>
META6:ver<0.0.25>:auth<github:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
Math::Matrix:ver<0.3.9>:auth<github:pierre-vigier>
NativeHelpers::Blob:ver<0.1.12>:auth<github:salortiz>
NativeLibs:ver<0.0.9>:auth<github:salortiz>
OO::Monitors:ver<1.1.1>
OpenSSL:ver<0.1.24>:auth<github:sergot>
PrettyDump:ver<1.2.1>
Readline:ver<0.1.6>:auth<cpan:fooist>
Shell::Command
String::Color:ver<0.0.7>:auth<cpan:ELIZABETH>
Sustenance:ver<0.0.1>:auth<atweiden>
System::Query:ver<0.1.6>:auth<zef:tony-o>
Temp::Path:ver<1.001007>
Test::Base
Test::META:ver<0.0.17>:auth<github:jonathanstowe>:api<1.0>
Test::Util::ServerPort:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
Test::When:ver<1.001008>
Testo:ver<1.003006>
TinyFloats:ver<0.0.3>:auth<zef:japhb>
URI:ver<0.3.1>
ake:ver<0.1.0>:auth<Jonathan Scott Duff <duff@pobox.com>>
if:ver<0.1.1>:auth<github:FROGGS>
p6-RandomColor:ver<v.0.11>
zef:ver<0.11.7>:auth<github:ugexe>:api<0>
```

**Comment by ugexe** [comment]
Something seems off, but not really sure what. I would first delete `~/.zef` and see if performance improved just to rule it out. If that doesn't help try and see if the update happens faster with the install command e.g. `zef install CSV::Parser --update --debug` (which would suggest something like building the table is the slow part since that table doesn't get created for `install`).

I won't have time to poke at this until this weekend but for anyone interested in adding some debug/timing statements the updates get fired here:
https://github.com/ugexe/zef/blob/70e71445e4c3b145bf8c8213a6bf923d0e850bc8/lib/Zef/Repository.rakumod#L209
from:
https://github.com/ugexe/zef/blob/70e71445e4c3b145bf8c8213a6bf923d0e850bc8/lib/Zef/CLI.rakumod#L966-L968
and then are processed here:
https://github.com/ugexe/zef/blob/70e71445e4c3b145bf8c8213a6bf923d0e850bc8/lib/Zef/CLI.rakumod#L969-L973

**Comment by Altai-man** [comment]
I tried to look at the .zef directory before just removing it and oh wow, I am seeing something "incredible":

![Peek 2021-09-10 18-44](https://user-images.githubusercontent.com/5764435/132888652-1ac63fa9-4fc0-4b88-8087-d743b75a7838.gif)

Clues?

**Comment by ugexe** [comment]
Yeah something is certainly wrong. It looks like `Zef::Utils::FileSystem::copy-paths` is involved in someway, potentially getting passed the wrong path for some reason -- https://github.com/ugexe/zef/search?q=copy-paths

Unfortunately it doesn't seem easily reproducible. Below I managed to get a `~/.zef/store/store` a single time after wiping `~/.zef`, but repeating the process afterwards isn't giving me that same problem directory. It almost feels like confusion about what the cwd is, so potentially something about multiple threads + absolute path construction (which uses cwd presumably)...

```
❯ ls ~/.zef/store
360.zef.pm cpan       cpan1.json fez        p6c        p6c1.json

❯ raku -I. bin/zef install CSV::Parser
===> Searching for: CSV::Parser
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated fez mirror: http://360.zef.pm/
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Testing: CSV::Parser:ver<0.1.2>:auth<zef:tony-o>
===> Testing [OK] for CSV::Parser:ver<0.1.2>:auth<zef:tony-o>
===> Installing: CSV::Parser:ver<0.1.2>:auth<zef:tony-o>

❯ ls ~/.zef/store
330336bfa75eb47ddeb4a121b30b7d9d93b1bbfb.tar.gz fez
360.zef.pm                                      p6c
MANIFEST.zef                                    p6c1.json
cpan                                            store
cpan1.json
```

**Comment by ugexe** [comment]
Actually I can reproduce if I explicitly disable `p6c` so it picks up the same version from fez with something like `rm -rf ~/.zef && raku -I. bin/zef install CSV::Parser --/test --update --dry --debug --/p6c`, which makes me think it would be caused by https://github.com/ugexe/zef/commit/04951c79f5884ec823167d2e4944a52e39ca0f83 ( ping @tony-o )

**Comment by tony-o** [comment]
Having a bit of trouble reproducing:

```
+tonyo@local ~/dev/raku/zef⦖ rm -rf ~/.zef && time raku -I. bin/zef install CSV::Parser --/test --update --dry --debug --/p6c
===> Updating fez mirror: http://360.zef.pm/
===> Updated fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for: CSV::Parser
===> Found: CSV::Parser:ver<0.1.2>:auth<zef:tony-o> [via Zef::Repository::Ecosystems<fez>]
===> Fetching: CSV::Parser
[CSV::Parser] Fetching http://360.zef.pm/C/SV/CSV_PARSER/330336bfa75eb47ddeb4a121b30b7d9d93b1bbfb.tar.gz with plugin: Zef::Service::Shell::curl+{<anon|1>}
===> Fetching [OK]: CSV::Parser:ver<0.1.2>:auth<zef:tony-o> to /Users/tonyo/.zef/tmp/1631305924.29474.7316.89887723546/330336bfa75eb47ddeb4a121b30b7d9d93b1bbfb.tar.gz
===> Extracting: CSV::Parser
[CSV::Parser] Extracting with plugin: Zef::Service::Shell::tar+{<anon|1>}
===> Extraction [OK]: CSV::Parser to /Users/tonyo/.zef/store/330336bfa75eb47ddeb4a121b30b7d9d93b1bbfb.tar.gz
===> Filtering: CSV::Parser:ver<0.1.2>:auth<zef:tony-o>
===> Filtering [OK] for CSV::Parser:ver<0.1.2>:auth<zef:tony-o>
===> # SKIP: No need to build CSV::Parser:ver<0.1.2>:auth<zef:tony-o>

real	0m1.869s
user	0m1.603s
sys	0m0.237s
```

I'll take a more in depth look at this tonight

**Comment by ugexe** [comment]
`zef update` is the slow command not `zef install`

**Comment by ugexe** [comment]
The speed issue is because it needs to get a count of valid distributions from each repository, which requires creating a bunch of `Zef::Distribution` objects (something like `my $valid-count = @json.map({ try Zef::Distribution.new(|$_) }).grep(*.defined).elems`). When running `zef install` that overhead was likely avoided with all those flags I used because of lazyness -- the extra time would just show up in a later stage of `install` when the adapters inevitably need to populate their distributions.

I'm leaning towards `zef update` no longer printing the result table or counts unless `--verbose` or `--debug` is passed. Such a change brings `zef update` down to ~2s with `zef update --verbose` remaining ~20s on one of my systems. @Altai-man would such a change help you, or are you running it (vs `zef install --update ...`) to get those distribution counts in particular?

**Comment by Altai-man** [comment]
@ugexe both `zef update` and `zef update --verbose` (`zef update --debug`) has a very long timing for me.
I'll try next Monday with `.zef` directory renamed to see if it'll be faster.

**Comment by ugexe** [comment]
> @ugexe both zef update and zef update --verbose (zef update --debug) has a very long timing for me.

Right. I can make it so `zef update` without verbose is faster by not printing the table and I'm asking if that is still useful (i.e. you are using `zef update` just to update all the ecosystems) or not (you are also using `zef update` to get count of distributions in each ecosystem in addition and thus would still need to pass `--verbose` and getting slow behavior).

**Comment by ugexe** [comment]
The separate issue of the `~/.zef/store` directory copying itself is caused by tar archives that don't have a directory prefix. Distributions archived with mi6 are not affected; distributions archived with fez are affected. While that should likely be corrected in fez I also have a potential fix with https://github.com/ugexe/zef/commit/244f6ca2b04ff19b95ac66ce92def230072169c7

**Comment by Altai-man** [comment]
If I rename the abnormal .zef directory, I can confirm `zef update` now takes 6.95 seconds.

>I can make it so zef update without verbose is faster by not printing the table and I'm asking if that is still useful (i.e. you are using zef update just to update all the ecosystems) or not (you are also using zef update to get count of distributions in each ecosystem in addition and thus would still need to pass --verbose and getting slow behavior after this theoretical future change).

Aha, I got your intention now. I am just doing update for the sake of update in Blin case.

**Comment by tony-o** [comment]
> The separate issue of the `~/.zef/store` directory copying itself is caused by tar archives that don't have a directory prefix. Distributions archived with mi6 are not affected; distributions archived with fez are affected. While that should likely be corrected in fez I also have a potential fix with https://github.com/ugexe/zef/commit/244f6ca2b04ff19b95ac66ce92def230072169c7

I don't see any reason the dist archive shouldn't be in the archive root. The `tar` utility can also be used to extract to a dir name

**Comment by ugexe** [comment]
> I don't see any reason the dist archive shouldn't be in the archive root. The tar utility can also be used to extract to a dir name

There isn't any reason it cant be infinite levels deep either. In cases like this is just easier to pick a single convention and run with it.

**Comment by tony-o** [comment]
It seems like supporting both modes is the right path forward since fez isn't the only ecosystem and it isn't like that issue is limited to fez.  It seems like an arbitrary thing to require

**Comment by ugexe** [comment]
> It seems like supporting both modes is the right path forward since fez isn't the only ecosystem and it isn't like that issue is limited to fez. Unpacking to a single directory is an arbitrary thing to require

It is supported as of the latest zef release. But a service providing these distributions should be consistent one way or another, so in the case where they need to be normalized (like now in fez where two different tar archive structures exist) it might as well be done in the way consistent with the e.g. git[hub|lab] archive links. Someone manually downloading distributions from fez and unpacking them shouldn't have to figure out the structure of each archive after all, regardless of if zef is smart enough to do it automatically.

**Comment by tony-o** [comment]
neither cpan nor git is reliable in this way.  90% of the modules in fez are packaged with `git archive` and CPAN will serve tar.gz's without a root dir.

Example: https://raku.land/cpan:SEGOMOS/fez

**Comment by patrickbkr** [comment]
> I'm leaning towards `zef update` no longer printing the result table or counts unless `--verbose` or `--debug` is passed. Such a change brings `zef update` down to ~2s with `zef update --verbose` remaining ~20s on one of my systems.

I would welcome that change. My typical use case of just updating the database does not involve paying attention to those numbers (I guess it's the same for most other zef users), so optimizing for that makes sense.

**Comment by Altai-man** [comment]
With the .zef directory structure issue being fixed I do not longer see the issue. And Blin works with zef as well. Thanks for your time!

**Comment by patrickbkr** [comment]
I agree with this issue being closed. But apart from that I'd still like to see the change to speed up `zef update` by not displaying statistics happen.

**Comment by tony-o** [comment]
There is going to be a fix coming in the zef eco to help fix this issue but it's going to take a while to happen
