### ISSUE TITLE
Complaints about deprecated $*PERL

### ISSUE THREAD

**Issue by vonbrand** [ugexe/zef#415]
Running latest zef (0.12.0) on recent rakudo (2021.09-246-g59debb4e7) complains about deprecated $*PERL. A simple patch is attached (renamed to *.txt, as github doesn't like *.patch)
[0001-Deprecated-PERL-in-Zef-Repository-Zef-Client.txt](https://github.com/ugexe/zef/files/7297499/0001-Deprecated-PERL-in-Zef-Repository-Zef-Client.txt)

## Context

Zef itself tells me to report this ;-)
$ zef upgrade
# ...
Saw 1 occurrence of deprecated code.
================================================================================
$*PERL seen at:
  /home/vonbrand/share/perl6/site/sources/2152003580E1E8C66B0510A7E7976C4D88D82506 (Zef::Repository), line 128

## Expected Behavior
Silence

## Actual Behavior

See above

## Your Environment

* raku -v
* zef list --installed
$ raku -v
Welcome to Rakudo™ v2021.09-246-g59debb4e7.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.09-584-g962e835dc.

$ zef list --installed
===> Found via /home/vonbrand/share/perl6/core
CORE:ver<6.d>:auth<perl>
===> Found via /home/vonbrand/share/perl6/site
DateTime::Parse:ver<0.9.1>
Debugger::UI::CommandLine
Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
Encode:ver<0.0.3>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1.1>
File::Find:ver<0.1>
File::Temp:ver<0.0.8>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
HTTP::Status:ver<0.0.1>
HTTP::UserAgent:ver<1.1.49>:auth<github:sergot>
HTTP::UserAgent:ver<1.1.50>:auth<github:sergot>
HTTP::UserAgent:ver<1.1.51>:auth<github:sergot>
IO::Capture::Simple:ver<v.0.0.1>
IO::Socket::SSL:ver<0.0.1>:auth<github:sergot>
IO::Socket::SSL:ver<0.0.2>:auth<github:sergot>
Inline::Perl5:ver<0.52>:auth<github:niner>
Inline::Perl5:ver<0.53>:auth<github:niner>
Inline::Perl5:ver<0.54>:auth<github:niner>
Inline::Perl5:ver<0.55>:auth<github:niner>
Inline::Perl5:ver<0.56>:auth<github:niner>
JSON::Class:ver<0.0.14>:auth<github:jonathanstowe>:api<1.0>
JSON::Class:ver<0.0.15>:auth<github:jonathanstowe>:api<1.0>
JSON::Class:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
JSON::Class:ver<0.0.17>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.10>
JSON::Fast:ver<0.12>
JSON::Fast:ver<0.13>
JSON::Fast:ver<0.14>
JSON::Fast:ver<0.15>
JSON::Fast:ver<0.16>
JSON::Marshal:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Marshal:ver<0.0.19>:auth<github:jonathanstowe>:api<1.0>
JSON::Marshal:ver<0.0.20>:auth<github:jonathanstowe>:api<1.0>
JSON::Marshal:ver<0.0.21>:auth<github:jonathanstowe>:api<1.0>
JSON::Marshal:ver<0.0.22>:auth<github:jonathanstowe>:api<1.0>
JSON::Marshal:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.4>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.5>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.6>:auth<github:jonathanstowe>:api<1.0>
JSON::OptIn:ver<0.0.1>:auth<github:jonathanstowe>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
LWP::Simple:ver<0.106>:auth<github:perl6>
LibraryCheck:ver<0.0.10>:auth<github:jonathanstowe>:api<1.0>
LibraryCheck:ver<0.0.9>:auth<github:jonathanstowe>:api<1.0>
License::SPDX:ver<3.11.0>:auth<github:jonathanstowe>:api<1.0>
License::SPDX:ver<3.11.1>:auth<github:jonathanstowe>:api<1.0>
License::SPDX:ver<3.12.0>:auth<github:jonathanstowe>:api<1.0>
License::SPDX:ver<3.13.0>:auth<github:jonathanstowe>:api<1.0>
License::SPDX:ver<3.14.0>:auth<github:jonathanstowe>:api<1.0>
License::SPDX:ver<3.8.0>:auth<github:jonathanstowe>:api<1.0>
License::SPDX:ver<3.9.0>:auth<github:jonathanstowe>:api<1.0>
META6:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
META6:ver<0.0.24>:auth<github:jonathanstowe>:api<1.0>
META6:ver<0.0.25>:auth<github:jonathanstowe>:api<1.0>
META6:ver<0.0.26>:auth<github:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.1>:auth<github:retupmoca>
Memoize:ver<0.0.6>:auth<cpan:ELIZABETH>
Memoize:ver<0.0.7>:auth<cpan:ELIZABETH>
Memoize:ver<0.0.8>:auth<cpan:ELIZABETH>
OO::Monitors:ver<1.1.1>
OpenSSL:ver<0.1.23>:auth<github:sergot>
Perl6::TypeGraph:ver<2.1.2>:auth<github:antoniogamiz>:api<2>
Perl6::TypeGraph:ver<2.1.3>:auth<github:antoniogamiz>:api<2>
Perl6::TypeGraph:ver<2.2>:auth<github:antoniogamiz>:api<2>
Pod::Load:ver<0.5.5>
Pod::Load:ver<0.5.6>
Pod::To::BigPage:ver<0.5.1>:auth<Perl 6>
Pod::To::BigPage:ver<0.5.2>:auth<Perl 6>
Pod::To::HTML:ver<0.7.0>:auth<github:Raku>
Pod::To::HTML:ver<0.7.1>:auth<github:Raku>
Pod::To::HTML:ver<0.8.1>:auth<github:Raku>
Pod::To::HTML:ver<0.8>:auth<github:Raku>
Pod::To::Latex:ver<0.1.1>
Pod::To::Markdown:ver<0.1.4>
Pod::To::Markdown:ver<0.2.1>:auth<github:softmoth>
Pod::To::Markdown:ver<v.0.1.4>
Pod::Utilities:ver<0.0.1>
Readline:ver<0.1.5>:auth<github:drforr>
System::Query:ver<0.1.6>:auth<zef:tony-o>
TOML:ver<2>:auth<zef:tony-o>:api<0>
TOML:ver<3>:auth<zef:tony-o>:api<0>
Template::Mustache:ver<1.1.4>:auth<github:softmoth>
Template::Mustache:ver<1.2.1>:auth<github:softmoth>
Template::Mustache:ver<1.2.2>:auth<github:softmoth>
Template::Mustache:ver<1.2.3>:auth<github:softmoth>
Terminal::ANSIColor:ver<0.5>
Test::META:ver<0.0.16>:auth<github:jonathanstowe>:api<1.0>
Test::META:ver<0.0.17>:auth<github:jonathanstowe>:api<1.0>
Test::Output:ver<1.001002>
Test::Util::ServerPort:ver<0.0.2>:auth<github:jonathanstowe>:api<1.0>
Test::Util::ServerPort:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
Test::When:ver<1.001008>
URI:ver<0.3.0>
URI:ver<0.3.1>
URI:ver<0.3.2>
URI:ver<0.3.3>
p6doc:ver<1.003>:auth<perl6>
p6doc:ver<1.006.d>:auth<perl6>
zef:ver<0.10.0>:auth<github:ugexe>:api<0>
zef:ver<0.11.0>:auth<github:ugexe>:api<0>
zef:ver<0.11.10>:auth<github:ugexe>:api<0>
zef:ver<0.11.11>:auth<github:ugexe>:api<0>
zef:ver<0.11.13>:auth<github:ugexe>:api<0>
zef:ver<0.11.1>:auth<github:ugexe>:api<0>
zef:ver<0.11.2>:auth<github:ugexe>:api<0>
zef:ver<0.11.4>:auth<github:ugexe>:api<0>
zef:ver<0.11.5>:auth<github:ugexe>:api<0>
zef:ver<0.11.6>:auth<github:ugexe>:api<0>
zef:ver<0.11.7>:auth<github:ugexe>:api<0>
zef:ver<0.11.8>:auth<github:ugexe>:api<0>
zef:ver<0.11.9>:auth<github:ugexe>:api<0>
zef:ver<0.12.0>:auth<github:ugexe>:api<0>
zef:ver<0.8.4>:auth<github:ugexe>:api<0>
zef:ver<0.8.5>:auth<github:ugexe>:api<0>
zef:ver<0.9.1>:auth<github:ugexe>:api<0>
zef:ver<0.9.3>:auth<github:ugexe>:api<0>
zef:ver<0.9.4>:auth<github:ugexe>:api<0>

**Comment by ugexe** [comment]
Resolved in https://github.com/ugexe/zef/commit/e4092d5142d9f53246ecfe4be320729f9faa5cdb
