### ISSUE TITLE
Weird issue: zef can't find itself... sometimes

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#430]
I'm trying to set up a Docker image that contains zef, and it works locally, it does not work in a CI environment such as GitHub.

## Context

Created a series of images that use Alpine as base. Since GitHub Actions use UID 1001 for their user, I've created a container that has a `raku` user with that UID. zef works perfectly... locally. However, [this happens](https://github.com/JJ/p6-pod-load/runs/4573911222?check_suite_focus=true) in GitHub actions: zef is found, however zef is unable to find its own library module yielding a 

```
===SORRY!===
No candidate found for 'zef'.
```

## Expected Behavior

Work the same as locally

## Actual Behavior

No zef command works, although it's in the path and it's actually run.

## Steps to Reproduce

Check out [failing GitHub actions here](https://github.com/JJ/p6-pod-load)

## Your Environment

* raku -v

2021.10

* zef list --installed
```
===> Found via /usr/share/perl6/core
CORE:ver<6.d>:auth<perl>
===> Found via /home/raku/.raku
File::Find:ver<0.1.1>
File::Which:ver<1.0.1>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
Linenoise:ver<0.1.1>:auth<Rob Hoelz>
Shell::Command
zef:ver<0.13.4>:auth<github:ugexe>:api<0>
```

**Comment by ugexe** [comment]
You have changed the default home repository, yet are installing zef to an entirely different home directory. Either install zef to a default repository, or pass the alternative repos to e.g. `RAKULIB`

**Comment by JJ** [comment]
`RAKULIB` sets a `file#` repo. The original installation place is an `inst#` repo. Using RAKULIB will not work.

**Comment by ugexe** [comment]
`RAKULIB` works fine with other repos types, so I'm confused by the language insisting you know otherwise. Anyways there is an example in the zef readme showing it works fine: https://github.com/ugexe/zef#custom-installation-locations

**Comment by JJ** [comment]
As usual, you are right; only the documentation fails to mention that. I'll create an issue to fix that issue. Thanks.
