### ISSUE TITLE
Feature request: Detect and nullify env var TEST_AUTHOR during test mode

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#433]
The environment variable **TEST_AUTHOR** is used by module authors for their own testing. If defined, it may cause an unintended test failure for some modules. Therefore, it shouldn't be respected by zef during module installation unless some new zef option is specifically used. For example:

~~~
   zef install --test-author Foo
~~~

This is not a zef bug, but it was discovered when trying to install **Spreadsheet::Libxlsxio** when I had TEST_AUTHOR defined. I solved the immediate problem by executing:

~~~
    export TEST_AUTHOR=""; zef install Spreadsheet::Libxslxio
~~~

OS: Debian 10
Rakudo: 2021.12

**Comment by ugexe** [comment]
What if someone wants to run the author tests anyway? Generally as an author you probably shouldn't be doing `export TEST_AUTHOR=""`, but instead setting it on a per-command basis i.e. `TEST_AUTHOR="..." prove t/`

**Comment by tbrowder** [comment]
I agree. I have removed my TEST_AUTHOR environment variable from my bash_aliases file.
