### ISSUE TITLE
Cannot install zef as always fails in 'Perl6-ecosystems.git'

### ISSUE THREAD

**Issue by abdulbadii** [ugexe/zef#440]
## Context
as Arch/Artix has no zef yet so try to install by help of pakku... then:

## Expected Behavior
Pass the test and install

## Actual Behavior
Got error...
```
./xt/install.t ...................... ok   
./xt/repository.t ................... 1/5 ===> Updating p6c mirror: git://github.com/ugexe/Perl6-ecosystems.git
!!!> Failed to update p6c mirror: git://github.com/ugexe/Perl6-ecosystems.git
    # Failed test at ./xt/repository.t line 59
        # Failed test at ./xt/repository.t line 63
        # You failed 1 test of 2
    # Failed test 'search'
    # at ./xt/repository.t line 61
    # You failed 2 tests of 2
./xt/repository.t ................... 2/5 # Failed test 'Ecosystems => p6c'

```
...
## Steps to Reproduce
$ sudo pakku -S zef 

## Your Environment
```
$ raku -v
Welcome to Rakudo™ v2021.12.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.
```

Please help out solving this.

**Comment by ugexe** [comment]
I'd suggest not running the xt/ tests then, since those are generally not intended to be run by end users. Maybe you should use zef to install itself instead of a different package manager.
