### ISSUE TITLE
Is it possible that zef interprets timeouts in a different way?

### ISSUE THREAD

**Issue by JJ** [ugexe/zef#442]
## Context

360.zef.pm is lately being a big slow. I notice that on my desktop. However, I get this error in CI:

```
Enabled fetching backends [git path wget] don't understand https://360.zef.pm/P/OD/POD_LOAD/84e13919fdc914b9ae9594eb8aa54baceb4d9679.tar.gz
You may need to configure one of the following backends, or install its underlying software - [curl pswebrequest]
```

## Expected Behavior

Just say it times out. Also timeout configuration would be great

## Actual Behavior

The error does not seem to be on point, since wget is perfectly able to understand that URL.

## Steps to Reproduce

Difficult to reproduce, but I would say it's a flapper when you use zef from CI. Maybe also locally in some cases.

## Your Environment

* raku -v
* zef list --installed

It's the previous version of zef. Admittedly, this might have been fixed, but I haven't see any issue referring to it.

**Comment by ugexe** [comment]
It’s not a timeout. There are a few closed zef issues where I’ve stated it’s an issue in rakudo itself. See https://github.com/ugexe/zef/issues/352
