### ISSUE TITLE
Make "--install-to=site" the default for installation by the root user [feature request]

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#455]
As a part-time, and now amateur sys admin, I believe installing Raku modules to the system site for Raku users should be the standard. That would have several advantages as I see it:

+ given a large set of curated and accessible installed Raku modules, new Raku users would not have to immdiately grapple with learning all about 'zef'

+ avoiding unnecessary module duplication would save space on small devices such as VMs from cloud sellers (Digital Ocean, Linode, etc.)

+ sys admins for larger installations could more easily control the desired module versions available for normal users

At the very least, I think the idea should be discussed on \#raku.  In the meantime,
I will try to adopt that as my standard operating procedure (maybe as a bash alias for root).

## Environment

Debian 11, and always running the latest Raku release via rakudo-pkg and zef via 'zef update'

**Comment by ugexe** [comment]
see: https://github.com/ugexe/zef#basic-settings

The default setting of `auto` will already install to site if the user running zef has appropriate permissions:
```
raku -e 'say CompUnit::RepositoryRegistry.repository-for-name("site").can-install()'
True
```

**Comment by ugexe** [comment]
https://github.com/ugexe/zef/blob/7c46ca2d5a1f78c86a5c543c4080774b30770ddb/lib/Zef/CLI.rakumod#L1219-L1226

You can see here the code that picks a default install-to location will pick `site` if it can

**Comment by tbrowder** [comment]
That sounds ideal. But I have been experimenting with a pristine host, nuking the site and home locations for root and my normal self and starting over. I haven't seen that result, but I may have made a mistake--I'll double check.

BTW, if root auto installs to site, where do I find the config.json for that installation (I really don't grok the config at all)?

**Comment by ugexe** [comment]
It’s possible rakudo regressed it’s can-install method or something. I can assure you zef is not at fault though and you can see the code for yourself to reach the same conclusion.

the config file location can be seen towards the bottom of the output of zef —help

**Comment by tbrowder** [comment]
On Sat, Jun 4, 2022 at 12:10 Nick Logan ***@***.***> wrote:
>
> It’s possible rakudo regressed it’s can-install method or something. I can assure you zef is not at fault though and you can see the code for yourself to reach the same conclusion.
>
> the config file location can be seen towards the bottom of the output of zef —help

Okay, I looked there for the root user and saw this:

{
    "ConfigVersion" : "1",
    "RootDir"  : "$*HOME/.zef",
    "StoreDir" : "$*HOME/.zef/store",
    "TempDir"  : "$*HOME/.zef/tmp",
    "DefaultCUR" : ["auto"],
    "License" : {
        "whitelist" : "*",
        "blacklist" : []
    },
    "Install" : [
        {
            "short-name" : "install-raku-dist",
            "enabled" : 1,
            "module" : "Zef::Service::InstallRakuDistribution"
        }
    ],
    "Report" : [
        {
            "short-name" : "file-reporter",
            "enabled" : 0,
            "module" : "Zef::Service::FileReporter"
        }
    ],
    "Repository" : [
        [
            {
                "short-name": "fez",
                "enabled": 1,
                "module": "Zef::Repository::Ecosystems",
                "options": {
                    "name": "fez",
                    "auto-update": 1,
                    "uses-path": true,
                    "mirrors": [
                        "https://360.zef.pm/"
                    ]
                }
            }
        ],
        [
            {
                "short-name" : "cpan",
                "enabled" : 0,
                "module" : "Zef::Repository::Ecosystems",
                "options" : {
                    "name" : "cpan",
                    "auto-update" : 1,
                    "mirrors" : [

"https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json",

"https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json",
                        "https://github.com/ugexe/Perl6-ecosystems.git"
                    ]
                }
            },
            {
                "short-name" : "p6c",
                "enabled" : 0,
                "module" : "Zef::Repository::Ecosystems",
                "options" : {
                    "name" : "p6c",
                    "auto-update" : 1,
                    "mirrors" : [

"https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json",
                        "https://github.com/ugexe/Perl6-ecosystems.git",
                        "https://ecosystem-api.p6c.org/projects1.json"
                    ]
                }
            }
        ],
        [
            {
                "short-name": "rea",
                "enabled": 1,
                "module": "Zef::Repository::Ecosystems",
                "options": {
                    "name": "rea",
                    "auto-update": 1,
                    "mirrors": [

"https://raw.githubusercontent.com/Raku/REA/main/META.json"
                    ]
                }
            }
        ],
        [
            {
                "short-name" : "cached",
                "enabled" : 1,
                "module" : "Zef::Repository::LocalCache",
                "options" : { }
            }
        ]
    ],
    "Fetch" : [
        {
            "short-name" : "git",
            "module" : "Zef::Service::Shell::git",
            "options" : {
                "scheme" : "https"
            }
        },
        {
            "short-name" : "path",
            "module" : "Zef::Service::FetchPath"
        },
        {
            "short-name" : "curl",
            "module" : "Zef::Service::Shell::curl"
        },
        {
            "short-name" : "wget",
            "module" : "Zef::Service::Shell::wget"
        },
        {
            "short-name" : "pswebrequest",
            "module" : "Zef::Service::Shell::PowerShell::download"
        }
    ],
    "Extract" : [
        {
            "short-name" : "git",
            "module" : "Zef::Service::Shell::git",
            "comment" : "used to checkout (extract) specific
tags/sha1/commit/branch from a git repo"
        },
        {
            "short-name" : "path",
            "module" : "Zef::Service::FetchPath",
            "comment" : "if this goes before git then git wont be able
to extract/checkout local paths because this reaches it first :("
        },
        {
            "short-name" : "tar",
            "module" : "Zef::Service::Shell::tar"
        },
        {
            "short-name" : "p5tar",
            "module" : "Zef::Service::Shell::p5tar"
        },
        {
            "short-name" : "unzip",
            "module" : "Zef::Service::Shell::unzip"
        },
        {
            "short-name" : "psunzip",
            "module" : "Zef::Service::Shell::PowerShell::unzip"
        }
    ],
    "Build" : [
        {
            "short-name" : "default-builder",
            "module" : "Zef::Service::Shell::DistributionBuilder"
        },
        {
            "short-name" : "legacy-builder",
            "module" : "Zef::Service::Shell::LegacyBuild"
        }
    ],
    "Test" : [
        {
            "short-name" : "tap-harness",
            "module" : "Zef::Service::TAP",
            "comment" : "Raku TAP::Harness adapter"
        },
        {
            "short-name" : "prove",
            "module" : "Zef::Service::Shell::prove"
        },
        {
            "short-name" : "raku-test",
            "module" : "Zef::Service::Shell::Test"
        }
    ]
}

**Comment by tbrowder** [comment]
On Sat, Jun 4, 2022 at 12:32 Tom Browder ***@***.***> wrote:

> On Sat, Jun 4, 2022 at 12:10 Nick Logan ***@***.***> wrote:
> >
> > It’s possible rakudo regressed it’s can-install method or something. I
> can assure you zef is not at fault though and you can see the code for
> yourself to reach the same conclusion.
> >
> > the config file location can be seen towards the bottom of the output of
> zef —help
>
> Okay, I looked there for the root user's config and saw this:

...

Doesn't look like it installs into root's $HOME?

-Tom

**Comment by ugexe** [comment]
Maybe it does but you can see the zef logic for choosing — it’s only a few lines long and there is no complicated or tricky logic. If the site repository can-install returns false then rakudo itself doesn’t think that location can be installed to and home would be chosen.

**Comment by tbrowder** [comment]
On Sat, Jun 4, 2022 at 13:28 Nick Logan ***@***.***> wrote:

> Maybe it does but you can see the zef logic for choosing — it’s only a few
> lines long
>
Sorry for all the trouble, Nick. I ran my tests again and all works as you
said. I'll close the issue.

Thanks for your help and patience.

Blessings,

-Tom
