### ISSUE TITLE
[LTA] Missing colon

### ISSUE THREAD

**Issue by habere-et-dispertire** [ugexe/zef#458]
When installing a module and missing one of the colons in the name (`Compress:Bzip2` versus `Compress::Bzip2`), we get the follow message:

~~~
$ zef install Compress:Bzip2
Enabled fetching backends [git path curl wget] don't understand Compress:Bzip2
You may need to configure one of the following backends, or install its underlying software - [pswebrequest]
~~~

An edit distance check against known candidates could help (Did you mean...), or perhaps a check noting the likelihood of a typo if only one colon is present.

Thanks!

**Comment by ugexe** [comment]
The problem is its impossible to know if its supposed to be a name or some type of uri (like `file:`, `git:`, or `https:`) which will typically contain a single colon (and of which the backends are pluggable/extendable).

**Comment by habere-et-dispertire** [comment]
I find it helpful when failures infer common use cases. I was once in the **UK** at a CSS event where the following example stumped me, the tutor and then equally everyone else in attendance (for the better part of an hour):

~~~css
p {
    colour: red;
}
~~~

~~~text
Property "colour" doesn't exist
~~~

Typographical errors are a common use case, but here we see a regional language issue, both of which an edit distance check could help diagnose. If `zef install` fails, it may well still be useful to indicate close matches if they pass some threshold:

~~~text
$ raku zef-install.raku Compress:Li

Enabled fetching backends [git path curl wget] don't understand Compress:Li
You may need to configure one of the following backends, or install its underlying software - [pswebrequest]

Did you mean: Compress::Bzip2, Compress::Zlib, Compress::Zstd ?
~~~

I used the excellent 'Text::Levenshtein::Damerau' to do the heavy lifting with `dld` and then we just filter down:

~~~raku
%lines.sort(               *.value )
      .head(                     3 ) 
      .grep( *.value <= $threshold )
      .map(                 *.keys )
      .join(                  ', ' )
      .fmt( "\nDid you mean: %s ?" )
      .say
~~~

:-)
