### ISSUE TITLE
Install fails - "could not find python..."

### ISSUE THREAD

**Issue by p6steve** [ugexe/zef#460]
When I go:
```zef install Dan::Pandas```

I see this error message:
```
[Dan::Pandas] t/04-upd.t .. ok
[Dan::Pandas] All tests successful.
[Dan::Pandas] Files=4, Tests=104, 41 wallclock secs ( 0.15 usr  0.01 sys + 58.26 cusr  2.10 csys = 60.52 CPU)
[Dan::Pandas] Result: PASS
===> Testing [OK] for Dan::Pandas:ver<0.0.2>:auth<zef:p6steve>:api<1>
===> Installing: Dan::Pandas:ver<0.0.2>:auth<zef:p6steve>:api<1>
===> Install [FAIL] for Dan::Pandas:ver<0.0.2>:auth<zef:p6steve>:api<1>: ===SORRY!=== Error while compiling /home/jovyan/site#sources/7127A72C6AE124BB2B10A740E13DF14B3C28B155 (Dan::Pandas)
===SORRY!=== Error while compiling /home/jovyan/site#sources/853202F5C5315E3288ABD12D78D851BE5560B4CF (Dan)
Could not find python in:
    /home/jovyan/rakudo/share/perl6/site
    /home/jovyan/rakudo/share/perl6/vendor
    /home/jovyan/rakudo/share/perl6/core
    CompUnit::Repository::AbsolutePath<4476520040024>
    CompUnit::Repository::NQP<4476556886072>
    CompUnit::Repository::Perl5<4476556886112>
at /home/jovyan/site#sources/853202F5C5315E3288ABD12D78D851BE5560B4CF (Dan):3

at /home/jovyan/site#sources/7127A72C6AE124BB2B10A740E13DF14B3C28B155 (Dan::Pandas):4
```

## Context

Dan::Pandas depends on Inline::Python
I guess Inline::Python runs some python during the compile, but does not look in right path... the path is:
which python =>  /opt/conda/bin/python
I have tried zef nuke site home and then zef install Dan::Pandas - does not resolve

echo $PATH
/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/jovyan/rakudo/bin:/home/jovyan/rakudo/share/perl6/site/bin:/home/jovyan/rakudo/share/perl6/vendor/bin:/home/jovyan/rakudo/share/perl6/core/bin

## Expected Behavior
Should Install[OK]

## Actual Behavior
Shows Install[FAIL]
BUT - actually install is good anyway

- Info for: Dan::Pandas
- Identity: Dan::Pandas:ver<0.0.2>:auth<zef:p6steve>:api<1>
- Recommended By: Zef::Repository::LocalCache
- Installed: Yes
Description:	 Bridge Dan to Python Pandas
License:	 Artistic-2.0
Source-url:	 git://github.com/p6steve/raku-dan-pandas.git
Provides: 1 modules
Depends: 2 items

## Steps to Reproduce
docker run -it --platform linux/amd64 -p 8888:8888 p6steve/rakudo:ipyjk
zef install Dan::Pandas
(or zef install https://github.com/p6steve/raku-dan-pandas.git)

zef --debug shows nothing of note

Please note there is an unrelated Warning -- but Install[OK} was working fine and this just ignored beforehand
```[Dan::Pandas] WARNING: unhandled Failure detected in DESTROY. If you meant...```

## Your Environment
This is ubuntu...
* raku -v
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.
* zef list --installed
===> Found via /home/jovyan/rakudo/share/perl6/site
Dan::Pandas:ver<0.0.2>:auth<zef:p6steve>:api<1>
Dan:ver<0.0.2>:auth<zef:p6steve>:api<1>
Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
Inline::Python:ver<0.5>:auth<cpan:NINE>
System::Query:ver<0.1.6>:auth<zef:tony-o>
Text::Table::Simple:ver<0.0.8>:auth<github:ugexe>
===> Found via /home/jovyan/rakudo/share/perl6/vendor
App::Prove6:ver<0.0.12>:auth<cpan:LEONT>
Config::Parser::json:ver<1.0.0>:auth<github:arjancwidlak>
Config::Parser::toml:ver<1.0.2>:auth<github:scriptkitties>
Config::Parser::yaml:ver<1.0.0>:auth<github:scriptkitties>
Config::TOML:ver<0.1.2>:auth<atweiden>
Config:ver<3.0.1>:auth<cpan:TYIL>:api<3>
Crane:ver<0.1.1>:auth<atweiden>
DateTime::Format:ver<0.1.4>:auth<zef:raku-community-modules>:api<1.0>
DateTime::Parse:ver<0.9.3>:auth<github:sergot>
Debugger::UI::CommandLine
Digest::MD5:ver<0.05>:auth<cosimo>
Digest:ver<0.7.2>:auth<Lucien Grondin>
Encode:ver<0.0.4>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1.1>
File::Temp:ver<0.0.10>:auth<zef:rbt>
File::Which:ver<1.0.1>
Getopt::Long:ver<0.3.3>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
Grammar::Profiler::Simple:ver<0.02>
HTTP::Status:ver<0.0.4>:auth<zef:lizmat>
HTTP::UserAgent:ver<1.1.51>:auth<github:sergot>
Hash::Merge:ver<2.0.0>:auth<github:scriptkitties>:api<2>
IO::Capture::Simple
IO::Glob:ver<0.9.0>:auth<github:zostay>
IO::Path::XDG:ver<0.2.0>:api<0>
IO::Socket::SSL:ver<0.0.3>:auth<github:sergot>
IO::String:ver<0.1.1>:auth<Rob Hoelz>
JSON::Class:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.17>:auth<cpan:TIMOTIMO>
JSON::Marshal:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.6>:auth<github:jonathanstowe>:api<1.0>
JSON::OptIn:ver<0.0.1>:auth<github:jonathanstowe>
JSON::RPC:ver<1.0.3>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
LWP::Simple:ver<0.108>:auth<zef:raku-community-modules>
LibraryCheck:ver<0.0.10>:auth<github:jonathanstowe>:api<1.0>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.17.0>:auth<github:jonathanstowe>:api<1.0>
Log::Colored:ver<0.1.1>:api<0>
Log:ver<0.3.1>:auth<cpan:TYIL>:api<0>
META6:ver<0.0.26>:auth<github:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.3>:auth<zef:raku-community-modules>
NativeCall::TypeDiag:auth<Sylvain Colinet>
NativeHelpers::Blob:ver<0.1.12>:auth<github:salortiz>
NativeLibs:ver<0.0.9>:auth<github:salortiz>
OO::Monitors:ver<1.1.1>
PathTools:ver<0.1.1>:auth<github:ugexe>
Perl6::TypeGraph:ver<2.1.3>:auth<github:antoniogamiz>:api<2>
Pod::Load:ver<0.7.1>:auth<zef:jjmerelo>
Pod::To::BigPage:ver<0.5.2>:auth<Perl 6>
Pod::To::HTML:ver<0.8.1>:auth<github:Raku>
SVG
SVG::Plot
Shell::Command
TAP:ver<0.3.5>
Temp::Path:ver<1.001007>
Template::Mojo:ver<v.0.1>
Template::Mustache:ver<1.2.3>:auth<github:softmoth>
Terminal::ANSIColor:ver<0.5>
Terminal::LineEditor:ver<0.0.13>:auth<zef:japhb>
Test::META:ver<0.0.17>:auth<github:jonathanstowe>:api<1.0>
Test::Mock:ver<1.5>
Test::Output:ver<1.001004>
Test::Util::ServerPort:ver<0.0.3>:auth<github:jonathanstowe>:api<1.0>
Test::When:ver<1.001009>:auth<zef:raku-community-modules>
Testo:ver<1.003007>:auth<zef:raku-community-modules>
URI:ver<0.3.5>
XML::Writer
YAMLish:ver<0.0.6>
p6doc:ver<1.006.d>:auth<perl6>
zef:ver<0.11.7>:auth<github:ugexe>:api<0>
===> Found via /home/jovyan/rakudo/share/perl6/core
rakudo:ver<2022.07>:auth<Yet Another Society>

**Comment by ugexe** [comment]
It's erroring during precompilation inside of rakudo's `CompUnit::Repository::Installation.install(...)` method. I'm not sure there is anything that can be done in regards to zef.

**Comment by p6steve** [comment]
oh - ok ... please can you suggest next step? raise an Issue on rakudo? Inline::Python?

currently even ```RUN zef install Dan::Pandas --force-install``` still exits from Docker RUN as a build failure ... can zef be cajoled to return 0 in this case?

**Comment by ugexe** [comment]
https://github.com/niner/Inline-Python/issues/40

**Comment by p6steve** [comment]
OK - thanks!
