### ISSUE TITLE
zef update gives errors (use of Any in string)

### ISSUE THREAD

**Issue by rypervenche** [ugexe/zef#462]
Zef gives the following error when running `zef update`:

## Context
```
Use of uninitialized value of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/rypervenche/.raku/sources/3C4F848040A87E6BCF37038095E6C7E514AAA19A (Zef::Repository::LocalCache) line 145
```
## Expected Behavior
`zef update` should run without this error.

## Actual Behavior
Gives the above error 3 times.

## Steps to Reproduce
```
1. Install (from git repo) or update to zef v0.14.0
2. zef update
```

## Your Environment
Gentoo Linux

`raku -v`
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.

`zef list --installed`
===> Found via inst#/usr/share/perl6/core
rakudo:ver<2022.07>:auth<Yet Another Society>
===> Found via inst#/home/rypervenche/.raku
zef:ver<0.14.0>:auth<github:ugexe>:api<0>

**Comment by ugexe** [comment]
Hmmm, I don't get that locally nor do the CI runs. However looking at the referenced code in the error indeed I see I missed committing changes to that file could lead to the error you are getting.
