### ISSUE TITLE
Failed to install TAP module on Windows

### ISSUE THREAD

**Issue by skaji** [ugexe/zef#491]
## Context

zef failed to install TAP module on Windows, not always, but fairly frequently.
This issue may be related to #490.

## Expected Behavior

We can install TAP module.

## Actual Behavior

zef failed to install TAP module on Windows, not always, but fairly frequently.

## Steps to Reproduce

I tried installing TAP module 8 times.
While I successfully installed TAP module once, I failed to install TAP module 7 times.

The output of failure is:

```

Run zef install --/test --trace TAP
  zef install --/test --trace TAP
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
===> Searching for: TAP
===> Updating fez mirror: https://360.zef.pm/
===> Updated fez mirror: https://360.zef.pm/
===> Found: TAP:ver<0.3.11>:auth<cpan:LEONT> [via Zef::Repository::Ecosystems<rea>]
===> Updating rea mirror: https://raw.githubusercontent.com/Raku/REA/main/META.json
===> Fetching: TAP
===> Updated rea mirror: https://raw.githubusercontent.com/Raku/REA/main/META.json
[TAP] Fetching https://raw.githubusercontent.com/raku/REA/main/archive/T/TAP/TAP%3Aver%3C0.3.11%3E%3Aauth%3Ccpan%3ALEONT%3E.tar.gz with plugin: Zef::Service::Shell::curl+{<anon|1>}

===> Fetching [OK]: TAP:ver<0.3.11>:auth<cpan:LEONT> to C:\Users\RUNNER~1\AppData\Local\Temp/.zef\1672745611.2944.7330.691750608229\TAP%3Aver%3C0.3.11%3E%3Aauth%3Ccpan%3ALEONT%3E.tar.gz
===> Extracting: TAP
[TAP] Extracting with plugin: Zef::Service::Shell::tar+{<anon|1>}
===> Extraction [OK]: TAP to C:\Users\RUNNER~1\AppData\Local\Temp/.zef\TAP%3Aver%3C0.3.11%3E%3Aauth%3Ccpan%3ALEONT%3E.tar.gz
===> CompUnit::Repository install target is valid: C:\hostedtoolcache\windows\rakudo\2022.12-01\x86_64\share\perl6\site
===> Filtering: TAP:ver<0.3.11>
===> Filtering [OK] for TAP:ver<0.3.11>
===> # SKIP: No need to build TAP:ver<0.3.11>
===> Installing: TAP:ver<0.3.11>
[TAP] Installing with plugin: Zef::Service::InstallRakuDistribution+{<anon|1>}
===> Install [FAIL] for TAP:ver<0.3.11>: 
Error: Process completed with exit code 1.
``` 

links:
* [github action yaml](https://github.com/skaji/raku-Acme-Test-Module-Zef/blob/327cae324572efa5649dc3610f2dc89a8d87697c/.github/workflows/test.yml)
* [github action log](https://github.com/skaji/raku-Acme-Test-Module-Zef/actions/runs/3829109938/jobs/6515438888)

## Your Environment
raku version 2022.12

**Comment by skaji** [comment]
I found that, if I used raku `2022.07` (instead of the latest `2022.12`),
I could install TAP on windows successfully.

So is this an issue for raku itself?

**github action yaml**
```yaml
name: test

on:
  push:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        number:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
    runs-on: windows-latest
    steps:
      - uses: Raku/setup-raku@v1
        with:
          raku-version: "2022.07"
      - run: zef install --/test --trace TAP
```

**github action log**
https://github.com/skaji/raku-Acme-Test-Module-Zef/actions/runs/3834117062/jobs/6526203605

**Comment by ugexe** [comment]
Do you happen to know if 2022.07 and 2022.12 github actions come with the same version of zef?

**Comment by skaji** [comment]
raku 2022.07 comes with zef v0.13.8.
raku 2022.12 comes with zef v0.14.5.

Note that we used raku from https://rakudo.org/downloads/rakudo
More precisely,
https://rakudo.org/dl/rakudo/rakudo-moar-2022.07-01-win-x86_64-msvc.zip
https://rakudo.org/dl/rakudo/rakudo-moar-2022.12-01-win-x86_64-msvc.zip

**Comment by ugexe** [comment]
Hmm, it doesn't look like any zef changes should result in this type of failure. To be sure you could try installing the most recent version in zef doing something like `git clone https://github.com/ugexe/zef.git && cd zef && raku -I. bin/zef nuke site home --/confirm && raku -I. bin/zef install .`

**Comment by skaji** [comment]
Even after upgrading zef, I could successfully install TAP on windows with raku 2022.07.

**github action yaml**
```yaml
name: test

on:
  push:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        number:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
    runs-on: windows-latest
    steps:
      - uses: Raku/setup-raku@v1
        with:
          raku-version: "2022.07"
      - run: git clone https://github.com/ugexe/zef.git; cd zef; raku -I. bin/zef nuke site home --/confirm; raku -I. bin/zef install .
      - run: zef --version
      - run: zef install --/test --trace TAP
```
**github action log**
https://github.com/skaji/raku-Acme-Test-Module-Zef/actions/runs/3834273219/jobs/6526516362

**Comment by skaji** [comment]
It seems that this is an issue for rakudo, not zef. So I close this issue.
