### ISSUE TITLE
Cannot install modules with zef on multi-user system

### ISSUE THREAD

**Issue by andinus** [ugexe/zef#510]
- Install a module as user `a` with zef
- Try to install a module as user `b` with zef
- zef returns `failed to failed to create directory: /tmp/.zef/1678623551.3000962.2345.9468585221734`

The directory `/tmp/.zef` is owned by `a` so `b` cannot install any modules.

## Your Environment

* raku -v (2023-02)
* zef list --installed (clean install)
* zef --version (v0.18.0)

**Comment by ugexe** [comment]
Ah, that would have started in https://github.com/ugexe/zef/commit/0ba3a1d83547952d555a8155c47819546b559ea1
