### ISSUE TITLE
Failed to create directory '/usr/share/perl6/site/short' with mode '0o777': Failed to mkdir

### ISSUE THREAD

**Issue by mimosinnet** [ugexe/zef#514]
After updating to Rakudo v2023.02, I got this error when using zef:

$ zef info
Failed to create directory '/usr/share/perl6/site/short' with mode '0o777': Failed to mkdir: Permission denied
  in sub MAIN at /home/mimosinnet/.raku/bin/zef line 3
  in block <unit> at /home/mimosinnet/.raku/bin/zef line 1

Zef works again after creating the directories:

- mkdir -m 777 /usr/share/perl6/site/short 
- mkdir -m 777 /usr/share/perl6/vendor/short

Another box with Rakudo v2022.06, without such directories, zef works fine.

**Comment by ugexe** [comment]
see: https://github.com/rakudo/rakudo/blob/7b4b680e3e9a1b8c07549c9d8089211059c6cb52/src/core.c/CompUnit/Repository/Installation.pm6#L142
