### ISSUE TITLE
Feature request: Have option "--serial" be the default for commands "install" and "upgrade"

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#528]
Since discovering option '--serial', I always use it. It seems to make the whole process much easier (and maybe faster).

**Comment by ugexe** [comment]
What does it make easier? I would the only thing it makes easier is installing distributions that have a misconfigured dependency somewhere.

By definition it can’t be faster - it being serial would prevent certain types of optimizations (like how it can be parallelized) less practical (or even impossible).

**Comment by tbrowder** [comment]
Okay, maybe the misconfigured distros are what I'm thinking about. Thanks.
