### ISSUE TITLE
zef install treated "v6" as a dependency

### ISSUE THREAD

**Issue by doomvox** [ugexe/zef#529]
An installation of the new Touch module generates a puzzling error: 

    zef install Touch

    ===> Searching for missing dependencies: v6
    ===> Failed to find dependencies: v6
    Failed to resolve some missing dependencies (use e.g. --exclude="v6" to skip)

Using the indicated exclude works.

    zef --version
    v0.11.7

I've also heard reports of this happening with:

    v0.18.2

raku -v
Welcome to Rakudo™ v2023.02.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.02.

zef list --installed
===> Found via /home/doom/Dust/Sys/Raku/rakudo-star-2023.02/share/perl6/vendor
App::Prove6:ver<0.0.17>:auth<cpan:LEONT>
Config::Parser::json:ver<1.0.0>:auth<github:arjancwidlak>
Config::TOML:ver<0.1.2>:auth<atweiden>
Crane:ver<0.1.1>:auth<atweiden>
DateTime::Format:ver<0.1.4>:auth<zef:raku-community-modules>:api<1.0>
DateTime::Parse:ver<0.9.3>:auth<github:sergot>
Debugger::UI::CommandLine
Digest::MD5:ver<0.05>:auth<cosimo>
Digest:ver<0.28.1>:auth<zef:grondilu>
Encode:ver<0.0.4>:auth<github:sergot>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1.1>
File::Temp:ver<0.0.10>:auth<zef:rbt>
File::Which:ver<1.0.4>
Getopt::Long:ver<0.4.2>
Grammar::Debugger:ver<1.0.1>:auth<github:jnthn>
Grammar::Profiler::Simple:ver<0.02>
HTTP::Status:ver<0.0.4>:auth<zef:lizmat>
HTTP::UserAgent:ver<1.1.51>:auth<github:sergot>
Hash::Merge:ver<2.0.0>:auth<github:scriptkitties>:api<2>
IO::Capture::Simple
IO::Glob:ver<0.9.0>:auth<github:zostay>
IO::Socket::SSL:ver<0.0.3>:auth<github:sergot>
IO::String:ver<0.1.1>:auth<Rob Hoelz>
JSON::Class:ver<0.0.19>:auth<zef:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.17>:auth<cpan:TIMOTIMO>
JSON::Marshal:ver<0.0.24>:auth<zef:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.7>:auth<zef:jonathanstowe>:api<1.0>
JSON::OptIn:ver<0.0.2>:auth<zef:jonathanstowe>
JSON::RPC:ver<1.0.5>:auth<zef:bbkr>
JSON::Tiny:ver<1.0>
JSON::Unmarshal:ver<0.08>
LWP::Simple:ver<0.109>:auth<zef:dwarring>
LibraryCheck:ver<0.0.11>:auth<zef:jonathanstowe>:api<1.0>
LibraryMake:ver<1.0.0>:auth<github:retupmoca>
License::SPDX:ver<3.20.0>:auth<zef:jonathanstowe>:api<1.0>
META6:ver<0.0.29>:auth<zef:jonathanstowe>:api<1.0>
MIME::Base64:ver<1.2.3>:auth<zef:raku-community-modules>
NativeCall::TypeDiag:auth<Sylvain Colinet>
NativeHelpers::Blob:ver<0.1.12>:auth<github:salortiz>
NativeLibs:ver<0.0.9>:auth<github:salortiz>
OO::Monitors:ver<1.1.1>
Path::Finder:ver<0.4.5>
Perl6::TypeGraph:ver<2.1.3>:auth<github:antoniogamiz>:api<2>
Pod::Load:ver<0.7.2>:auth<zef:jjmerelo>
Pod::To::BigPage:ver<0.5.2>:auth<Perl 6>
Pod::To::HTML:ver<0.8.1>:auth<github:Raku>
Pod::Usage:ver<0.0.1>:auth<zef:leont>
Readline:ver<0.1.6>:auth<cpan:fooist>
SVG
SVG::Plot
Shell::Command
TAP:ver<0.3.14>
Temp::Path:ver<1.001007>
Template::Mojo:ver<v.0.1>
Template::Mustache:ver<1.2.3>:auth<github:softmoth>:api<1.2.0>
Terminal::ANSIColor:ver<0.9>:auth<zef:lizmat>
Terminal::LineEditor:ver<0.0.13>:auth<zef:japhb>
Test::META:ver<0.0.19>:auth<zef:jonathanstowe>:api<1.0>
Test::Mock:ver<1.5>
Test::Output:ver<1.001005>
Test::Util::ServerPort:ver<0.0.4>:auth<zef:jonathanstowe>:api<1.0>
Test::When:ver<1.001009>:auth<zef:raku-community-modules>
Testo:ver<1.003007>:auth<zef:raku-community-modules>
URI:ver<0.3.6>:auth<zef:raku-community-modules>
XML::Writer
YAMLish:ver<0.0.6>
sigpipe:ver<0.0.3>:auth<zef:leont>
zef:ver<0.11.7>:auth<github:ugexe>:api<0>
===> Found via /home/doom/.raku
DB::Pg:ver<1.1>:auth<github:CurtTilmes>:api<1>
DBIish:ver<0.6.3>:auth<github:raku-community-modules>
File::Directory::Tree:auth<labster>
File::Find:ver<0.1.1>:auth<Tadeusz “tadzik” Sośnierz>
File::Temp:ver<0.0.8>
File::Which
JSON::Class:ver<0.0.18>:auth<github:jonathanstowe>:api<1.0>
JSON::Fast:ver<0.16>
JSON::Marshal:ver<0.0.23>:auth<github:jonathanstowe>:api<1.0>
JSON::Name:ver<0.0.6>:auth<github:jonathanstowe>:api<1.0>
JSON::OptIn:ver<0.0.1>:auth<github:jonathanstowe>
JSON::Unmarshal:ver<0.08>
LibUUID:ver<0.5>:auth<github:CurtTilmes>
LibraryMake:ver<1.0.0>
License::SPDX:ver<3.15.0>:auth<github:jonathanstowe>:api<1.0>
META6:ver<0.0.26>:auth<github:jonathanstowe>:api<1.0>
NativeHelpers::Blob:ver<0.1.12>:auth<github:salortiz>
NativeLibs:ver<0.0.9>:auth<github:salortiz>
Shell::Command:auth<Tadeusz “tadzik” Sośnierz>
Slang::Tuxic:ver<0.0.1>:auth<github:FROGGS>
Test::META:ver<0.0.17>:auth<github:jonathanstowe>:api<1.0>
Test::When:ver<1.001008>
Text::CSV:ver<0.010>:auth<github:Tux>
URI:ver<0.3.5>
===> Found via /home/doom/Dust/Sys/Raku/rakudo-star-2023.02/share/perl6/site
Algorithm::Diff:ver<0.0.1>
CoreHackers::Sourcery:ver<2.2>:auth<zef:raku-community-modules>
Distribution::Builder::MakeFromJSON:ver<0.6>:auth<github:niner>
Inline::Perl5:ver<0.60>:auth<github:niner>
System::Query:ver<0.1.6>:auth<zef:tony-o>
Text::Diff:ver<1.0.5>:auth<zef:rbt>
Text::Tabs:ver<1.0>:auth<zef:Altai-man>
Touch:ver<0.7.0>:auth<zef:rir>
===> Found via /home/doom/Dust/Sys/Raku/rakudo-star-2023.02/share/perl6/core
rakudo:ver<2023.02>:auth<Yet Another Society>

**Comment by ugexe** [comment]
They shouldn't list `v6` as a dependency -- `use v6` is a pragma -- and indeed it looks like it has been removed on the head of their repo (although they haven't released a new version yet).
