### ISSUE TITLE
Error testing on Windows:  mswin32 not supported

### ISSUE THREAD

**Issue by tbrowder** [ugexe/zef#566]
## Context

While attempting to install ‘PDF::Extract’ on Windows using GitHub workflows testing I got an error, apparently from module ‘Zef::Service::Shell::Test’, that said:

    OS mswin32 not supported

## Expected Behavior

I expect the installation to work. Perhaps I am missing some Windows dependency, but so far I have no clue what that might be.

## Actual Behavior

Test failure.

## Steps to Reproduce

See my workflows log file in repo https://github.com/tbrowder/raku-PDF-Extract.git.

## Your Environment

* raku -v
* zef list --installed

Not applicable.

**Comment by ugexe** [comment]
I'm confused. You are asking about an error condition that you yourself have written and control:
https://github.com/tbrowder/QueryOS/blob/cc97fdf78232a484c7931ac345321af7cb7c7854/lib/QueryOS.rakumod#L96-L99

Closing as this has nothing to do with zef

**Comment by tbrowder** [comment]
My bad. I misread the GitHub workflows--sorry.
