### ISSUE TITLE
Shelling out to `mode` on Windows can fail due to encoding issues

### ISSUE THREAD

**Issue by cygx** [ugexe/zef#65]
`Zef::Utils::SystemInfo` [parses the output](https://github.com/ugexe/zef/blob/master/lib/Zef/Utils/SystemInfo.pm6#L16) of `mode`, which is sensitive to system language and encoding.

In particular, the German output contains the byte 0xF6 (aka latin-1 `ö`), which is invalid UTF-8 and makes the whole thing die with `Malformed UTF-8`.

**Comment by ugexe** [comment]
I was not aware of that, thanks. I think its from `Proc` itself and the `NORMALIZE_ENCODING`:
https://github.com/rakudo/rakudo/blob/nom/src/core/Proc.pm#L43
I imagine most things that use `Proc` and read from `.out` will encounter the same error right now unless the encoding is manually set

I have an idea to workaround it using `unpack` to decode instead, but could you paste the German output of `mode` so I can test the regex?

**Comment by cygx** [comment]
> could you paste the German output of `mode` so I can test the regex?

Sure. Here's what I get on a pristine `cmd` terminal:

    Status von Gerät CON:
    ---------------------
        Zeilen:          300
        Spalten:         80
        Wiederholrate:   31
        Verzögerungszeit:1
        Codepage:        850

**Comment by ugexe** [comment]
# error?
    perl6 -e ".say for shell('mode', :out).out.lines"

    # ok?
    perl6 -e ".say for shell('mode', :out, :enc('latin-1')).out.lines"

I suspect this could fix this specific instance. There are others that will need to be looked at now, but the stdout from those usually is printed back out to the terminal so may require a more targeted solution.
