### ISSUE TITLE
zef doesn't install gitlab urls in the ecosystem

### ISSUE THREAD

**Issue by stmuk** [ugexe/zef#84]
I added Task::Galaxy to the ecosystem hosted as a gitlab raw url and it's installed by panda ok.

However I get 

% zef install Task::Galaxy
===> Searching for: Task::Galaxy
No candidates found matching: Task::Galaxy

**Comment by ugexe** [comment]
Ah, there is a typo in your META6 source field: `gitlabs.com` instead of `gitlab.com`. Maybe panda was finding a cached local copy, because `git clone git://gitlabs.com/stmuk/p6-task-galaxy.git` does not work

**Comment by stmuk** [comment]
Fixed thanks!

 zef confirmed to work with gitlab.com
