### ISSUE TITLE
zef fails to install Inline::Perl5

### ISSUE THREAD

**Issue by Xliff** [ugexe/zef#91]
Here is the output:

$ zef install Inline::Perl5
===> Searching for: Inline::Perl5
===> Searching for missing dependencies: File::Temp
===> Searching for missing dependencies: File::Directory::Tree
===> Fetching: Inline::Perl5
===> Fetching: File::Temp
===> Fetching: File::Directory::Tree
===> Building: Inline::Perl5:ver('0.6'):auth('github:niner')
Failed

Actually thrown at:
  in any  at gen/moar/m-Metamodel.nqp line 3055
  in block <unit> at -e line 1

===> Building [FAIL]: Inline::Perl5:ver('0.6'):auth('github:niner')
===SORRY!===
Aborting due to build failure: Inline::Perl5:ver('0.6'):auth('github:niner')(use --force to override)

**Comment by ugexe** [comment]
Can you post the result when using zef -v install, as well as perl6 -v?

AFAIK Inline::Perl5 itself had problems with rakudo recently and couldn't be installed at all.

**Comment by ugexe** [comment]
This was apparently caused by a new rakudo bug. A backwards compatible workaround has been implemented.
