### ISSUE TITLE
[RFC] Do not attempt to use $cwd/config.json file as config

### ISSUE THREAD

**Issue by zoffixznet** [ugexe/zef#94]
I propose zef does not attempt to load its configuration from `$cwd/config.json`. I can't think of a usecase where `$cwd` as a searchpath for zef's config is useful, but if there is one, perhaps the needed file can be renamed to `$cwd/zef.config.json` or something less generic?

I'm currently working on a project that has its own `config.json` in the project's root directory. Whenever I attempt to install a module to move forward with the development of some new feature, I get the error as in Issue #92, then I have to `cd ..`, install the module, then `cd` back into the project's directory.

It's really annoying and I believe this can be easily rectified.

**Comment by ugexe** [comment]
Resolved in d9bbdf5

Defaults are now `$HOME/.zef/config.json` and `%?RESOURCES<config.json>`, which can be overridden by passing `--config-path $path`

**Comment by zoffixznet** [comment]
Thanks!
